import OBR from '@owlbear-rodeo/sdk';
import {getState,setState,type Language,type ModuleId} from '../state';
import type {TabDef} from '../settings';
export const workbenchSettings=new URLSearchParams(location.search).get('workbench')==='1';
export const featureSettings=new URLSearchParams(location.search).get('section')==='features';
const plainLabel=(label:string)=>label.replace(/<[^>]*>/g,'').replace(/"/g,'&quot;').trim();
const toneKey='full-suite/ui-tone',nightKey='full-suite/ui-night';
const nightMode=()=>{try{return localStorage.getItem(nightKey)==='1';}catch{return false;}};
const row=(label:string,key:string,value:boolean,gm:boolean)=>`<div class="row"><span class="lbl">${label}</span><button class="tog ${value?'on':''}" data-key="${key}" aria-label="${label}" aria-pressed="${value}" ${gm?'':'disabled'}></button></div>`;
const labels:Partial<Record<ModuleId,string>>={hpBar:'生命条组件',threeDragonAnte:'三龙牌',inventory:'背包与公共仓库'};
function optionBody(html:string,selectors:string[]){const root=document.createElement('div');root.innerHTML=html;return [...root.querySelectorAll(selectors.join(','))].map(node=>node.outerHTML).join('');}
function supporterBody(html:string,english:boolean){const root=document.createElement('div');root.innerHTML=html;const intro=root.querySelector('p');if(intro)intro.innerHTML=intro.innerHTML.replace('所有代码开源于 GitHub','当前版本附带对应源码').replace('with all code open-sourced on GitHub','with corresponding source provided alongside this version');const note=root.querySelector('.note');if(note)note.innerHTML=english?'The character-card web app uses the project non-commercial share-alike license. The original Owlbear suite and third-party components retain their respective licenses. <a href="../workbench/LICENSING.md" target="_blank">License details</a>':'角色卡网页采用项目非商用共享许可；原枭熊套件和第三方组件保留各自许可证。<a href="../workbench/LICENSING.md" target="_blank">许可说明</a>';return root.innerHTML;}
export function workbenchTabs(original:TabDef[]):TabDef[]{
 const modules=original.filter(t=>t.moduleId&&t.id!=='follow').map(t=>({id:t.moduleId!,zh:t.id==='search'?'规则资料 / Wiki':t.zh,en:t.id==='search'?'Rules / Wiki':t.en}));
 for(const [id,label] of Object.entries(labels))if(!modules.some(t=>t.id===id))modules.push({id:id as ModuleId,zh:label,en:label});
 const features:TabDef={id:'features',zh:'功能开关',en:'Features',dynamicBody:(lang,gm)=>'<div class="feature-toggle-grid">'+modules.map(t=>`<div class="row feature-toggle-row"><span class="lbl">${lang==='zh'?t.zh:t.en}</span><button class="tog ${getState().enabled[t.id]?'on':''}" data-feature="${t.id}" aria-label="${plainLabel(lang==='zh'?t.zh:t.en)}" aria-pressed="${!!getState().enabled[t.id]}" ${gm?'':'disabled'}></button></div>`).join('')+'</div>',afterRender:(root,gm)=>root.querySelectorAll<HTMLButtonElement>('[data-feature]').forEach(button=>button.addEventListener('click',async()=>{if(!gm)return;button.disabled=true;try{await setState({enabled:{[button.dataset.feature!]:!getState().enabled[button.dataset.feature as ModuleId]} as any});}finally{button.disabled=false;}}))};
 if(featureSettings)return [features];
 const appearance:TabDef={id:'appearance',zh:'界面',en:'Appearance',dynamicBody:()=>{let color='#50525B';try{color=localStorage.getItem(toneKey)||color;}catch{}if(!/^#[0-9a-f]{6}$/i.test(color))color='#50525B';return `<div class="tone-controls"><label for="ui-tone">UI 基准色调</label><input type="color" id="ui-tone" aria-label="UI 基准色调" value="${color}"><input type="text" id="tone-hex" aria-label="颜色代码" maxlength="7" value="${color.toUpperCase()}"><button id="tone-reset">恢复默认</button><label class="night-mode"><input id="ui-night" type="checkbox" ${nightMode()?'checked':''}>黑夜模式</label></div><div class="tone-presets">${[['#50525B','石墨灰'],['#596C7D','雾蓝'],['#667464','苔灰绿'],['#827260','暖褐'],['#72657B','烟紫']].map(([hex,name])=>`<button data-tone="${hex}"><i style="--swatch:${hex}"></i>${name}</button>`).join('')}</div><div class="tone-preview"><strong>Full Suite</strong><span>规则正文 · 角色资料 · 资源记录</span></div>`;},afterRender:root=>{root.querySelector<HTMLInputElement>('#ui-night')!.addEventListener('change',event=>{const value=(event.target as HTMLInputElement).checked;document.documentElement.dataset.suiteNight=String(value);localStorage.setItem(nightKey,value?'1':'0');parent.postMessage({channel:'workbench-panel-frame/v1',night:value},location.origin);});const input=root.querySelector<HTMLInputElement>('#ui-tone')!,hex=root.querySelector<HTMLInputElement>('#tone-hex')!;const apply=(value:string,save=true)=>{if(!/^#[0-9a-f]{6}$/i.test(value))return;input.value=value;hex.value=value.toUpperCase();document.documentElement.style.setProperty('--suite-tone',value);parent.postMessage({channel:'workbench-panel-frame/v1',tone:value},location.origin);if(save)localStorage.setItem(toneKey,value);};input.addEventListener('input',()=>apply(input.value,false));input.addEventListener('change',()=>apply(input.value));hex.addEventListener('change',()=>{if(/^#[0-9a-f]{6}$/i.test(hex.value))apply(hex.value);else hex.value=input.value.toUpperCase();});root.querySelectorAll<HTMLButtonElement>('[data-tone]').forEach(button=>button.addEventListener('click',()=>apply(button.dataset.tone!)));root.querySelector('#tone-reset')!.addEventListener('click',()=>{localStorage.removeItem(toneKey);apply('#50525B',false);});}};
 const scope:TabDef={id:'scope',zh:'同步',en:'Sync',dynamicBody:(lang,gm)=>row(lang==='zh'?'房间内共享功能设置和规则':'Share settings and rules across scenes','crossSceneSyncSettings',getState().crossSceneSyncSettings,gm),afterRender:(root,gm)=>root.querySelector<HTMLButtonElement>('[data-key]')?.addEventListener('click',async()=>{if(gm)await setState({crossSceneSyncSettings:!getState().crossSceneSyncSettings});})};
 const keep=['search','initiative','dice','portals','bossBar','bubbles','dynamicFog','worldPack','support'];
 return [appearance,scope,...keep.map(id=>original.find(t=>t.id===id)!).filter(Boolean).map(tab=>({...tab,moduleId:undefined,body:tab.id==='support'&&tab.body?{zh:supporterBody(tab.body.zh,false),en:supporterBody(tab.body.en,true)}:undefined,dynamicBody:tab.dynamicBody?((lang:Language,gm:boolean)=>{const html=tab.dynamicBody!(lang,gm);if(tab.id==='search')return row(lang==='zh'?'玩家可查看怪物图鉴':'Players can view the bestiary','allowPlayerMonsters',getState().allowPlayerMonsters,gm)+row(lang==='zh'?'Wiki 仅 DM 可见':'Wiki visible to GM only','searchGmOnly',getState().searchGmOnly,gm);if(tab.id==='portals')return '<div id="portal-default-host"></div>';if(['initiative','dice','bossBar','bubbles','search'].includes(tab.id))return optionBody(html,['.row:not(:has([data-key="bubblesRepairLegacyHide"]))']);return html;}):undefined}))];
}
