export type CardLanguage="zh"|"en";
const TEXT:Record<string,readonly [string,string]>={
 fightingStyle:["战斗风格","Fighting Styles"],specialAbilities:["特殊能力","Special Abilities"],
 title:["角色卡信息","Character information"],attributes:["属性","Attributes"],resources:["资源","Resources"],loading:["加载中…","Loading…"],failed:["加载失败","Could not load character"],unavailable:["当前无法查看这张角色卡。","This character is currently unavailable."],sceneClosed:["场景已关闭。","The scene is closed."],retry:["重试","Retry"],unnamed:["未命名","Unnamed"],
 pinned:["已置顶（取消则恢复随选择关闭）","Pinned (unpin to follow selection)"],pin:["置顶面板（取消选中也保持显示）","Pin panel (keep open when deselected)"],nameToggle:["同步 / 清除单位名字","Show / clear token name"],reset:["重画地图血条，修复位置漂移","Redraw token bars to correct their position"],drag:["拖动面板","Drag panel"],raw:["原始数据","Source data"],
 initiative:["先攻","Initiative"],speed:["速度","Speed"],passive:["被动察觉","Passive Perception"],proficiency:["熟练","Proficiency"],dc:["豁免DC","Save DC"],casting:["施法关键属性","Spellcasting ability"],check:["检定","check"],save:["豁免","save"],spellAttack:["法术攻击","Spell attack"],spellAttacks:["近战/远程法术攻击","Melee / ranged spell attack"],attack:["命中","attack"],damage:["伤害","damage"],extra:["附加","extra"],weapons:["武器 / 攻击","Weapons / Attacks"],none:["无","None"],features:["特性","Features"],feats:["专长","Feats"],spells:["法术","Spells"],mastery:["精通","Mastery"],search:["搜索","Search"],searchMastery:["搜索精通词条","Search mastery"],
};
const ABILITIES:Record<string,readonly [string,string,string,string]>={str:["力","力量","STR","Strength"],dex:["敏","敏捷","DEX","Dexterity"],con:["体","体质","CON","Constitution"],int:["智","智力","INT","Intelligence"],wis:["感","感知","WIS","Wisdom"],cha:["魅","魅力","CHA","Charisma"]};
const TERMS:readonly (readonly [string,string])[]=[
 ["体操","Acrobatics"],["特技","Acrobatics"],["驯兽","Animal Handling"],["奥秘","Arcana"],["运动","Athletics"],["欺瞒","Deception"],["欺诈","Deception"],["历史","History"],["洞悉","Insight"],["威吓","Intimidation"],["调查","Investigation"],["医药","Medicine"],["医疗","Medicine"],["自然","Nature"],["察觉","Perception"],["表演","Performance"],["游说","Persuasion"],["宗教","Religion"],["巧手","Sleight of Hand"],["隐匿","Stealth"],["求生","Survival"],["生存","Survival"],
 ["力量","Strength"],["敏捷","Dexterity"],["体质","Constitution"],["智力","Intelligence"],["感知","Wisdom"],["魅力","Charisma"],
 ["酸蚀","Acid"],["寒冷","Cold"],["火焰","Fire"],["力场","Force"],["闪电","Lightning"],["暗蚀","Necrotic"],["黯蚀","Necrotic"],["穿刺","Piercing"],["毒素","Poison"],["心灵","Psychic"],["辐光","Radiant"],["挥砍","Slashing"],["雷鸣","Thunder"],["钝击","Bludgeoning"],
 ["弹药","Ammunition"],["灵巧","Finesse"],["重型","Heavy"],["轻型","Light"],["装填","Loading"],["触及","Reach"],["特殊","Special"],["投掷","Thrown"],["双手","Two-Handed"],["两用","Versatile"],
 ["顺劈","Cleave"],["擦伤","Graze"],["推离","Push"],["推击","Push"],["迅切","Nick"],["削弱","Sap"],["失衡","Sap"],["缓速","Slow"],["击倒","Topple"],["侵扰","Vex"],["烦扰","Vex"],
 ["野蛮人","Barbarian"],["吟游诗人","Bard"],["牧师","Cleric"],["德鲁伊","Druid"],["战士","Fighter"],["武僧","Monk"],["圣武士","Paladin"],["游侠","Ranger"],["游荡者","Rogue"],["术士","Sorcerer"],["邪术师","Warlock"],["法师","Wizard"],["奇械师","Artificer"],
 ["人类","Human"],["精灵","Elf"],["高等精灵","High Elf"],["木精灵","Wood Elf"],["卓尔","Drow"],["半精灵","Half-Elf"],["矮人","Dwarf"],["山地矮人","Mountain Dwarf"],["丘陵矮人","Hill Dwarf"],["半身人","Halfling"],["轻足半身人","Lightfoot Halfling"],["壮心半身人","Stout Halfling"],["侏儒","Gnome"],["森林侏儒","Forest Gnome"],["岩侏儒","Rock Gnome"],["龙裔","Dragonborn"],["提夫林","Tiefling"],["半兽人","Half-Orc"],["兽人","Orc"],["歌利亚","Goliath"],["阿斯莫","Aasimar"],
 ["短棒","Club"],["匕首","Dagger"],["巨棒","Greatclub"],["手斧","Handaxe"],["标枪","Javelin"],["轻锤","Light Hammer"],["硬头锤","Mace"],["长棍","Quarterstaff"],["镰刀","Sickle"],["矛","Spear"],["轻弩","Light Crossbow"],["飞镖","Dart"],["短弓","Shortbow"],["投石索","Sling"],
 ["战斧","Battleaxe"],["链枷","Flail"],["长柄刀","Glaive"],["巨斧","Greataxe"],["巨剑","Greatsword"],["戟","Halberd"],["骑枪","Lance"],["长剑","Longsword"],["巨锤","Maul"],["流星锤","Morningstar"],["长矛","Pike"],["刺剑","Rapier"],["弯刀","Scimitar"],["短剑","Shortsword"],["三叉戟","Trident"],["战镐","War Pick"],["战锤","Warhammer"],["鞭","Whip"],["吹箭筒","Blowgun"],["手弩","Hand Crossbow"],["重弩","Heavy Crossbow"],["长弓","Longbow"],["捕网","Net"],
];
export function ccText(key:string,lang:CardLanguage):string{return TEXT[key]?.[lang==="en"?1:0]??key;}
export function abilityKey(value:unknown):string{const raw=String(value??"").trim().toLowerCase();return Object.keys(ABILITIES).find(key=>key===raw||ABILITIES[key].some(label=>label.toLowerCase()===raw))??raw;}
export function abilityName(key:string,lang:CardLanguage,short=false):string{const entry=ABILITIES[abilityKey(key)];return entry?entry[lang==="en"?(short?2:3):(short?0:1)]:key;}
/** Translate fixed rule terms only. Unknown/custom names remain authored text. */
export function ccTerm(value:unknown,lang:CardLanguage):string{const raw=String(value??"");const normalized=raw.trim().toLowerCase();const pair=TERMS.find(p=>p.some(label=>label.toLowerCase()===normalized));return pair?.[lang==="en"?1:0]??raw;}
export function ccName(value:any,lang:CardLanguage):string{if(typeof value==="string")return ccTerm(value,lang);if(!value)return "";const explicit=lang==="en"?(value.name_en??value.nameEn??value.english_name):(value.name_zh??value.nameZh??value.chinese_name);return typeof explicit==="string"&&explicit.trim()?explicit:ccTerm(value.name??value.class_name??value.cls??"",lang);}
export function ccUnits(value:unknown,lang:CardLanguage):string{const raw=String(value??"");return lang==="en"?raw.replace(/尺/g," ft.").replace(/英里/g," miles").replace(/射程/g,"range ").replace(/伤害/g,"damage "):raw;}
export function ccProperty(value:string,lang:CardLanguage):string{const at=value.search(/[(（]/);return at<0?ccTerm(value,lang):`${ccTerm(value.slice(0,at).trim(),lang)}${ccUnits(value.slice(at),lang)}`;}
