import {rulePrompt, RULE_PROMPTS} from "./rules/prompts";
export type TableLanguage="zh"|"en";
const TEXT:Record<string,readonly [string,string]>={
 title:["三龙牌","Three-Dragon Ante"],edition:["传奇版基础盒 · 自备牌包规则","Legendary base box · Supplied pack rules"],close:["关闭窗口","Close window"],
 backToMap:["返回地图","Back to map"],minimize:["缩小牌桌","Minimize table"],expand:["展开牌桌","Expand table"],inspectCard:["查看卡牌","Inspect card"],closePreview:["关闭卡牌预览","Close card preview"],inspectHint:["悬停或点 i 查看能力","Hover or tap i to read powers"],
 create:["创建牌桌","Create table"],join:["加入牌桌","Join table"],leave:["离开座位","Leave seat"],start:["开始游戏","Start game"],
 newGame:["准备新局","Prepare new game"],retry:["重新连接","Reconnect"],waiting:["等待其他玩家","Waiting for other players"],
 lobby:["2–6 人即可开始，每局随机使用 10 张特殊牌。","Start with 2–6 players. Each game uses 10 random special cards."],
 noTable:["任何玩家都可以创建牌桌。同房间的玩家加入后，由牌桌创建者开局，无需 DM 参与。","Any player can create a table. Once others in the room join, the table creator starts the game. No DM is needed."],
 host:["牌桌创建者","Table creator"],you:["你","You"],spectator:["正在旁观；本局手牌仅座位本人可见。","Spectating. Hands are visible only to their owners."],
 watch:["游戏进行中，可旁观；下一局开始前可加入。","Game in progress. Watch now and join before the next game."],
 seated:["已入座，等待牌桌创建者开局。","Seated. Waiting for the table creator to start."],creatorReady:["你是牌桌创建者，可以点击“开始游戏”发牌。","You created this table. Click Start game to deal."],needPlayers:["等待至少两位玩家入座。","Waiting for at least two players."],
 closeHint:["关窗后仍保留座位，可随时重新打开。","Closing keeps your seat. Reopen at any time."],
 gold:["金币","Gold"],debt:["欠款","Debt"],handCount:["手牌","Hand"],strength:["当前点数","Current strength"],
 stakes:["奖池","Stakes"],hole:["偿债池","Hole"],deck:["牌库","Deck"],gambit:["轮局","Gambit"],round:["轮次","Round"],
 ante:["下注牌","Ante cards"],revealed:["公开待结算","Revealed, resolving"],flight:["牌阵","Flight"],hand:["你的手牌","Your hand"],
 antePrompt:["将一张手牌拖入自己的暗置区；所有人提交后同时翻开。","Drag one hand card to your face-down slot. Reveal together after everyone commits."],
 playPrompt:["轮到你出牌。","Your turn to play."],confirmAnte:["提交下注牌","Commit ante"],confirmPlay:["出这张牌","Play card"],confirmChoice:["确认选择","Confirm choice"],
 selection:["已选","Selected"],chooseRange:["可选数量","Allowed selection"],waitingFor:["等待","Waiting for"],
 committed:["已暗置","Ante committed"],ownAnte:["你的下注牌","Your ante card"],none:["暂无","None"],
 good:["善龙","Good dragon"],evil:["邪龙","Evil dragon"],mortal:["凡人","Mortal"],wild:["颜色百搭","Color wildcard"],rider:["结算时改点数","Strength changes at scoring"],
 leader:["领出","Leader"],acting:["正在操作","Acting"],abilityBy:["能力归属","Ability owner"],effects:["持续效果","Active effects"],
 discard:["弃牌堆","Discard pile"],history:["最近记录","Recent moves"],rules:["官方规则","Official rules"],help:["玩法速览","How to play"],
 helpText:["回合：一名玩家出一张牌并处理效果。轮次：所有人各行动一次。轮局（牌面称斗牌）：从前注到分配奖池，通常三轮。整局：持续多个轮局，轮局末有人没金币时结束。\n\n买牌：自己回合开始仅有 1 张手牌，或触发能力全部结束后没有手牌时，翻开并弃掉牌堆顶 1 张牌，按其点数付款，再从牌堆补至 4 张手牌。金币进奖池，贸易亲王生效时改交给它的能力拥有者；不足部分记入轮局末偿付。不能随意买牌。\n\n每轮结束，用本轮点数最高且不并列的牌决定下一轮领出者；全部并列则保留原领出者。牌面左侧指顺时针相邻玩家，右侧指逆时针相邻玩家。\n\n每人先暗置一张下注牌，一起翻开。最高点数决定每人付款，最高不并列者领出；所有牌均有并列则不付款，弃掉下注牌、各抓一张后重选。按顺时针轮流出牌。轮到你时出一张牌：领出直接发动能力，其余通常在点数不大于逆时针相邻玩家本轮所出牌时发动。先结算能力，再结算组合奖励。通常三轮后比较牌阵总强度，最高者赢奖池，最高并列则加一轮。轮局末补付欠款后若有人没有金币，整局结束，金币最多者获胜。特殊牌可能改变这些规则；规则未定义的局面会暂停并说明原因。","A turn is one player acting; a round is everyone taking one turn; a gambit runs from ante to scoring; a full game ends when anyone has no gold after a gambit. Buy automatically with 1 card at turn start or no cards after powers finish: reveal and discard the top card, pay its strength to stakes (or the active Merchant Prince), then draw to 4 hand cards. Purchases are not voluntary. The highest untied card this round leads the next; all tied retains the leader. Card left means clockwise, right means counterclockwise.\n\nCommit one ante each, then reveal together. The highest strength sets each payment; the highest untied ante leads. If every ante is tied, pay nothing, discard them, draw one each and repeat. Take turns clockwise, playing one card per turn. The leader triggers; other cards normally trigger at equal or lower strength than your counterclockwise neighbor’s card this round. Resolve powers before flight rewards. Normally, after three rounds, the strongest flight wins the stakes; tied highest totals add a round. After unpaid amounts are settled at the end of a gambit, no gold in any hoard ends the game; most gold wins. Special cards may change these rules. Undefined positions pause with an explanation."],
 paused:["需要整桌裁定 · 牌局已暂停","Table ruling needed · Game paused"],pausedHelp:["当前状态已保留。此版本不自动采用桌规；牌桌创建者可在大家确认后重新开局。","The current state is retained. This version does not apply house rules automatically; the table creator may start a new game after everyone agrees."],
 ended:["本局结束","Game ended"],winners:["胜者","Winners"],lastGambit:["上一轮局胜者","Previous gambit winner"],
 resetTitle:["结束当前牌局并回到准备大厅？","End this game and return to the lobby?"],resetBody:["本局手牌与金币进度会清空，座位会保留。请先与同桌玩家确认。回到大厅后可以加入或离席，由牌桌创建者重新开始发牌。","Hands and gold from this game will be cleared; seats are kept. Check with the table first. Players can join or leave in the lobby before the table creator starts dealing again."],
 cancel:["取消","Cancel"],confirmReset:["确认回到大厅","Return to lobby"],sending:["正在处理…","Processing…"],
 connecting:["正在连接牌桌…","Connecting to the table…"],hostOffline:["牌桌创建者的原窗口已离线，等待其恢复牌桌后继续。","The table creator's original window is offline. Play resumes when they restore the table."],
 privateSync:["正在同步你的私有手牌。","Syncing your private hand."],storageFailed:["本机无法保存恢复记录，请检查浏览器存储后重试。","Recovery storage is unavailable. Check browser storage and retry."],
 roomFull:["房间暂时无法保存牌桌设置，请重试。","The room cannot save the table right now. Retry."],tableExists:["房间已有牌桌，可直接加入。","A table already exists. Join it."],tableFull:["六个座位都已坐满，可以旁观。","All six seats are taken. You can watch."],
 notHost:["只有牌桌创建者可以开局或准备新局。","Only the table creator can start or reset the game."],cannotLeave:["游戏进行中无法离开座位；可以直接关窗。","You cannot leave a running game. You can close the window."],
 tooFewPlayers:["至少需要两名玩家。","At least two players are needed."],notSeated:["请先加入牌桌。","Join the table first."],staleTable:["牌桌已变化，请重新连接。","The table changed. Reconnect."],
 invalidCommand:["当前无法执行这个操作。","That action is unavailable."],requestFailed:["未收到处理结果，请重新连接后重试。","No result arrived. Reconnect and retry."],
 recoveryMissing:["当前浏览器没有本局存档，无法还原手牌。请牌桌创建者回到原浏览器恢复，或与同桌玩家确认后重新开局。","This browser has no saved game to restore the hands. The table creator must return to the original browser, or agree with the table to start a new game."],
 protocolMismatch:["玩家与牌桌创建者的插件版本不同，请更新后重新连接。","Player and table creator versions differ. Update and reconnect."],
 druid:["最弱牌阵获胜","Weakest flight wins"],priest:["胜者与顺时针相邻玩家分奖池","Winner shares stakes with clockwise neighbor"],merchant:["买牌款改付能力拥有者","Purchases pay the ability owner"],warlord:["第三轮未赢则加打一轮","Extra round if owner loses round three"],monarch:["获胜后向每位对手支付 3","On winning, pay 3 to each opponent"],dracolich:["结算时每条邪龙 +2","At scoring, +2 per evil dragon"],archmage:["后续出牌均发动","Later cards trigger"],
 DECK_RESHUFFLED:["弃牌已重洗为牌库","Discard reshuffled into deck"],TOOK_STAKES:["领取奖池金币","Took gold from stakes"],PAID_STAKES:["支付到奖池","Paid into stakes"],PAID_PLAYER:["支付给玩家","Paid a player"],
 CARD_REVEALED:["展示手牌","Revealed a card"],CARDS_REVEALED:["公开牌","Revealed cards"],CARD_TRANSFERRED:["转交手牌","Transferred a card"],FLIGHT_REPLACED:["替换牌阵中的牌","Replaced a flight card"],BUY_PRICE:["强制买牌价格","Forced purchase price"],ANTE_REVEALED:["同时翻开下注牌","Antes revealed together"],ANTE_ALL_TIED:["每张下注牌都有并列，重新暗置","Every ante is tied; ante again"],GAMBIT_SCORED:["逐张计算牌阵力量","Flight scoring"],GAMBIT_WON:["赢得轮局","Won the gambit"],GAME_ENDED:["整局结束","Game ended"],POWER_TRIGGERED:["发动能力","Power triggered"],SPECIAL_FLIGHT:["获得组合奖励","Special flight bonus"],DRAGON_REMOVED:["移除龙牌","Removed a dragon"],MORTALS_SWAPPED:["交换凡人牌","Swapped mortals"],CARD_PLAYED:["出牌","Played a card"],
};
export function tableText(code:string,lang:TableLanguage):string{return TEXT[code]?.[lang==="zh"?0:1]??(RULE_PROMPTS[code]?rulePrompt(code,lang):TEXT.requestFailed[lang==="zh"?0:1]);}
