import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {pathToFileURL} from 'node:url';
import {createHash} from 'node:crypto';
const [input,output,runtime]=process.argv.slice(2);
const require=createRequire(import.meta.url);
const {Workbook,SpreadsheetFile}=await import(pathToFileURL(require.resolve('@oai/artifact-tool',{paths:[path.resolve(runtime)]})).href);
const plan=JSON.parse(await fs.readFile(input,'utf8'));
assert.equal(plan.schema,'obr-species-data-plan/v1');assert.ok(plan.entries.length>1000);
assert.equal(await fs.stat(output).then(()=>true,()=>false),false);
const book=Workbook.create(),sheet=book.worksheets.add('English text');
const rows=[['Record','Rules','Cell','English text'],...plan.entries.map(e=>[e.id,e.version,`${e.sheet}!${e.cell}`,e.target])];
const range=sheet.getRange(`A1:D${rows.length}`);
range.values=rows.map(row=>row.map(value=>value.startsWith('=')?`'${value}`:value));
assert.deepEqual(range.values,rows);
range.format.font={name:'Arial',size:11};sheet.getRange(`D1:D${rows.length}`).format.wrapText=true;
for(const [col,width] of [['A',28],['B',9],['C',45],['D',100]])sheet.getRange(`${col}:${col}`).format.columnWidth=width;
sheet.getRange('A1:D1').format.font.bold=true;sheet.freezePanes.freezeRows(1);
const inspected=await book.inspect({kind:'table',range:'English text!A1:D8',include:'values,formulas',tableMaxRows:8,tableMaxCols:4});
await fs.writeFile(output+'.inspect.ndjson',inspected.ndjson);
const preview=await book.render({sheetName:'English text',range:'A1:D8',scale:1,format:'png'});
await fs.writeFile(output+'.preview.png',new Uint8Array(await preview.arrayBuffer()));
const file=await SpreadsheetFile.exportXlsx(book);await file.save(output);
console.log(JSON.stringify({output,sha256:createHash('sha256').update(await fs.readFile(output)).digest('hex'),cells:rows.length*4,valuesExact:true,nativeCardImported:false}));
