// Real Three classes and dependency graph, mocked GL. No GPU/pixel claims.
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {installGroundLiveProbe} from './dice-ground-live-runtime.mjs';
const req=createRequire(process.env.DICE_GROUND_LIVE_PACKAGE_JSON||new URL('../package.json',import.meta.url)),T=req('three');
const oldWebGL2=globalThis.WebGL2RenderingContext;
class GL {
  constructor(){for(const [i,key]of ['NO_ERROR','VIEWPORT','SCISSOR_BOX','SCISSOR_TEST','COLOR_WRITEMASK','DEPTH_WRITEMASK','STENCIL_WRITEMASK','DEPTH_CLEAR_VALUE','STENCIL_CLEAR_VALUE','FRAMEBUFFER','FRAMEBUFFER_COMPLETE','DEPTH_BITS','STENCIL_BACK_WRITEMASK'].entries())this[key]=i;this.drawingBufferWidth=1280;this.drawingBufferHeight=800;this.vp=[0,0,1280,800];this.sc=[10,10,1200,700];this.test=true;this.cm=[true,true,true,true];this.dm=true;this.sm=0xffffffff;this.cd=1;this.cs=0;this.error=0;this.lost=false;}
  isContextLost(){return this.lost;}getError(){const e=this.error;this.error=0;return e;}getExtension(name){return this.unsupported===name?null:{};}isEnabled(){return this.test;}
  getParameter(key){return new Map([[this.VIEWPORT,this.vp],[this.SCISSOR_BOX,this.sc],[this.COLOR_WRITEMASK,this.cm],[this.DEPTH_WRITEMASK,this.dm],[this.STENCIL_WRITEMASK,this.sm],[this.STENCIL_BACK_WRITEMASK,this.sm],[this.DEPTH_CLEAR_VALUE,this.cd],[this.STENCIL_CLEAR_VALUE,this.cs],[this.DEPTH_BITS,24]]).get(key);}
  checkFramebufferStatus(){return this.incomplete?-1:this.FRAMEBUFFER_COMPLETE;}
}
export {GL};
export function fixture({count=20,trusted=true}={}){
 const gl=new GL(),scene=new T.Scene(),camera=new T.OrthographicCamera(-8,8,5,-5,.1,150);camera.position.set(0,44,0);camera.up.set(0,0,1);camera.lookAt(0,0,0);camera.updateMatrixWorld();
 const ground=new T.Mesh(new T.PlaneGeometry(38,22),new T.ShadowMaterial({opacity:.32}));ground.rotation.x=-Math.PI/2;ground.position.y=-.015;ground.receiveShadow=true;
 const light=new T.DirectionalLight();light.position.set(-2.4,9,4.2);light.castShadow=true;Object.assign(light.shadow.camera,{left:-7,right:7,top:7,bottom:-7,near:.5,far:40});light.shadow.camera.updateProjectionMatrix();
 scene.add(ground,light,new T.HemisphereLight());
 const geometry=new T.BoxGeometry(1,1,1),onBeforeCompile=()=>{},customProgramCacheKey=()=> 'trusted-test-builtin';
 const bodies=Array.from({length:count},(_,i)=>{const m=new T.MeshPhysicalMaterial();m.onBeforeCompile=onBeforeCompile;m.customProgramCacheKey=customProgramCacheKey;const body=new T.Mesh(geometry,m);body.castShadow=true;body.receiveShadow=true;body.position.set((i%5)-2,.5,Math.floor(i/5)-2);scene.add(body);return body;});
 let shaders=new Map(),calls=0,failCapture=false,failHit=false,hitError=false,nestedOnce=false,restoreThrows=0;
 const renderer={xr:{isPresenting:false},shadowMap:{enabled:true,type:T.PCFShadowMap,autoUpdate:true,needsUpdate:false},localClippingEnabled:false,clippingPlanes:[],capabilities:{reverseDepthBuffer:false,logarithmicDepthBuffer:false},outputColorSpace:T.SRGBColorSpace,toneMapping:T.ACESFilmicToneMapping,toneMappingExposure:1,sortObjects:true,autoClear:false,autoClearColor:true,autoClearDepth:true,autoClearStencil:true,info:{autoReset:true,render:{frame:0,calls:0}},domElement:new EventTarget(),target:null,viewport:new T.Vector4(0,0,1280,800),scissor:new T.Vector4(10,10,1200,700),color:new T.Color(0),alpha:0,
 state:{buffers:{color:{setMask(v){gl.cm=[v,v,v,v];}},depth:{setMask(v){gl.dm=v;},setClear(v){gl.cd=v;}},stencil:{setMask(v){gl.sm=v;},setClear(v){gl.cs=v;}}}},
 getContext:()=>gl,getPixelRatio:()=>1,getRenderTarget(){return this.target;},getActiveCubeFace:()=>0,getActiveMipmapLevel:()=>0,getCurrentViewport(v){return v.fromArray(gl.vp);},getViewport(v){return v.copy(this.viewport);},getScissor(v){return v.copy(this.scissor);},getScissorTest:()=>gl.test,getClearColor(v){return v.copy(this.color);},getClearAlpha(){return this.alpha;},setClearAlpha(v){this.alpha=v;},setClearColor(v,a){this.color.set(v);this.alpha=a;},setViewport(v){this.viewport.copy(v);gl.vp=v.toArray();},setScissor(v){this.scissor.copy(v);gl.sc=v.toArray();},setScissorTest(v){gl.test=v;},setRenderTarget(t){if(t===null&&restoreThrows>0){restoreThrows--;throw Error('injected restore throw');}this.target=t;gl.vp=(t?.viewport??this.viewport).toArray();gl.sc=(t?.scissor??this.scissor).toArray();gl.test=t?.scissorTest??gl.test;},clear(){this.clears=(this.clears||0)+1;},
 compile(s){s.traverseVisible(o=>{const m=o.material;if(m&&!shaders.has(m)){const shader={fragmentShader:T.ShaderLib.shadow.fragmentShader,uniforms:{}};m.onBeforeCompile(shader,this);shaders.set(m,shader);}});},
 render(s,c){calls++;if(nestedOnce){nestedOnce=false;this.render(s,c);}if(this.target&&failCapture)throw Error('injected capture throw');if(ground.material.customProgramCacheKey()==='diagnostic-ground-live-r32f-v1'&&failHit)throw Error('injected hit throw');if(ground.material.customProgramCacheKey()==='diagnostic-ground-live-r32f-v1'&&hitError){hitError=false;geometry.dispatchEvent({type:'dispose'});}if(this.info.autoReset){this.info.render.calls=0;this.info.render.frame++;}if(this.shadowMap.autoUpdate||this.shadowMap.needsUpdate){if(!light.shadow.map){light.shadow.map=new T.WebGLRenderTarget(64,64);light.shadow.map.depthTexture=new T.DepthTexture(64,64);}light.shadow.updateMatrices(light,c);light.shadow.needsUpdate=false;this.shadowMap.needsUpdate=false;}s.updateMatrixWorld();c.updateMatrixWorld();this.compile(s,c);s.traverseVisible(o=>{if(o.isMesh||o.isLine){this.info.render.calls++;o.onBeforeRender(this,s,c,o.geometry,o.material,null);}});}
 };
 const r={gl:renderer,scene,camera,contextLost:false,active:[{roll:{request:{id:'roll-1'}},start:100,meshes:bodies}]};
 const trust={source:'unit-fixture-known-static-source',exclusiveRenderer:true,rendererRender:renderer.render,bodyMaterialHooks:[{onBeforeCompile,customProgramCacheKey}],geometries:[geometry],decorationShaders:[]};
 const original=renderer.render,material=ground.material;const probe=installGroundLiveProbe({r,T,enabled:true,minBodies:20,stableFrames:2,trust:trusted?trust:undefined});
 const draw=()=>renderer.render(scene,camera);
 return{gl,r,renderer,scene,camera,ground,light,bodies,geometry,probe,draw,original,material,get calls(){return calls;},set failCapture(v){failCapture=v;},set failHit(v){failHit=v;},set hitError(v){hitError=v;},set nestedOnce(v){nestedOnce=v;},set restoreThrows(v){restoreThrows=v;}};
}
function ready(f){for(let i=0;i<4&&f.probe.stats.builds===0;i++)f.draw();assert.equal(f.probe.stats.builds,1,JSON.stringify(f.probe.snapshot()));f.draw();assert.equal(f.probe.stats.hits,1,JSON.stringify(f.probe.snapshot()));}
let cases=0;
function run(name,fn){const f=fixture();try{fn(f);cases++;console.log('PASS '+name);}finally{f.probe.dispose();assert.equal(f.probe.stats.resources.liveTargets,0);assert.equal(f.probe.stats.resources.targetsCreated,f.probe.stats.resources.targetsDisposed);}}
if(import.meta.url===new URL(process.argv[1], 'file:').href){
globalThis.WebGL2RenderingContext=GL;
try{
 run('stable known scene builds after original frame and hits',f=>{ready(f);assert.equal(f.ground.material,f.material);assert.equal(f.renderer.target,null);assert.equal(f.renderer.autoClear,false);assert.deepEqual(f.gl.sc,[10,10,1200,700]);assert.equal(f.probe.stats.resources.peakTargets,1);});
 for(const [name,mutate]of [
 ['body transform',f=>f.bodies[0].position.x+=.1],['ancestor transform',f=>f.scene.position.x+=.1],['camera projection',f=>{f.camera.zoom=1.1;f.camera.updateProjectionMatrix();}],['light position',f=>f.light.position.x+=1],['light target world',f=>{f.light.target.position.x+=1;f.light.target.updateMatrixWorld();}],['shadow intensity',f=>f.light.shadow.intensity=.5],['shadow normal bias',f=>f.light.shadow.normalBias=.05],['shadow radius',f=>f.light.shadow.radius=2],['ground opacity',f=>f.ground.material.opacity=.2],['ground normal version',f=>f.ground.geometry.attributes.normal.needsUpdate=true],['body position version',f=>f.geometry.attributes.position.needsUpdate=true],['cast shadow',f=>f.bodies[0].castShadow=false],['body layers',f=>f.bodies[0].layers.set(2)],['light layers',f=>f.light.layers.set(2)],['body visibility',f=>f.bodies[0].visible=false],['new active identity',f=>f.r.active[0]={...f.r.active[0]}],['new roll identity',f=>f.r.active[0].roll={request:{id:'roll-2'}}],['clear alpha',f=>f.renderer.alpha=.1],['scissor',f=>f.renderer.setScissor(new T.Vector4(0,0,1200,700))],['depth texture version',f=>f.light.shadow.map.depthTexture.needsUpdate=true],['depth texture replacement',f=>f.light.shadow.map.depthTexture=new T.DepthTexture(64,64)],['shadow camera projection',f=>{f.light.shadow.camera.zoom=2;f.light.shadow.camera.updateProjectionMatrix();}],
 ])run('dependency miss: '+name,f=>{ready(f);const hits=f.probe.stats.hits;mutate(f);f.draw();assert.equal(f.probe.stats.hits,hits);assert.equal(f.ground.material,f.material);});
 for(const [name,mutate]of [
 ['unknown FX',f=>f.scene.add(new T.Mesh(new T.BoxGeometry(),new T.MeshBasicMaterial()))],['resin',f=>f.bodies[0].material.transparent=true],['custom object render',f=>f.bodies[0].onBeforeRender=()=>{}],['custom before shadow',f=>f.bodies[0].onBeforeShadow=()=>{}],['custom material compile',f=>f.bodies[0].material.onBeforeCompile=()=>{}],['custom frustum',f=>f.bodies[0].intersectsFrustum=()=>true],['custom shadow viewport',f=>f.light.shadow.getViewportCount=()=>1],['custom ground key',f=>f.ground.material.customProgramCacheKey=()=> 'x'],['ground defines',f=>f.ground.material.defines={X:1}],['ground double side',f=>f.ground.material.side=T.DoubleSide],['ground insufficient coverage',f=>f.ground.scale.x=.1],['manual world transform',f=>f.bodies[0].matrixAutoUpdate=false],['alpha map',f=>f.bodies[0].material.alphaMap=new T.Texture()],['wireframe shadow',f=>f.bodies[0].material.wireframe=true],['object bounding sphere',f=>f.bodies[0].boundingSphere=new T.Sphere(new T.Vector3(),1)],['NaN transform',f=>f.bodies[0].position.x=NaN],['infinite light intensity',f=>f.light.shadow.intensity=Infinity],['morph geometry',f=>f.geometry.morphAttributes.position=[new T.Float32BufferAttribute([0,0,0],3)]],
 ])run('unsafe source rejection: '+name,f=>{ready(f);mutate(f);f.draw();assert.equal(f.probe.stats.hits,1);assert.equal(f.probe.stats.resources.liveTargets,0);assert(f.probe.stats.records.at(-1).reason);});
 run('retimed start alone remains a hit',f=>{ready(f);f.r.active[0].start+=450;f.draw();assert.equal(f.probe.stats.hits,2);});
 run('original reference does not change cache/stats',f=>{ready(f);const snapshot=JSON.stringify(f.probe.snapshot());f.probe.withOriginal(f.draw);assert.equal(JSON.stringify(f.probe.snapshot()),snapshot);f.draw();assert.equal(f.probe.stats.hits,2);});
 run('post-render resource validation failure restores then clears and falls back',f=>{ready(f);f.hitError=true;const calls=f.calls;f.draw();assert(f.calls>=calls+2);assert.equal(f.probe.stats.fallbacks,1);assert.equal(f.ground.material,f.material);assert.equal(f.renderer.target,null);assert.equal(f.probe.stats.resources.liveTargets,0);});
 run('capture engine exception releases resources and requires recreation',f=>{f.failCapture=true;f.draw();assert.throws(f.draw,/injected capture throw/);assert.equal(f.probe.stats.requiresRendererRecreation,true);assert.equal(f.probe.stats.builds,0);assert.equal(f.ground.material,f.material);assert.equal(f.renderer.target,null);assert.equal(f.probe.stats.resources.liveTargets,0);});
 run('context lost/restored discards cache and rebuilds',f=>{ready(f);f.gl.lost=true;f.renderer.domElement.dispatchEvent(new Event('webglcontextlost'));assert.equal(f.probe.stats.resources.liveTargets,0);f.draw();assert.equal(f.probe.stats.hits,1);f.gl.lost=false;f.renderer.domElement.dispatchEvent(new Event('webglcontextrestored'));f.draw();assert.equal(f.probe.stats.hits,1);f.draw();assert.equal(f.probe.stats.builds,2);f.draw();assert.equal(f.probe.stats.hits,2);});
 run('one-shot hit restore exception invalidates and recovers baseline',f=>{ready(f);f.restoreThrows=1;f.draw();assert.equal(f.probe.stats.fallbacks,1);assert.equal(f.probe.stats.resources.liveTargets,0);assert.equal(f.ground.material,f.material);assert.equal(f.renderer.target,null);});
 run('nested engine hit aborts without reusing interrupted Three stacks',f=>{ready(f);f.nestedOnce=true;assert.throws(f.draw,/nested render/);assert.equal(f.probe.stats.requiresRendererRecreation,true);assert.equal(f.probe.stats.fallbacks,0);assert.equal(f.ground.material,f.material);assert.equal(f.renderer.target,null);assert.equal(f.probe.stats.resources.liveTargets,0);});
 run('hit engine exception restores public state but forbids retry',f=>{ready(f);f.failHit=true;assert.throws(f.draw,/injected hit throw/);assert.equal(f.probe.stats.requiresRendererRecreation,true);assert.equal(f.probe.stats.resources.liveTargets,0);assert.equal(f.ground.material,f.material);assert.throws(f.draw,/requires recreation/);});
 run('engine fatal cannot be masked by cleanup failure',f=>{ready(f);f.failHit=true;f.restoreThrows=1;const before=f.calls;assert.throws(f.draw,/injected hit throw/);assert.equal(f.calls,before+1);assert.equal(f.probe.stats.fallbacks,0);assert.equal(f.probe.stats.requiresRendererRecreation,true);});
 run('capture fatal cannot be masked by cleanup failure',f=>{f.draw();f.failCapture=true;f.restoreThrows=1;assert.throws(f.draw,/injected capture throw/);assert.equal(f.probe.stats.builds,0);assert.equal(f.probe.stats.resources.liveTargets,0);});
 run('steady hit has no probe GPU query or readback',f=>{ready(f);const init=JSON.stringify(f.probe.stats.syncCalls.init),build=JSON.stringify(f.probe.stats.syncCalls.build);for(let i=0;i<4;i++)f.draw();assert.deepEqual(f.probe.stats.syncCalls.hit,{});assert.equal(JSON.stringify(f.probe.stats.syncCalls.init),init);assert.equal(JSON.stringify(f.probe.stats.syncCalls.build),build);});
 run('mirrored clear depth mutation invalidates',f=>{ready(f);f.renderer.state.buffers.depth.setClear(.5);f.draw();assert.equal(f.probe.stats.hits,1);});
 run('hidden casters do not meet threshold',f=>{f.bodies.forEach(b=>b.visible=false);for(let i=0;i<4;i++)f.draw();assert.equal(f.probe.stats.builds,0);});
 run('geometry disposal invalidates GPU resource generation',f=>{ready(f);f.geometry.dispose();assert.equal(f.probe.stats.resources.liveTargets,0);f.draw();assert.equal(f.probe.stats.hits,1);});
 run('disabled bypass creates nothing',f=>{f.probe.setEnabled(false);for(let i=0;i<5;i++)f.draw();assert.equal(f.probe.stats.builds,0);assert.equal(f.probe.stats.resources.targetsCreated,0);});
 for(const options of [{count:1},{trusted:false}]){const f=fixture(options);for(let i=0;i<6;i++)f.draw();assert.equal(f.probe.stats.builds,0);assert.equal(f.probe.stats.hits,0);f.probe.dispose();cases++;}
 console.log(`${cases} ground-live dependency/control tests passed; mocked GL, no GPU correctness claim`);
}finally{globalThis.WebGL2RenderingContext=oldWebGL2;}
}
