import test from 'node:test';
import assert from 'node:assert/strict';
import {encodeRoll,decodeRoll,CONTACT_FLOATS} from '../extensions/workbench-dice3d/src/wire.mjs';
import {canonicalWireContacts,WIRE_CONTACT_FIELDS,compareCases} from './dice-pass-summary.mjs';
const contacts=[{t:.1,kind:0,a:1,b:0,seq:1,x:.123456789,y:-.234567891,z:.345678912,speed:1.23456789,impulse:.123456789}];
const poses=new Float32Array([0,.25,0,0,0,0,1,0,.25,0,0,0,0,1]);
// Enough real frames for the contact time; decodeRoll validates the complete header.
const frames=25,fullPoses=new Float32Array(frames*7);for(let i=0;i<frames;i++)fullPoses.set(poses.subarray(0,7),i*7);
const meta={version:2,fps:120,kinds:['d6'],frames,results:[4],duration:(frames-1)/120,collisions:contacts.length,request:{id:'fixed',source:'Host',name:'Host',theme:'ink_sketch',count:1,seed:123456,modifier:0,bodyColor:'#28b1fa',visibility:'all'}};
const decoded=await decodeRoll(await encodeRoll(meta,fullPoses,contacts));
const cue={settled:.2,firstBeam:2.2,finalReveal:2.78,finalBeamEnd:3.5,diceExit:4.5,beams:[{dieIndex:0,value:4}],total:4};
function client(index,contactValues){return{index,sdk:{results:[{data:{total:4,dice:[{type:'d6',value:4}]}}]},raw:{rolls:[{kinds:['d6'],results:[4],poseSha256:'sha256-exact',duration:meta.duration,fps:120,frames,seed:123456,contacts:structuredClone(contactValues),cue:structuredClone(cue)}]}};}
function cases(){return[{label:'single',expression:'1d6',clientCount:1,repeat:1,variant:'test',clients:[client(0,contacts)]},{label:'dual',expression:'1d6',clientCount:2,repeat:1,variant:'test',clients:[client(0,contacts),client(1,decoded.contacts)]}];}
const compare=value=>compareCases(value).invariants;
function nextFloat32(value){const view=new DataView(new ArrayBuffer(4));view.setFloat32(0,value);view.setUint32(0,view.getUint32(0)+1);return view.getFloat32(0);}
test('ten-field canonicalization is byte-codec exact using actual encodeRoll/decodeRoll',()=>{assert.equal(WIRE_CONTACT_FIELDS.length,CONTACT_FLOATS);assert.deepEqual(Object.keys(decoded.contacts[0]),WIRE_CONTACT_FIELDS);assert.notDeepEqual(decoded.contacts,contacts);assert.deepEqual(canonicalWireContacts(contacts),decoded.contacts);assert.deepEqual(decoded.poses,fullPoses);assert.deepEqual(decoded.results,meta.results);assert.equal(compare(cases()).valid,true);});
test('canonicalization rounds only ten fields and does not discard unrecognized fields',()=>{const extra={...contacts[0],future:.123456789,note:'retained'};assert.equal(canonicalWireContacts([extra])[0].future,extra.future);assert.equal(canonicalWireContacts([extra])[0].note,'retained');assert.throws(()=>canonicalWireContacts([{...extra,t:'0.1'}]),/Invalid authoritative/);const missing={...extra};delete missing.impulse;assert.throws(()=>canonicalWireContacts([missing]),/Invalid authoritative/);});
test('sender raw contacts reject drift even if it encodes to the same Float32 value',()=>{const rows=cases();rows[1].clients[0].raw.rolls[0].contacts[0].x+=1e-10;assert.equal(Math.fround(rows[1].clients[0].raw.rolls[0].contacts[0].x),Math.fround(contacts[0].x));const result=compare(rows);assert.equal(result.valid,false);assert.equal(result.mismatches[0].comparison,'sender-raw');});
test('receiver noncanonical drift is rejected even if re-rounding would hide it',()=>{const rows=cases(),contact=rows[1].clients[1].raw.rolls[0].contacts[0];contact.x+=1e-10;assert.equal(Math.fround(contact.x),decoded.contacts[0].x);const result=compare(rows);assert.equal(result.valid,false);assert.equal(result.mismatches[0].comparison,'receiver-wire-float32');});
test('one Float32 ULP and integer-field changes are rejected for every encoded contact field',()=>{for(const key of WIRE_CONTACT_FIELDS){const rows=cases(),contact=rows[1].clients[1].raw.rolls[0].contacts[0];contact[key]=nextFloat32(contact[key]);assert.equal(compare(rows).valid,false,key);}});
test('missing/extra fields and reordered or additional contacts are not ignored',()=>{for(const alter of [c=>delete c[0].impulse,c=>c[0].unexpected=1,c=>c.push({...c[0],seq:2})]){const rows=cases();alter(rows[1].clients[1].raw.rolls[0].contacts);assert.equal(compare(rows).valid,false);}const rows=cases();rows[0].clients[0].raw.rolls[0].contacts.push({...contacts[0],seq:2});rows[1].clients[0].raw.rolls[0].contacts.push({...contacts[0],seq:2});rows[1].clients[1].raw.rolls[0].contacts=[{...decoded.contacts[0],seq:2},decoded.contacts[0]];assert.equal(compare(rows).valid,false);});
test('poses, outcomes, seed, duration and complete cue values retain strict comparison',()=>{for(const alter of [c=>c.raw.rolls[0].poseSha256='different',c=>c.raw.rolls[0].results[0]=5,c=>c.sdk.results[0].data.total=5,c=>c.sdk.results[0].data.dice[0].value=5,c=>c.raw.rolls[0].seed++,c=>c.raw.rolls[0].duration+=1e-10,c=>c.raw.rolls[0].cue.finalReveal+=1e-10]){const rows=cases();alter(rows[1].clients[1]);assert.equal(compare(rows).valid,false);}});
