import test from 'node:test';
import assert from 'node:assert/strict';
import {analyzeBracket,CORE_SCENES,ORDER} from './dice-overlay-brackets-summary.mjs';
function fixture(condition,gap){
  const report={success:true,coreOnly:true,capture:{video:false,screenshots:false},realSDK:true,realPhysics:true,realOwlbearRoom:false,softwareWebGLRequested:true,deterministicParticleRollIds:true,host:{cpuModel:'same-runner',logicalCpus:4},browser:'same-chromium',viewport:{width:1280,height:800},submissionSeedsPerClient:[1,7,123456,54321,20261004,99,8,42],virtualOneWayNetworkMs:10,source:{suite:condition==='stage1'?'stage1-sha':'baseline-sha',web:'same-web'},errors:[],cases:CORE_SCENES.map((name,ordinal)=>{const rollId='fixed-'+ordinal,submittedAt=1000;return{name,rollId,submittedAt,total:4,clients:[0,1].map(index=>({index,firstSubmittedFrameMs:21,frameP50Ms:gap+index,frameP95Ms:gap+index,frameSamples:{rAF:[1020,1020+gap+index,1020+2*(gap+index)],renderSubmitted:[1021]},events:[{event:'render-release',detail:{roll:rollId+':r0',actual:1020},observedAt:1021},{event:'render-retimed',detail:{roll:rollId+':r0',start:1010}},{event:'render-complete',detail:{roll:rollId},observedAt:1020+3*(gap+index)}],result:{rollId,expression:name==='twenty-dice'?'20d6':'1d20+5',total:4,dice:[{type:'d6',value:4}],visibility:'all'}}))};})};return{condition,report};
}
const bracket=(before=450,stage=440,after=460)=>[fixture(ORDER[0],before),fixture(ORDER[1],stage),fixture(ORDER[2],after)];
test('preserves all three runs, five scenarios and both clients without averaging',()=>{const result=analyzeBracket(bracket());assert.equal(result.measurements.length,30);assert.equal(result.comparisons.length,10);assert.equal(result.stableImprovementEstablished,false);for(const scene of CORE_SCENES)assert.deepEqual(result.comparisons.filter(row=>row.scene===scene).map(row=>row.client),[0,1]);assert.equal(result.comparisons[0].stage1.completionWallMs,1320);assert.equal(result.comparisons[0].stage1.retimeCount,1);assert.equal(result.comparisons[0].baselineDrift.frameP95Ms,10);});
test('lower P95 against both baselines remains exploratory, never a stable improvement claim',()=>{const result=analyzeBracket(bracket());assert(result.comparisons.every(row=>row.p95Direction==='lower-than-both-baselines'));assert.match(result.twentyDiceDecision,/no stability claim/);assert.equal(result.stableImprovementEstablished,false);});
test('mixed and non-improving stage-one directions explicitly stop the small candidate',()=>{const mixed=analyzeBracket(bracket(430,450,470));assert(mixed.comparisons.every(row=>row.p95Direction==='mixed-against-bracketing-baselines'));assert.match(mixed.twentyDiceDecision,/Stop/);const worse=analyzeBracket(bracket(430,480,450));assert(worse.comparisons.every(row=>row.p95Direction==='not-lower-than-either-baseline'));assert.match(worse.twentyDiceDecision,/Stop/);});
test('one bad client is not hidden by averaging a faster client',()=>{const rows=bracket(),scene=rows[1].report.cases.at(-1),client=scene.clients[1];client.frameP50Ms=900;client.frameP95Ms=900;client.frameSamples.rAF=[1020,1920,2820];assert.match(analyzeBracket(rows).twentyDiceDecision,/Stop/);});
test('rejects cross-runner data, capture, altered pins and missing clients/scenarios',()=>{for(const alter of [rows=>rows[1].report.host.cpuModel='other-runner',rows=>rows[1].report.browser='other-browser',rows=>rows[1].report.capture.video=true,rows=>rows[1].report.source.web='other-web',rows=>rows[1].report.cases.pop(),rows=>rows[1].report.cases[0].clients.pop(),rows=>rows.reverse()]){const rows=bracket();alter(rows);assert.throws(()=>analyzeBracket(rows));}});
test('rejects changed outcomes, IDs, completion and reported metrics inconsistent with raw samples',()=>{for(const alter of [rows=>rows[1].report.cases[0].clients[0].result.total=5,rows=>rows[1].report.cases[0].rollId='different',rows=>rows[1].report.cases[0].clients[0].events.pop(),rows=>rows[1].report.cases[0].clients[0].frameP95Ms=1,rows=>rows[1].report.cases[0].clients[0].firstSubmittedFrameMs=0]){const rows=bracket();alter(rows);assert.throws(()=>analyzeBracket(rows));}});
