import assert from 'node:assert/strict';
import {Controller} from '../extensions/workbench-dice3d/src/controller';
import {diceCatalog} from '../extensions/workbench-dice3d/src/asset-catalog';
import {BUILD,now} from '../extensions/workbench-dice3d/src/types';
import {encodeRoll,hash,split,Assembly,sizeOf,MAX_MESSAGE_BYTES} from '../extensions/workbench-dice3d/src/wire.mjs';
const tests:any[]=[];const check=async(name:string,fn:()=>any)=>{try{await fn();tests.push({name,passed:true})}catch(e){tests.push({name,passed:false,error:String(e)})}};
function host(){const h:any=Object.create(Controller.prototype),sent:any[]=[],local:any[]=[],worker:any[]=[],errors:any[]=[];
 Object.assign(h,{transport:{id:'host',name:'Host',role:'GM'},catalog:diceCatalog(),ready:true,disabled:false,born:0,peers:new Map([['peer',{id:'peer',session:'12345678-1234-1234-1234-123456789012',name:'Peer',role:'PLAYER',ready:true,born:1,lastSeen:now(),rtt:20,offset:0,version:BUILD,inlineRollV1:true}]]),inbound:new Map(),outgoing:new Map(),rolls:new Map(),queue:[],requests:new Map(),accepted:new Map(),retainedUntil:new Map(),settledAt:new Map(),heldRolls:new Map(),reservations:new Map(),privateRunning:new Set(),privateAudiences:new Map(),secrets:new Map(),records:new Map(),probes:new Map(),clocks:new Map(),started:new Map(),events:[],lastState:now(),lastPresence:now(),bytesReceived:0,packetsReceived:0,bytesSent:0,packetsSent:0,viewport:{w:390,h:844},keys:{forget:()=>{},remember:async()=>{},ready:Promise.resolve(),publicKey:'synthetic'},worker:{postMessage:(p:any)=>worker.push(p)},bus:{postMessage:(p:any)=>local.push(p)},state:()=>{},sendRecords:()=>{},log:()=>{},fail:(...e:any[])=>errors.push(e),next:()=>{},addRecord:()=>{},retainUntilExit:()=>{},send:async(p:any,stamp?:(q:any)=>void)=>{stamp?.(p);sent.push(structuredClone(p));},ping:async()=>{}});return {h,sent,local,worker,errors};}
function roll(count=1,frames=30){const request:any={id:'r',source:'host',authority:'host',name:'Host',kind:'d6',count,theme:'ink_sketch',seed:1,modifier:0,visibility:'all'};return{version:2,request,kinds:Array(count).fill('d6'),results:Array(count).fill(3),fps:120,frames,poses:new Float32Array(frames*count*7),contacts:[],physicsMs:1,steps:frames*2,collisions:0,duration:(frames-1)/120};}
async function produce(options:any={}){const fixture=host(),{h,sent,local}=fixture,r=roll(options.count??1,options.frames??30);options.alterRoll?.(r);options.alter?.(h);h.pending=r.request;
 h.bus.postMessage=(p:any)=>{local.push(p);if(p.type==='prepare')void h.onLocal({type:'prepared',id:p.roll.request.id});};
 h.send=async(p:any,stamp?:(q:any)=>void)=>{stamp?.(p);sent.push(structuredClone(p));if(p.type==='offer'){const out=h.outgoing.get(p.id);for(const member of out?.members||[])out.wait.delete(member);await options.duringOffer?.(h,p);}};
 await h.onWorker({id:r.request.id,roll:r});return{...fixture,r};}
await check('one complete small trace uses one negotiated offer and no data/trailer slots',async()=>{const{sent,local,errors}=await produce();const offer=sent.find(p=>p.type==='offer');assert.equal(typeof offer.inlineChunk,'string');assert.equal(sent.filter(p=>['chunk','chunks-done'].includes(p.type)).length,0);assert.equal(local.filter(p=>p.type==='start').length,1);assert.deepEqual(errors,[]);});
await check('nine one-chunk dice eligible but ten stays on legacy boundary',async()=>{const a=await produce({count:9}),b=await produce({count:10});assert(a.sent.find(p=>p.type==='offer').inlineChunk);assert.equal(b.sent.find(p=>p.type==='offer').inlineChunk,undefined);assert(b.sent.some(p=>p.type==='chunk'));assert(b.sent.some(p=>p.type==='chunks-done'));});
await check('one unknown/old recipient keeps the whole audience on legacy',async()=>{for(const flag of [undefined,false,'true',1]){const{sent}=await produce({alter:(h:any)=>h.peers.get('peer').inlineRollV1=flag});assert.equal(sent.find(p=>p.type==='offer').inlineChunk,undefined);assert(sent.some(p=>p.type==='chunk'));assert(sent.some(p=>p.type==='chunks-done'));}});
await check('multi-chunk trace uses existing chunk and tail recovery path',async()=>{const{sent}=await produce({frames:300,alterRoll:(r:any)=>{let seed=7;for(let i=0;i<r.poses.length;i++){seed=(1664525*seed+1013904223)>>>0;r.poses[i]=seed/2**32;}}});const offer=sent.find(p=>p.type==='offer');assert(offer.total>1);assert.equal(offer.inlineChunk,undefined);assert.equal(sent.filter(p=>p.type==='chunk').length,offer.total);assert(sent.some(p=>p.type==='chunks-done'));});
await check('a grouped child retains original group transport',async()=>{const{sent}=await produce({alterRoll:(r:any)=>r.request.batch={id:'g',index:0,size:1}});assert.equal(sent.find(p=>p.type==='offer').inlineChunk,undefined);assert(sent.some(p=>p.type==='chunks-done'));});
await check('oversized inline envelope falls back rather than exceeding packet budget',async()=>{const{sent}=await produce({alter:(h:any)=>{h.peers.clear();for(let i=0;i<64;i++){const id=String(i)+'x'.repeat(185);h.peers.set(id,{id,ready:true,lastSeen:now(),rtt:20,version:BUILD,inlineRollV1:true});}},frames:220,alterRoll:(r:any)=>{for(let i=0;i<r.poses.length;i++)r.poses[i]=Math.sin(i)*.03;}});const offer=sent.find(p=>p.type==='offer');assert.equal(offer.total,1);assert.equal(offer.inlineChunk,undefined);assert(sizeOf({...offer,v:1,build:BUILD,from:'host'})<MAX_MESSAGE_BYTES);});
await check('targeted retry size is checked even when broadcast envelope fits',async()=>{
 const r:any=roll(1,250);let seed=7;for(let i=0;i<r.poses.length;i++){seed=(Math.imul(1664525,seed)+1013904223)>>>0;r.poses[i]=seed/2**32;}
 const{poses,contacts,...meta}=r,bytes=await encodeRoll({...meta,contacts:0},poses,contacts),chunks=split(bytes);assert.equal(chunks.length,1);
 let members:string[]|undefined;
 for(let count=1;count<=64&&!members;count++)for(let length=20;length<=100;length++){const ids=Array.from({length:count},(_,i)=>String(i).padStart(2,'0')+'x'.repeat(length-2));const p={v:1,build:BUILD,from:'host',type:'offer',id:'r',total:1,bytes:bytes.length,hash:await hash(bytes),members:ids,inlineChunk:chunks[0]};if(sizeOf(p)<=MAX_MESSAGE_BYTES&&sizeOf({...p,to:ids[0]})>MAX_MESSAGE_BYTES){members=ids;break;}}
 assert(members,'construct a valid retry-only boundary');const{sent}=await produce({frames:250,alterRoll:(r:any)=>r.poses.set(poses),alter:(h:any)=>{h.peers.clear();for(const id of members!)h.peers.set(id,{id,ready:true,lastSeen:now(),rtt:20,version:BUILD,inlineRollV1:true});}});assert.equal(sent.find(p=>p.type==='offer').inlineChunk,undefined);
});
await check('unprepared local renderer cannot be bypassed by an inline ready peer',async()=>{const{h,sent,local}=host(),r=roll();h.pending=r.request;h.send=async(p:any,stamp?:(q:any)=>void)=>{stamp?.(p);sent.push(p);if(p.type==='offer')h.outgoing.get(p.id).wait.delete('peer');};await h.onWorker({id:'r',roll:r});assert(h.outgoing.get('r').wait.has('host'));assert(!local.some(p=>p.type==='start'));await h.onLocal({type:'prepared',id:'r'});assert.equal(local.filter(p=>p.type==='start').length,1);});
await check('capability is strict and reset by a same-session legacy hello',async()=>{const{h}=host();for(const inlineRollV1 of [true,undefined,'true',false]){await h.receive({v:1,build:BUILD,from:'peer',type:'hello',session:'12345678-1234-1234-1234-123456789012',name:'Peer',role:'PLAYER',ready:true,born:1,inlineRollV1},'peer');assert.equal(h.peers.get('peer').inlineRollV1,inlineRollV1===true);}});
await check('authenticated peer restart during offer ACK cannot resurrect discarded roll',async()=>{const{sent,local,h}=await produce({duringOffer:async(h:any)=>{await h.receive({v:1,build:BUILD,from:'peer',type:'hello',session:'87654321-4321-4321-4321-210987654321',name:'Peer',role:'PLAYER',ready:true,born:1,inlineRollV1:true},'peer');}});assert.equal(h.outgoing.size,0);assert(local.some(p=>p.type==='discard'));assert.equal(sent.filter(p=>p.type==='start').length,0);assert.equal(local.filter(p=>p.type==='start').length,0);});
await check('failed combined offer acknowledgement cannot start a ready-but-unconfirmed roll',async()=>{const{sent,local,errors}=await produce({duringOffer:async()=>{throw Error('ACK unavailable');}});assert.equal(sent.filter(p=>p.type==='start').length,0);assert.equal(local.filter(p=>p.type==='start').length,0);assert(errors.length);});
await check('restart aborts all remaining public children of an in-flight group',async()=>{const{h,sent,local}=host(),r:any=roll(2,2);r.request={...r.request,id:'g',recipe:true,groupSize:2,visibility:'gm'};
 r.formulaData={ids:['da','db'],births:[0,0],contexts:[{visibility:'all',rollerId:'host',itemId:null,label:'one'},{visibility:'all',rollerId:'host',itemId:null,label:'two'}],rows:[{formula:'1d6',dice:[{id:'da',value:3}],total:3},{formula:'1d6',dice:[{id:'db',value:3}],total:3}],timeline:{births:[0,0],clamps:[],decisionAt:0},expression:'1d6;1d6'};
 h.pending=r.request;h.reservations.set('g',{request:r.request,broker:'host',members:['host','peer'],at:now()});h.bus.postMessage=(p:any)=>{local.push(p);if(p.type==='prepare')void h.onLocal({type:'prepared',id:p.roll.request.id});};
 h.send=async(p:any,stamp?:(q:any)=>void)=>{stamp?.(p);sent.push(p);if(p.type==='offer'&&p.id==='g.g0'){const out=h.outgoing.get(p.id);out.wait.delete('peer');await h.receive({v:1,build:BUILD,from:'peer',type:'hello',session:'87654321-4321-4321-4321-210987654321',name:'Peer',role:'PLAYER',ready:true,born:1,inlineRollV1:true},'peer');}};
 await h.onWorker({id:'g',roll:r});assert.equal(h.outgoing.size,0);assert.equal(h.reservations.size,0);assert(!local.some(p=>p.type==='start'||p.type==='prepare'&&p.roll.request.id==='g.g1'));assert(!sent.some(p=>p.type==='offer'&&p.id==='g.g1'));});
async function packet(r=roll()){const{poses,contacts,...meta}=r,b=await encodeRoll({...meta,contacts:contacts.length},poses,contacts);const chunks=split(b);assert.equal(chunks.length,1);return {v:1,build:BUILD,from:'host',type:'offer',id:r.request.id,total:1,bytes:b.length,hash:await hash(b),members:['peer'],inlineChunk:chunks[0]};}
function receiver(){const f=host();f.h.transport.id='peer';f.h.peers=new Map([['host',{id:'host',name:'Host',ready:true,born:0,lastSeen:now(),rtt:20,offset:0,version:BUILD}]]);f.h.born=1;return f;}
await check('inline receive validates exact trace and records one network envelope',async()=>{const{h,local}=receiver(),p=await packet();await h.receive(p,'host');assert.equal(h.packetsReceived,1);assert.equal(h.bytesReceived,sizeOf(p));assert.deepEqual(h.rolls.get('r').results,[3]);assert.equal(local.filter(p=>p.type==='prepare').length,1);assert(!local.some(p=>p.type==='start'));});
await check('repeated inline offer and late old chunk do not prepare twice',async()=>{const{h,local}=receiver(),p=await packet();await h.receive(p,'host');await h.receive(p,'host');await h.receive({v:1,build:BUILD,from:'host',type:'chunk',id:'r',index:0,data:p.inlineChunk},'host');assert.equal(local.filter(p=>p.type==='prepare').length,1);});
await check('inline retry fills a previously received plain manifest',async()=>{const{h,local}=receiver(),p=await packet(),{inlineChunk,...plain}=p;await h.receive(plain,'host');assert.equal(local.length,0);await h.receive(p,'host');assert.equal(local.filter(p=>p.type==='prepare').length,1);});
await check('malformed inline data is rejected before retaining its manifest',async()=>{for(const extra of [{inlineChunk:123},{total:2},{inlineChunk:'AA=='},{bytes:0}]){const{h,local}=receiver(),p={...await packet(),...extra};await assert.rejects(h.receive(p,'host'));assert.equal(h.inbound.size,0);assert.equal(local.length,0);}});
await check('wrong SHA and source/manifest mismatch never prepare or start',async()=>{const{h,local}=receiver(),p=await packet();await assert.rejects(h.receive({...p,hash:'0'.repeat(64)},'host'),/SHA/);assert.equal(local.length,0);const f=receiver();await assert.rejects(f.h.receive({...p,from:'outsider'},'outsider'),/权威/);assert.equal(f.local.length,0);});
await check('conflicting duplicate inline bytes are rejected without replacing good roll',async()=>{const{h,local}=receiver(),p=await packet();await h.receive(p,'host');const altered=Buffer.from(p.inlineChunk,'base64');altered[altered.length-1]^=1;await assert.rejects(h.receive({...p,inlineChunk:altered.toString('base64')},'host'),/Conflicting/);assert.deepEqual(h.rolls.get('r').results,[3]);assert.equal(local.filter(p=>p.type==='prepare').length,1);});
await check('inline cannot make a forbidden private result public',async()=>{const r=roll();r.request.visibility='self';const{h,local}=receiver();await assert.rejects(h.receive(await packet(r),'host'),/权威\/结果/);assert.equal(local.length,0);});
await check('both targeted preparation and late-start retries retain the complete inline payload',async()=>{const{h,sent}=await produce();const out=h.outgoing.get('r');assert(out.inlineOffer);out.started=false;out.start=undefined;out.wait=new Set(['peer']);out.roll.request.source='peer';out.at=now()-3000;out.retry=0;sent.length=0;await h.tick();let offers=sent.filter(p=>p.type==='offer');assert(offers.length);assert(offers.every(p=>p.to==='peer'&&p.inlineChunk===out.chunks[0]));out.started=true;out.start=now();out.lastStartRetry=now()-2000;out.acks=new Set(['peer']);sent.length=0;await h.tick();offers=sent.filter(p=>p.type==='offer');assert(offers.length);assert(offers.every(p=>p.inlineChunk===out.chunks[0]));});
function noisyRoll(){const r=roll(9,90);let seed=91;for(let i=0;i<r.poses.length;i++){seed=(Math.imul(1664525,seed)+1013904223)>>>0;r.poses[i]=seed/2**32;}return r;}
async function fragments(r=noisyRoll()){const{poses,contacts,...meta}=r,bytes=await encodeRoll({...meta,contacts:0},poses,contacts),chunks=split(bytes);assert(chunks.length>1);return {chunks,p:{v:1,build:BUILD,from:'host',type:'offer',id:'r',total:chunks.length,bytes:bytes.length,hash:await hash(bytes),members:['peer'],inlineChunk:chunks[0]}};}
await check('negotiated multi-chunk small trace embeds only first fragment and keeps tail hint',async()=>{const r=noisyRoll(),{sent}=await produce({count:9,frames:r.frames,alterRoll:(p:any)=>p.poses.set(r.poses),alter:(h:any)=>h.peers.get('peer').inlineChunkV1=true});const offer=sent.find(p=>p.type==='offer');assert(offer.total>1);assert(offer.inlineChunk);assert.deepEqual(sent.filter(p=>p.type==='chunk').map(p=>p.index),Array.from({length:offer.total-1},(_,i)=>i+1));assert.equal(sent.filter(p=>p.type==='chunks-done').length,1);});
await check('single-chunk capability never authorizes multi-chunk piggyback',async()=>{for(const flag of [undefined,false,'true',1]){const r=noisyRoll(),{sent}=await produce({count:9,frames:r.frames,alterRoll:(p:any)=>p.poses.set(r.poses),alter:(h:any)=>h.peers.get('peer').inlineChunkV1=flag});const offer=sent.find(p=>p.type==='offer');assert.equal(offer.inlineChunk,undefined);assert.equal(sent.filter(p=>p.type==='chunk').length,offer.total);}});
await check('one incapable member makes multi-fragment offer legacy for everyone',async()=>{const r=noisyRoll(),{sent}=await produce({count:9,frames:r.frames,alterRoll:(p:any)=>p.poses.set(r.poses),alter:(h:any)=>{h.peers.get('peer').inlineChunkV1=true;h.peers.set('older',{...h.peers.get('peer'),id:'older',inlineChunkV1:false});}});assert.equal(sent.find(p=>p.type==='offer').inlineChunk,undefined);});
await check('ten physical dice retain legacy even with multi-chunk capability',async()=>{const{sent}=await produce({count:10,alter:(h:any)=>h.peers.get('peer').inlineChunkV1=true});assert.equal(sent.find(p=>p.type==='offer').inlineChunk,undefined);});
await check('first inline fragment never prepares before all verified remaining fragments',async()=>{const{h,local}=receiver(),{p,chunks}=await fragments();await h.receive(p,'host');assert.equal(local.filter(p=>p.type==='prepare').length,0);for(let i=chunks.length-1;i>=1;i--)await h.receive({v:1,build:BUILD,from:'host',type:'chunk',id:'r',index:i,data:chunks[i]},'host');assert.equal(local.filter(p=>p.type==='prepare').length,1);assert.deepEqual(h.rolls.get('r').results,Array(9).fill(3));});
await check('duplicate inline retry does not postpone missing-fragment repair deadline',async()=>{const{h,sent}=receiver(),{p,chunks}=await fragments();await h.receive(p,'host');const inbound=h.inbound.get('r');inbound.at=now()-3100;const prior=inbound.at;await h.receive(p,'host');assert.equal(inbound.at,prior);await h.tick();const missing=sent.find(p=>p.type==='missing');assert(missing);assert.deepEqual(missing.indices,Array.from({length:chunks.length-1},(_,i)=>i+1));});
await check('genuinely new fragment advances progress while same data duplicate does not',async()=>{const{h}=receiver(),{p,chunks}=await fragments();await h.receive(p,'host');const inbound=h.inbound.get('r');inbound.at=now()-3100;const wire={v:1,build:BUILD,from:'host',type:'chunk',id:'r',index:1,data:chunks[1]};await h.receive(wire,'host');assert(inbound.at>now()-100);const fresh=inbound.at;await h.receive(wire,'host');assert.equal(inbound.at,fresh);});
await check('lost tail plus trailer is repaired after repeated first-fragment offers',async()=>{const{h,sent,local}=receiver(),{p,chunks}=await fragments();await h.receive(p,'host');for(let i=1;i<chunks.length-1;i++)await h.receive({v:1,build:BUILD,from:'host',type:'chunk',id:'r',index:i,data:chunks[i]},'host');const inbound=h.inbound.get('r');inbound.at=now()-3100;for(let i=0;i<4;i++)await h.receive(p,'host');await h.tick();const missing=sent.find(p=>p.type==='missing');assert.deepEqual(missing.indices,[chunks.length-1]);await h.receive({v:1,build:BUILD,from:'host',type:'chunk',id:'r',index:chunks.length-1,data:chunks.at(-1)},'host');assert.equal(local.filter(p=>p.type==='prepare').length,1);});
await check('tail before lost manifest remains unprepared until retry plus missing-fragment repair',async()=>{const{h,sent,local}=receiver(),{p,chunks}=await fragments();for(let i=1;i<chunks.length;i++)await h.receive({v:1,build:BUILD,from:'host',type:'chunk',id:'r',index:i,data:chunks[i]},'host');assert.equal(h.inbound.size,0);await h.receive(p,'host');assert.equal(local.length,0);h.inbound.get('r').at=now()-3100;await h.tick();const missing=sent.find(p=>p.type==='missing');assert.deepEqual(missing.indices,Array.from({length:chunks.length-1},(_,i)=>i+1));for(const i of missing.indices)await h.receive({v:1,build:BUILD,from:'host',type:'chunk',id:'r',index:i,data:chunks[i]},'host');assert.equal(local.filter(p=>p.type==='prepare').length,1);});
const report={checks:tests.length,passed:tests.filter(t=>t.passed).length,failed:tests.filter(t=>!t.passed).length,boundary:'Production Controller/codec; in-memory transport and renderer acknowledgement, not browser or phone latency.',tests};console.log(JSON.stringify(report,null,2));if(report.failed)process.exitCode=1;
