import {Assembly} from '../extensions/workbench-dice3d/src/wire.mjs';
import {diceCatalog} from '../extensions/workbench-dice3d/src/asset-catalog';
import assert from 'node:assert/strict';
import {writeFileSync,mkdirSync} from 'node:fs';
import {join} from 'node:path';
const evidence=process.env.DND_DICE_EVIDENCE||'.cache/dice-clock-latency';mkdirSync(evidence,{recursive:true});
import {Controller} from '../extensions/workbench-dice3d/src/controller';
import {DiceSendQueue} from '../src/workbench/dice-send-queue';
import {sendDiceMessage} from '../src/workbench/dice-broadcast';
import {BUILD,now} from '../extensions/workbench-dice3d/src/types';
const tests:any[]=[];const check=async(name:string,fn:()=>any)=>{if(process.env.DICE_CLOCK_CASE&&!name.includes(process.env.DICE_CLOCK_CASE))return;try{await fn();tests.push({name,passed:true});}catch(e){tests.push({name,passed:false,error:String(e)});}};
const host=()=>{const h:any=Object.create(Controller.prototype);Object.assign(h,{transport:{id:'a',name:'a',send:async()=>{}},peers:new Map([['b',{id:'b',ready:true,lastSeen:now(),rtt:-1,offset:0}]]),probes:new Map(),clocks:new Map(),inbound:new Map(),bytesReceived:0,packetsReceived:0,bytesSent:0,packetsSent:0,log:()=>{}});return h;};
const pong=async(fields:any,probeT=1000,end=2620)=>{const h=host();h.probes.set('nonce',{to:'b',t:probeT});const saved=globalThis.performance;Object.defineProperty(globalThis,'performance',{value:{timeOrigin:0,now:()=>end},configurable:true});try{await h.receive({v:1,build:BUILD,from:'b',type:'pong',nonce:'nonce',...fields},'b',end);}finally{Object.defineProperty(globalThis,'performance',{value:saved,configurable:true});}return h;};
await check('four timestamps subtract 1600 ms peer queue and preserve 5000 ms offset',async()=>{const h=await pong({received:6010,remote:7610});assert.equal(h.peers.get('b').rtt,20);assert.equal(h.peers.get('b').offset,5000);});
await check('legacy pong without receive timestamp keeps prior three-time estimate',async()=>{const h=await pong({remote:6010},1000,1020);assert.equal(h.peers.get('b').rtt,20);assert.equal(h.peers.get('b').offset,5000);});
for(const [name,fields]of Object.entries({nan:{received:NaN,remote:7600},futureReceive:{received:8000,remote:7600},tooMuchProcessing:{received:6000,remote:9000},nullReceive:{received:null,remote:7600},infiniteRemote:{received:6000,remote:Infinity}}))await check('reject malformed timestamp: '+name,async()=>{const h=await pong(fields);assert.equal(h.peers.get('b').rtt,-1);assert.equal(h.clocks.size,0);});
await check('wrong connection cannot consume or update matching nonce',async()=>{const h=host();h.peers.set('c',{rtt:-1,offset:0});h.probes.set('nonce',{to:'b',t:1000});await h.receive({v:1,build:BUILD,from:'c',type:'pong',nonce:'nonce',received:6010,remote:7610},'c',2620);assert.equal(h.peers.get('b').rtt,-1);assert(h.probes.has('nonce'));});
await check('matching nonce alone cannot accept sample older than probe budget',async()=>{const h=await pong({received:6010,remote:7610},1000,20000);assert.equal(h.peers.get('b').rtt,-1);});
await check('fresh clock avoids a per-roll ping',async()=>{const h=host();h.clocks.set('b',[{at:now(),rtt:20,offset:0}]);let sends=0;h.send=async()=>sends++;await h.ping('b');assert.equal(sends,0);});
await check('stale clock re-probes and stamps after transport dispatch delay',async()=>{const h=host();h.clocks.set('b',[{at:now()-5000,rtt:20,offset:0}]);let finish:any,packet:any;h.transport.sendTimed=(p:any,stamp:()=>void)=>new Promise<void>(r=>{finish=()=>{stamp();packet=p;r();};});const task=h.ping('b');const probe=[...h.probes.values()][0] as any,initial=probe.t;await new Promise(r=>setTimeout(r,25));finish();await task;assert(probe.t-initial>=20);assert.equal(packet.t,probe.t);});
await check('nonqueued transport fallback stamps before send',async()=>{const h=host();let packet:any;h.transport.send=async(p:any)=>{packet=p;};await h.ping('b');const probe=[...h.probes.values()][0] as any;assert.equal(packet.t,probe.t);assert(h.bytesSent>0);});
await check('pong keeps ingress time while stamp marks delayed dispatch',async()=>{const h=host();let finish:any,packet:any;h.transport.sendTimed=(p:any,stamp:()=>void)=>new Promise<void>(r=>{finish=()=>{stamp();packet=p;r();};});const arrived=now();const task=h.receive({v:1,build:BUILD,from:'b',type:'ping',nonce:'n'},'b',arrived);await new Promise(r=>setTimeout(r,25));finish();await task;assert.equal(packet.received,arrived);assert(packet.remote-arrived>=20);});
for(const grouped of [false,true])await check((grouped?'group':'single')+' start anchors to paced dispatch and preserves settled predecessor',async()=>{
 const h=host(),q=new DiceSendQueue();h.outgoing=new Map();h.settledAt=new Map();const sent:any[]=[],retained:any[]=[],local:any[]=[];let unblock:any;
 Object.assign(h,{bus:{postMessage:(p:any)=>local.push(p)},retainUntilExit:(roll:any,start:number)=>retained.push({id:roll.request.id,start}),finishReservation:()=>{},next:()=>{}});
 h.peers.get('b').rtt=20;
 const held=q.send(()=>new Promise<void>(r=>{unblock=r;}));
 const transmit=(p:any,stamp?:()=>void)=>q.send(async()=>{stamp?.();sent.push({p:{...p},at:now()});},()=>true,'control');h.transport.send=transmit;h.transport.sendTimed=transmit;
 const ids=grouped?['g0','g1']:['s'];for(const [index,id]of ids.entries())h.outgoing.set(id,{uploading:false,started:false,roll:{request:{id,source:'a',...(grouped?{batch:{id:'g',index,size:2}}:{})}},wait:new Set(),members:['b'],at:now(),hash:'a'.repeat(64)});
 const task=h.maybeStart(h.outgoing.get(ids[0]));await new Promise(r=>setTimeout(r,160));const predecessor=now()+140;h.settledAt.set('old',predecessor);unblock();await held;await task;
 const start=sent[0];assert(start.p.start-start.at>=(grouped?98:68),JSON.stringify(start));assert(start.p.start>=predecessor);assert(retained.every(row=>row.start===start.p.start));assert(local.every(row=>row.at===start.p.start));assert(ids.every(id=>h.outgoing.get(id).start===start.p.start));
});
await check('normal sends retain exact 100 ms budget with deterministic clock',async()=>{
 let time=0;const sleeps:number[]=[],starts:number[]=[];const q=new DiceSendQueue(100,()=>time,async ms=>{sleeps.push(ms);time+=ms;});
 await Promise.all(Array.from({length:4},()=>q.send(async()=>{starts.push(time);})));
 assert.deepEqual(starts,[0,100,200,300]);assert.deepEqual(sleeps,[100,100,100]);
});
await check('Suite broadcast stamps the exact packet before its SDK operation',async()=>{
 (globalThis as any).__diceSdkSent=[];const packet:any={type:'ping'};let stamps=0;
 await sendDiceMessage('probe',{type:'hello'},{destination:'REMOTE'});
 await (sendDiceMessage as any)('probe',packet,{destination:'REMOTE'},()=>true,()=>{packet.dispatchStamp=++stamps;});
 const sent=(globalThis as any).__diceSdkSent;assert.equal(sent.length,2);assert.equal(stamps,1);assert.equal(sent[1].data.dispatchStamp,1);assert.equal(sent[0].data.dispatchStamp,undefined);
});
const startHost=()=>{const h=host(),out={uploading:false,started:false,roll:{request:{id:'s',source:'a'}},wait:new Set(),members:['b'],at:now(),hash:'a'.repeat(64),acks:new Set(['b'])},local:any[]=[],retained:any[]=[],logs:any[]=[];Object.assign(h,{outgoing:new Map([['s',out]]),settledAt:new Map(),bus:{postMessage:(p:any)=>local.push(p)},retainUntilExit:(roll:any,start:number)=>retained.push(start),finishReservation:()=>{},next:()=>{},log:(event:string,detail:any)=>logs.push({event,...detail})});h.peers.get('b').rtt=20;return {h,out,local,retained,logs};};
await check('slow SDK ACK never gates first local animation',async()=>{const {h,out,local}=startHost();let finish:any;h.transport.sendTimed=async(p:any,stamp:()=>void)=>{stamp();await new Promise<void>(r=>{finish=r;});};const task=h.maybeStart(out);await new Promise(r=>setTimeout(r,120));assert.equal(local.length,1);assert(local[0].at<now());assert.equal((out as any).dispatching,false,'once armed, SDK ACK must not block next-roll prediction');finish();await task;assert.equal((out as any).dispatching,false);assert.equal(local.length,1);});
await check('unknown outcome after dispatch retains one start for bounded idempotent recovery',async()=>{const {h,out,local,retained,logs}=startHost();h.transport.sendTimed=async(p:any,stamp:()=>void)=>{stamp();throw Error('SDK ACK timed out, outcome unknown');};await h.maybeStart(out);assert.equal(local.length,1);assert.equal(retained.length,1);assert.equal((out as any).dispatching,false);assert.equal(out.started,true);assert(Number.isFinite((out as any).start));assert(logs.some(l=>l.event==='start-send-unconfirmed'));});
await check('failure before dispatch rolls back start lock without nonfinite state',async()=>{const {h,out,local}=startHost();h.transport.sendTimed=async()=>{throw Error('disposed before dispatch');};await assert.rejects(h.maybeStart(out),/disposed/);assert.equal(local.length,0);assert.equal(out.started,false);assert.equal((out as any).dispatching,false);assert.equal((out as any).start,undefined);assert.equal((out as any).lastStartRetry,0);});
await check('explicit rate-limit retries keep the same time and arm only once',async()=>{const {h,out,local,retained}=startHost();let t=0;const q=new DiceSendQueue(100,()=>t,async ms=>{t+=ms;}),attempts:any[]=[];h.transport.sendTimed=(p:any,stamp:()=>void)=>q.send(async()=>{stamp();attempts.push({start:p.start,id:p.id,hash:p.hash,time:t});if(attempts.length<3)throw {error:{name:'RateLimitHit'}};},()=>true,'control');await h.maybeStart(out);assert.equal(attempts.length,3);assert.deepEqual(attempts.map(x=>x.time),[0,800,2400]);assert.equal(new Set(attempts.map(x=>x.start)).size,1);assert.equal(new Set(attempts.map(x=>x.hash)).size,1);assert.equal(local.length,1);assert.equal(retained.length,1);assert.equal((out as any).dispatching,false);});
await check('exhausted explicit rate-limit budget retains finite start for peer catch-up',async()=>{const {h,out,local}=startHost();let t=0,count=0;const q=new DiceSendQueue(100,()=>t,async ms=>{t+=ms;});h.transport.sendTimed=(p:any,stamp:()=>void)=>q.send(async()=>{stamp();count++;throw {error:{name:'RateLimitHit'}};},()=>true,'control');await h.maybeStart(out);assert.equal(count,4);assert.equal(t,5600);assert.equal(local.length,1);assert(Number.isFinite((out as any).start));assert.equal((out as any).dispatching,false);});
{
const host=()=>{const h:any=Object.create(Controller.prototype),local:any[]=[],sent:any[]=[],worker:any[]=[],fails:any[]=[],logs:any[]=[];
 Object.assign(h,{transport:{id:'a',name:'a',role:'GM',send:async(p:any)=>sent.push({...p}),sendTimed:async(p:any,stamp:()=>void)=>{stamp();sent.push({...p});}},catalog:diceCatalog(),peers:new Map([['b',{id:'b',ready:true,lastSeen:now(),rtt:20,offset:5000,version:BUILD,born:1}]]),ready:true,disabled:false,wasAuthority:true,born:0,probes:new Map(),clocks:new Map(),started:new Map(),bytesReceived:0,packetsReceived:0,bytesSent:0,packetsSent:0,queue:[],inbound:new Map(),outgoing:new Map(),rolls:new Map(),requests:new Map(),accepted:new Map(),retainedUntil:new Map(),settledAt:new Map(),heldRolls:new Map(),reservations:new Map(),privateRunning:new Set(),privateAudiences:new Map(),secrets:new Map(),records:new Map(),events:[],lastState:now(),lastPresence:now(),viewport:{w:1920,h:1080},keys:{forget:()=>{}},worker:{postMessage:(p:any)=>worker.push(p)},bus:{postMessage:(p:any)=>local.push(p)},state:()=>{},sendRecords:()=>{},log:(event:string,detail:any)=>logs.push({event,...detail}),fail:(...e:any[])=>fails.push(e),addRecord:()=>{},retainUntilExit:(r:any,t:number)=>{h.heldRolls.set(r.request.id,r);h.settledAt.set(r.request.id,t+r.duration*1000);}});
 return {h,local,sent,worker,fails,logs};};
const out=(id='s',batch?:any)=>({uploading:false,started:false,roll:{request:{id,source:'a',theme:'ink_sketch',...(batch?{batch}:{})},kinds:['d20'],duration:0.1},wait:new Set(),members:['b'],at:now(),hash:'a'.repeat(64),acks:new Set(['b']),viewers:new Set(['a','b']),lastStartRetry:0,window:20000,retry:0,chunks:['a'],bytes:1});
await check('queued dispatch prevents next prediction until first arm and scheduled release',async()=>{
 const {h,worker}=host(),row=out();h.outgoing.set('s',row);h.queue=[{id:'next',source:'a',kind:'d20',count:1,theme:'ink_sketch'}];let fire:any,resolve:any;
 h.transport.sendTimed=(p:any,stamp:()=>void)=>new Promise<void>(r=>{fire=stamp;resolve=r;});const task=h.maybeStart(row);h.next();assert(!worker.some(p=>p.request));fire();h.next();assert(!worker.some(p=>p.request));await new Promise(r=>setTimeout(r,100));h.next();assert.equal(worker.filter(p=>p.request).length,1,'prediction must start while SDK ACK is pending');resolve();await task;clearTimeout(h.pendingTimer);
});
await check('slow ACK cannot let tick send an undefined start before initial dispatch',async()=>{
 const {h,sent}=host(),row=out();h.outgoing.set('s',row);let fire:any,resolve:any;h.transport.sendTimed=(p:any,stamp:()=>void)=>new Promise<void>(r=>{fire=stamp;resolve=r;});const task=h.maybeStart(row);await h.tick();assert.equal(sent.length,0);assert.equal((row as any).start,undefined);fire();assert(Number.isFinite((row as any).start));resolve();await task;
});
await check('failed group SDK ACK arms all child tracks exactly once',async()=>{
 const {h,local,fails}=host(),rows=[out('g.g0',{id:'g',index:0,size:2}),out('g.g1',{id:'g',index:1,size:2})];for(const row of rows)h.outgoing.set(row.roll.request.id,row);
 let attempt=0;h.transport.sendTimed=async(p:any,stamp:()=>void)=>{stamp();const first=p.start;stamp();assert.equal(p.start,first);attempt++;throw Error('unknown ACK outcome');};await h.maybeStart(rows[1]);assert.equal(attempt,1);assert.equal(local.filter(p=>p.type==='start').length,2);assert(rows.every(r=>r.started&&Number.isFinite((r as any).start)));assert.equal(new Set(rows.map(r=>(r as any).start)).size,1);assert.equal(fails.length,0);
});
await check('late authenticated spectator begins the whole trace and ignores duplicate start',async()=>{
 const {h,local,worker}=host(),assembly=new Assembly(1,1,'a'.repeat(64)),roll={request:{id:'s',source:'b',authority:'b',theme:'ink_sketch'},kinds:['d20'],duration:1};h.rolls.set('s',roll);h.inbound.set('s',{source:'b',assembly,at:now(),retry:0,processing:true,prepared:true});
 const packet={v:1,build:BUILD,from:'b',type:'start',id:'s',hash:assembly.sha,start:now()+5000-3000};const before=now();await h.receive(packet,'b');await h.receive(packet,'b');const starts=local.filter(p=>p.type==='start');assert.equal(starts.length,1);assert(starts[0].at>=before+60);assert.equal(worker.filter(p=>p.type==='retain').length,1);assert.equal(h.started.get('s').hash,assembly.sha);
});
await check('actual onWorker send failure after arm never releases physics or rejects the roll',async()=>{
 const {h,local,worker,fails,sent}=host(),request={id:'s',source:'a',authority:'a',name:'a',kind:'d20',count:1,theme:'ink_sketch',seed:1,modifier:0},roll={version:2,request,kinds:['d20'],results:[10],fps:120,frames:2,poses:new Float32Array(14),contacts:[],physicsMs:0,steps:2,collisions:0,duration:1/120};h.pending=request;
 h.bus.postMessage=(p:any)=>{local.push(p);if(p.type==='prepare')void h.onLocal({type:'prepared',id:p.roll.request.id});};h.transport.sendTimed=async(p:any,stamp:()=>void)=>{stamp();sent.push({...p});if(p.type==='offer')await h.receive({v:1,build:BUILD,from:'b',type:'ready',id:p.id,hash:p.hash},'b');if(p.type==='start')throw Error('unknown ACK outcome');};await h.onWorker({id:'s',roll});assert.equal(local.filter(p=>p.type==='start').length,1);assert.equal(worker.filter(p=>p.type==='release').length,0);assert.equal(sent.filter(p=>p.type==='roll-rejected').length,0);assert.equal(fails.length,0);assert.equal(h.outgoing.get('s').started,true);
});
}
const result={checks:tests.length,passed:tests.filter(t=>t.passed).length,failed:tests.filter(t=>!t.passed).length,tests};writeFileSync(join(evidence,'clock-regression.json'),JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));if(result.failed)process.exitCode=1;
