import assert from 'node:assert/strict';
import {Controller} from '../extensions/workbench-dice3d/src/controller';
import {RollAudioMixer} from '../extensions/workbench-dice3d/src/audio-mixer';
import {diceCatalog} from '../extensions/workbench-dice3d/src/asset-catalog';
import {BUILD,now} from '../extensions/workbench-dice3d/src/types';
const tests:{name:string;passed:boolean;error?:string}[]=[];
const check=async(name:string,fn:()=>unknown)=>{timeouts.clear();intervals.clear();try{await fn();tests.push({name,passed:true});}catch(error){tests.push({name,passed:false,error:String(error)});}};
let sequence=0;
const timeouts=new Map<number,{fn:()=>void;ms:number}>(),intervals=new Map<number,{fn:()=>void;ms:number}>();
const real={setTimeout,clearTimeout,setInterval,clearInterval,window:(globalThis as any).window};
Object.assign(globalThis,{setTimeout:(fn:()=>void,ms:number)=>{const id=++sequence;timeouts.set(id,{fn,ms});return id;},clearTimeout:(id:number)=>timeouts.delete(id),setInterval:(fn:()=>void,ms:number)=>{const id=++sequence;intervals.set(id,{fn,ms});return id;},clearInterval:(id:number)=>intervals.delete(id)});
(globalThis as any).window={setInterval:globalThis.setInterval};
class FakeAudio{played=0;dropped=0;starts=0;stops=0;disposed=false;state(){return'running';}async resume(){}async load(){return{};}async loadRequired(){return{};}async loadStinger(){return{};}setVolume(){}fork(){return new FakeAudio();}start(){this.starts++;}stop(){this.stops++;}dispose(){this.disposed=true;}update(){}reserveHit(){}reserveRule(){}stinger(){}}
function mixer(){const m:any=new RollAudioMixer(()=>{},undefined,{themes:{ink_sketch:{}}} as any);m.root=new FakeAudio();return m;}
const audioPlan={duration:1,impacts:[],hits:[],stinger:null,rolling:{activity:new Float32Array([0]),pan:new Float32Array([0]),step:.03}};
async function audioStart(m:any,id:string){m.prepare(id,'ink_sketch',audioPlan);await m.release(id,now());}
function host(){const h:any=Object.create(Controller.prototype),sent:any[]=[],local:any[]=[],errors:any[]=[],seals:any[]=[],workerMessages:any[]=[];let closed=false,terminated=false,postTerminate=0;
 Object.assign(h,{transport:{id:'host',name:'Host',role:'GM',color:'#112233'},catalog:diceCatalog(),born:0,ready:true,physicsReady:true,overlayReady:true,disabled:false,disposed:false,retirementTimers:new Set(),wasAuthority:true,viewport:{w:1280,h:800},peers:new Map(),inbound:new Map(),outgoing:new Map(),rolls:new Map(),queue:[],requests:new Map(),accepted:new Map(),retainedUntil:new Map(),settledAt:new Map(),heldRolls:new Map(),reservations:new Map(),privateRunning:new Set(),privateAudiences:new Map(),secrets:new Map(),records:new Map(),probes:new Map(),clocks:new Map(),started:new Map(),events:[],receipts:[],lastState:now(),lastPresence:now(),keys:{forget:()=>{},seal:async(details:any,scope:string,audience:string[])=>{seals.push({details,scope,audience:[...audience]});return{scope,audience,commitment:'a'.repeat(64),data:{iv:'fixture',data:'fixture'},keys:[]};}},worker:{postMessage:(p:any)=>{if(terminated)postTerminate++;workerMessages.push(p);},terminate:()=>{terminated=true;}},bus:{postMessage:(p:any)=>{if(closed)throw new DOMException('BroadcastChannel is closed','InvalidStateError');local.push(p);},close:()=>{closed=true;}},stopTransport:()=>{},state:()=>{},log:()=>{},fail:(stage:string,error:unknown)=>errors.push({stage,error:String(error)}),next:()=>{},send:async(p:any)=>{sent.push(p);}});
 h.accept=(descriptor:any)=>{h.pending=h.requests.get(descriptor.id).request;if(descriptor.visibility!=='all')h.reservations.set(descriptor.id,{request:descriptor,broker:'host',at:now(),members:['host',...h.peers.keys()]});};
 return{h,sent,local,errors,seals,workerMessages,postsAfterTermination:()=>postTerminate};
}
function prediction(request:any){const id=request.id,n=request.formulas?.length||1,ids=Array.from({length:n},(_,i)=>`${id}.w0:${i}`),rows=ids.map((die,index)=>({index,formula:'1d6',total:3,operation:'',events:[],dice:[{id:die,kind:'d6',raw:3,value:3,sign:1,kept:true,flags:[]}]})),poses=new Float32Array(n*7);for(let i=0;i<n;i++)poses.set([i,1,0,0,0,0,1],i*7);
 return{version:2,request,kinds:Array(n).fill('d6'),results:Array(n).fill(3),fps:120,frames:1,poses,contacts:[],physicsMs:1,steps:1,collisions:0,duration:.1,births:Array(n).fill(0),formulaData:{ids,rows,logicalRows:rows,births:Array(n).fill(0),timeline:{births:Array(n).fill(0),clamps:[],decisionAt:.1},contexts:request.contexts,expression:'1d6'}};
}
async function submit(h:any,id:string,scopes:string[]|string='all'){const group=Array.isArray(scopes),visibility=group?'gm':scopes,contexts=group?scopes.map((visibility,i)=>({itemId:'token'+i,label:'Synthetic target '+i,rollerId:'player',visibility})):undefined;await h.submit({id,recipe:true,kind:'mixed',count:group?scopes.length:1,theme:'ink_sketch',modifier:0,visibility,...(group?{formulas:scopes.map(()=> '1d6'),contexts}:{formula:'1d6'})});return h.pending;}
async function finish(h:any,ids:string[]){for(const id of ids){await h.onLocal({type:'prepared',id});const out=h.outgoing.get(id);for(const peer of out.members)await h.receive({v:1,build:BUILD,from:peer,type:'ready',id,hash:out.hash},peer);}for(const id of ids){assert.equal(h.outgoing.get(id).started,true);await h.onLocal({type:'renderer-event',event:'render-complete',detail:{roll:id}});for(const peer of h.outgoing.get(id).members)await h.receive({v:1,build:BUILD,from:peer,type:'receipt',event:'render-complete',detail:{roll:id}},peer);}}
async function sweep(h:any){for(const out of h.outgoing.values())out.at=now()-60001;for(const lease of h.reservations.values())lease.at=now()-300001;for(const r of h.requests.values())r.at=now()-300001;await h.tick();}
const peers=(h:any)=>{for(const [id,role]of [['gm','GM'],['player','PLAYER']])h.peers.set(id,{id,name:id,role,ready:true,lastSeen:now(),rtt:1,offset:0,version:BUILD,born:1});};
await check('audio warmup and completed roll leave no interval',async()=>{const m=mixer();await m.warmup();assert.equal(intervals.size,0);await audioStart(m,'normal');assert.equal(intervals.size,1);m.tracks.get('normal').at=now()-2000;for(const {fn}of [...intervals.values()])fn();assert.equal(m.snapshot().active.length,0);assert.equal(intervals.size,0);});
await check('one paused track does not stop another playing track',async()=>{const m=mixer();await audioStart(m,'a');await audioStart(m,'b');m.pause('a');assert.equal(intervals.size,1);assert.equal(m.tracks.get('a').started,false);assert.equal(m.tracks.get('b').started,true);});
await check('stalled flight retiming does not replay due audio but reschedules future reservations',async()=>{
 const m=mixer(),hits=[2.95,3.1,3.4].map((t,ordinal)=>({t,ordinal,maximumFace:false})),rules=hits.map(({t})=>({t,kind:'max',pan:0}));
 m.prepare('stall','ink_sketch',{...audioPlan,duration:4,hits,rules});await m.release('stall',now()-3000);
 const track=m.tracks.get('stall');track.hit=2;track.rule=2;await m.retime('stall',now()-2800);
 assert.equal(track.hit,1,'already due audio is not repeated; cancelled future audio is requeued');assert.equal(track.rule,1);assert.equal(track.engine.starts,2);
 m.stop('stall');
});
await check('paused presentation resumes its saved audio without using time spent paused',async()=>{
 const m=mixer(),hits=[2.95,3.1].map((t,ordinal)=>({t,ordinal,maximumFace:false}));
 m.prepare('paused','ink_sketch',{...audioPlan,duration:4,hits});await m.release('paused',now()-3000);m.pause('paused');await m.retime('paused',now()-2800);
 assert.equal(m.tracks.get('paused').hit,0);m.stop('paused');
});
await check('retiming keeps due sounds which were never dispatched',async()=>{
 const m=mixer(),hits=[2.95,3.1].map((t,ordinal)=>({t,ordinal,maximumFace:false}));
 m.prepare('undispatched','ink_sketch',{...audioPlan,duration:4,hits});await m.release('undispatched',now()-3000);await m.retime('undispatched',now()-2800);
 assert.equal(m.tracks.get('undispatched').hit,0);m.stop('undispatched');
});
await check('all paused tracks stop ticking and resume once with preserved tracks',async()=>{const m=mixer();await audioStart(m,'a');await audioStart(m,'b');const a=m.tracks.get('a'),b=m.tracks.get('b');m.pause('a');m.pause('b');assert.equal(intervals.size,0);assert.equal(m.snapshot().active.length,2);await m.retime('a',now());await m.retime('b',now());assert.equal(intervals.size,1);assert.equal(m.tracks.get('a'),a);assert.equal(m.tracks.get('b'),b);assert.equal(a.engine.starts,2);assert.equal(b.engine.starts,2);m.stop('a');m.stop('b');assert.equal(intervals.size,0);});
await check('stopping last playing track also stops timer when paused tracks remain',async()=>{const m=mixer();await audioStart(m,'paused');await audioStart(m,'active');m.pause('paused');m.stop('active');assert.equal(intervals.size,0);assert.equal(m.snapshot().active.length,1);});
await check('25 successful public groups release every per-target audience snapshot',async()=>{const {h,errors}=host();for(let i=0;i<25;i++){const id='group-'+i,request=await submit(h,id,['all','all']);await h.onWorker({id,roll:prediction(request)});await finish(h,[id+'.g0',id+'.g1']);await sweep(h);assert.equal(h.privateAudiences.size,0);assert.equal(h.requests.size,0);assert.equal(h.outgoing.size,0);assert.equal(h.reservations.size,0);}assert.equal(errors.length,0);assert.equal(h.records.size,50);});
await check('normal public result and completion are unchanged',async()=>{const {h,seals,errors}=host(),id='public',request=await submit(h,id);await h.onWorker({id,roll:prediction(request)});assert.equal(h.records.get(id).complete,false);assert.equal(h.records.get(id).total,3);assert.equal(h.requests.size,0);await finish(h,[id]);assert.equal(h.records.get(id).complete,true);assert.equal(seals.length,0);assert.equal(errors.length,0);});
await check('private self/gm/players rolls keep frozen scopes and masked outgoing results',async()=>{for(const [scope,audience]of [['self',['host']],['gm',['gm','host']],['players',['host','player']]] as const){const {h,seals,errors}=host();peers(h);const id='private-'+scope,request=await submit(h,id,scope);h.peers.set('late-gm',{id:'late-gm',name:'late',role:'GM',ready:true,lastSeen:now(),rtt:1,version:BUILD,born:1});await h.onWorker({id,roll:prediction(request)});assert.equal(errors.length,0);assert.deepEqual(seals[0].audience,audience);assert.equal(seals[0].scope,scope);assert.deepEqual(h.outgoing.get(id).roll.results,[0]);assert.equal(h.records.get(id).total,3);assert.equal(h.privateAudiences.size,0);await finish(h,[id]);assert.equal(h.records.get(id).complete,true);}});
await check('mixed public/private group releases snapshots without exposing hidden faces',async()=>{const {h,seals,errors}=host();peers(h);const id='mixed',request=await submit(h,id,['all','gm']);await h.onWorker({id,roll:prediction(request)});assert.equal(errors.length,0);assert.equal(h.privateAudiences.size,0);assert.deepEqual(h.outgoing.get(id+'.g0').roll.results,[3]);assert.deepEqual(h.outgoing.get(id+'.g1').roll.results,[0]);assert.equal(seals.length,1);assert.deepEqual(seals[0].audience,['gm','host']);await finish(h,[id+'.g0',id+'.g1']);assert.equal(h.records.get(id+'.g0').complete,true);assert.equal(h.records.get(id+'.g1').complete,true);});
await check('25 local public physics failures retire requests and allow a subsequent successful roll',async()=>{const {h,errors}=host();for(let i=0;i<25;i++){const id='failure-'+i;await submit(h,id);await h.onWorker({id,error:'synthetic physics failure'});}await sweep(h);assert.equal(errors.length,25);assert.equal(h.requests.size,0);const request=await submit(h,'recovery');await h.onWorker({id:'recovery',roll:prediction(request)});await finish(h,['recovery']);assert.equal(h.records.get('recovery').total,3);assert.equal(h.records.get('recovery').complete,true);});
await check('private failure still cancels reservation and sends the same private failure notice',async()=>{const {h,sent}=host(),id='secret-failure';await submit(h,id,'self');await h.onWorker({id,error:'synthetic physics failure'});assert.equal(h.requests.size,0);assert.equal(h.privateAudiences.size,0);assert.equal(h.reservations.size,0);assert.equal(h.records.size,0);assert.equal(sent.filter(p=>p.type==='secret-failed'&&p.id===id).length,1);});
await check('group failure before any child exists releases all submitted child snapshots',async()=>{const {h}=host(),id='early-group';await submit(h,id,['all','gm']);await h.onWorker({id,error:'synthetic early group failure'});assert.equal(h.privateAudiences.size,0);assert.equal(h.requests.size,0);assert.equal(h.reservations.size,0);});
await check('mid-group sealing failure cancels unstarted siblings and preserves earlier completed private results',async()=>{const {h}=host(),prior=await submit(h,'prior-secret','self');await h.onWorker({id:'prior-secret',roll:prediction(prior)});await finish(h,['prior-secret']);const previous=h.records.get('prior-secret');const id='partial-group',request=await submit(h,id,['all','gm']),seal=h.keys.seal;h.keys.seal=async(...args:any[])=>{if(args[0].id===id+'.g1')throw Error('synthetic seal failure');return seal(...args);};await h.onWorker({id,roll:prediction(request)});assert.equal(h.privateAudiences.size,0);assert.equal(h.requests.size,0);assert(!h.reservations.has(id));assert(!h.outgoing.has(id+'.g0'));assert(!h.records.has(id+'.g0'));assert.equal(h.records.get('prior-secret'),previous);assert.equal(previous.complete,true);assert.equal(previous.total,3);});
await check('a failed remote public request keeps the rejection notice',async()=>{const {h,sent}=host(),id='remote-failure';await submit(h,id);h.pending={...h.pending,source:'remote'};await h.onWorker({id,error:'synthetic physics failure'});assert.equal(h.requests.size,0);assert.equal(sent.filter(p=>p.type==='roll-rejected'&&p.to==='remote'&&p.id===id).length,1);});
await check('retirement retains its original deadline and only completes a cancelled roll at that deadline',async()=>{const {h}=host(),request=await submit(h,'timed'),roll=prediction(request);h.retainUntilExit(roll,now()+70);const deadline=h.retainedUntil.get('timed');h.records.set('timed',{id:'timed',source:'host',secret:false,complete:false,at:now()});await h.onLocal({type:'renderer-event',event:'render-cancelled',detail:{roll:'timed',failed:false}});assert.equal(h.records.get('timed').complete,false);const scheduled=[...timeouts.values()];assert.equal(scheduled.length,2);assert(Math.abs(scheduled[0].ms-(deadline-now()+40))<100);assert(Math.abs(scheduled[1].ms-(deadline-now()))<100);for(const {fn}of scheduled)fn();assert.equal(h.records.get('timed').complete,true);assert.equal(h.retirementTimers.size,0);assert.equal(h.heldRolls.size,0);});
await check('dispose cancels both retirement callbacks and suppresses already captured late callbacks',async()=>{const {h,postsAfterTermination}=host(),request=await submit(h,'disposed'),roll=prediction(request);h.retainUntilExit(roll,now()+70);h.records.set('disposed',{id:'disposed',source:'host',secret:false,complete:false,at:now()});await h.onLocal({type:'renderer-event',event:'render-cancelled',detail:{roll:'disposed',failed:false}});const callbacks=[...timeouts.values()].map(t=>t.fn);assert.equal(callbacks.length,2);h.dispose();assert.equal(timeouts.size,0);assert.equal(h.retirementTimers.size,0);for(const callback of callbacks)callback();assert.equal(postsAfterTermination(),0);assert.equal(h.records.get('disposed').complete,false);h.dispose();});
await check('retirement scheduled after disposal cannot restart a retired callback',async()=>{const {h}=host(),request=await submit(h,'late-retirement'),roll=prediction(request);h.dispose();h.retainUntilExit(roll,now()+70);assert.equal(timeouts.size,0);});
await check('combined: authenticated restart cancels grouped request and every frozen audience during upload',async()=>{
 for(const scopes of [['all','all'],['all','gm'],['gm','all']]){
 const {h,sent,local,seals,errors}=host();peers(h);h.keys.remember=async()=>{};
 h.peers.get('player').session='11111111-1111-1111-1111-111111111111';
 const id='restart-'+scopes.join('-'),request=await submit(h,id,scopes),send=h.send;
 h.send=async(p:any)=>{await send(p);if(p.type==='offer'&&p.id===id+'.g0')await h.receive({v:1,build:BUILD,from:'player',type:'hello',session:'22222222-2222-2222-2222-222222222222',name:'Player',role:'PLAYER',color:'#112233',ready:true,born:1,inlineRollV1:true,inlineChunkV1:true},'player');};
 await h.onWorker({id,roll:prediction(request)});
 assert.equal(h.requests.size,0);assert.equal(h.privateAudiences.size,0);assert.equal(h.reservations.size,0);assert.equal(h.outgoing.size,0);assert.equal(h.records.size,0);
 assert(!sent.some((p:any)=>p.type==='start'||p.type==='offer'&&p.id===id+'.g1'));
 assert(!local.some((p:any)=>p.type==='start'||p.type==='prepare'&&p.roll.request.id===id+'.g1'));
 assert(errors.some((p:any)=>p.stage==='peer-restarted'));
 }
});
await check('combined: group offer ACK failure clears pending snapshots and preserves completed prior result',async()=>{
 const {h,errors}=host();peers(h);const prior=await submit(h,'prior-public');await h.onWorker({id:'prior-public',roll:prediction(prior)});await finish(h,['prior-public']);const kept=h.records.get('prior-public');
 const id='failed-group',request=await submit(h,id,['all','gm']),send=h.send;
 h.send=async(p:any)=>{if(p.type==='offer'&&p.id===id+'.g0')throw Error('review ACK failure');await send(p);};
 await h.onWorker({id,roll:prediction(request)});
 assert.equal(h.requests.size,0);assert.equal(h.privateAudiences.size,0);assert.equal(h.reservations.size,0);
 assert(!h.outgoing.has(id+'.g0'));assert(!h.records.has(id+'.g0'));assert.equal(h.records.get('prior-public'),kept);assert.equal(kept.complete,true);assert(errors.some((p:any)=>p.stage==='physics/trajectory'));
});

Object.assign(globalThis,{setTimeout:real.setTimeout,clearTimeout:real.clearTimeout,setInterval:real.setInterval,clearInterval:real.clearInterval});if(real.window===undefined)delete(globalThis as any).window;else(globalThis as any).window=real.window;
console.log(JSON.stringify({scope:'Actual Controller and RollAudioMixer; synthetic physics, transport, cryptographic seal, browser audio and clock boundaries. No browser heap/GPU measurement.',checks:tests.length,passed:tests.filter(t=>t.passed).length,failed:tests.filter(t=>!t.passed).length,tests},null,2));
if(tests.some(t=>!t.passed))process.exitCode=1;
