import assert from 'node:assert/strict';
import {Controller} from '../extensions/workbench-dice3d/src/controller';
import {diceCatalog} from '../extensions/workbench-dice3d/src/asset-catalog';
import {BUILD,now} from '../extensions/workbench-dice3d/src/types';
import {encodeRoll,hash,split,Assembly,sizeOf,MAX_MESSAGE_BYTES} from '../extensions/workbench-dice3d/src/wire.mjs';
// Historical runner name retained so existing aggregate and CI gates keep covering this protocol.
const tests:any[]=[];const check=async(name:string,fn:()=>any)=>{try{await fn();tests.push({name,passed:true})}catch(e){tests.push({name,passed:false,error:String(e)})}};
function host(){const h:any=Object.create(Controller.prototype),sent:any[]=[],local:any[]=[],worker:any[]=[],errors:any[]=[];
 Object.assign(h,{transport:{id:'host',name:'Host',role:'GM'},catalog:diceCatalog(),ready:true,disabled:false,born:0,peers:new Map([['peer',{id:'peer',session:'12345678-1234-1234-1234-123456789012',name:'Peer',role:'PLAYER',ready:true,born:1,lastSeen:now(),rtt:20,offset:0,version:BUILD,inlineRollV1:true,inlineChunkV1:true}]]),inbound:new Map(),outgoing:new Map(),rolls:new Map(),queue:[],requests:new Map(),accepted:new Map(),retainedUntil:new Map(),settledAt:new Map(),heldRolls:new Map(),reservations:new Map(),privateRunning:new Set(),privateAudiences:new Map(),secrets:new Map(),records:new Map(),probes:new Map(),clocks:new Map(),started:new Map(),events:[],lastState:now(),lastPresence:now(),bytesReceived:0,packetsReceived:0,bytesSent:0,packetsSent:0,viewport:{w:390,h:844},keys:{forget:()=>{},remember:async()=>{},ready:Promise.resolve(),publicKey:'synthetic'},worker:{postMessage:(p:any)=>worker.push(p)},bus:{postMessage:(p:any)=>local.push(p)},state:()=>{},sendRecords:()=>{},log:()=>{},fail:(...e:any[])=>errors.push(e),next:()=>{},addRecord:()=>{},retainUntilExit:()=>{},send:async(p:any,stamp?:(q:any)=>void)=>{stamp?.(p);sent.push(structuredClone(p));},ping:async()=>{}});return {h,sent,local,worker,errors};}
function roll(count=1,frames=30){const request:any={id:'r',source:'host',authority:'host',name:'Host',kind:'d6',count,theme:'ink_sketch',seed:1,modifier:0,visibility:'all'};return{version:2,request,kinds:Array(count).fill('d6'),results:Array(count).fill(3),fps:120,frames,poses:new Float32Array(frames*count*7),contacts:[],physicsMs:1,steps:frames*2,collisions:0,duration:(frames-1)/120};}
async function produce(options:any={}){const fixture=host(),{h,sent,local}=fixture,r=roll(options.count??1,options.frames??30);options.alterRoll?.(r);options.alter?.(h);h.pending=r.request;
 h.bus.postMessage=(p:any)=>{local.push(p);if(p.type==='prepare')void h.onLocal({type:'prepared',id:p.roll.request.id});};
 h.send=async(p:any,stamp?:(q:any)=>void)=>{stamp?.(p);sent.push(structuredClone(p));if(p.type==='offer'){const out=h.outgoing.get(p.id);for(const member of out?.members||[])out.wait.delete(member);await options.duringOffer?.(h,p);}await options.duringSend?.(h,p);};
 await h.onWorker({id:r.request.id,roll:r});return{...fixture,r};}
function assertQueued(sent:any[],expectedCount?:number){
 const offer=sent.find(p=>p.type==='offer');assert(offer);assert.equal(offer.inlineChunk,undefined);
 const chunks=sent.filter(p=>p.type==='chunk');assert.equal(chunks.length,offer.total);
 assert.deepEqual(chunks.map(p=>p.index),Array.from({length:offer.total},(_,i)=>i));
 assert.deepEqual(sent.filter(p=>['offer','chunk','chunks-done','start'].includes(p.type)).map(p=>p.type),['offer',...chunks.map(()=> 'chunk'),'chunks-done','start']);
 if(expectedCount!==undefined)assert.equal(offer.total,expectedCount);
 for(const p of sent)assert(sizeOf({...p,v:1,build:BUILD,from:'host'})<=MAX_MESSAGE_BYTES);
 return {offer,chunks};
}
await check('one complete small trace retains manifest, every data slot and trailer',async()=>{const{sent,local,errors}=await produce();assertQueued(sent,1);assert.equal(local.filter(p=>p.type==='start').length,1);assert.deepEqual(errors,[]);});
await check('one, two, five, nine and ten dice use the same single-chunk queue',async()=>{for(const count of [1,2,5,9,10]){const{sent}=await produce({count});assertQueued(sent,1);}});
await check('old, unknown and inline-capable peers all receive legacy packets',async()=>{for(const flag of [undefined,false,'true',1,true]){const{sent}=await produce({alter:(h:any)=>{h.peers.get('peer').inlineRollV1=flag;h.peers.get('peer').inlineChunkV1=flag;}});assertQueued(sent);}});
await check('one, two, five, nine and ten dice keep every multi-chunk data slot and tail hint',async()=>{for(const count of [1,2,5,9,10]){const{sent}=await produce({count,frames:300,alterRoll:(r:any)=>{let seed=91;for(let i=0;i<r.poses.length;i++){seed=(Math.imul(1664525,seed)+1013904223)>>>0;r.poses[i]=seed/2**32;}}});const{offer}=assertQueued(sent);assert(offer.total>1);}});
await check('a grouped child retains the established group transport',async()=>{const{sent}=await produce({alterRoll:(r:any)=>r.request.batch={id:'g',index:0,size:1}});const offer=sent.find(p=>p.type==='offer');assert.equal(offer.inlineChunk,undefined);assert.deepEqual(sent.filter(p=>['offer','chunk','chunks-done'].includes(p.type)).map(p=>p.type),['offer','chunk','chunks-done']);});
await check('largest valid audience keeps broadcast and targeted retry envelopes bounded',async()=>{const{h,sent}=await produce({alter:(h:any)=>{h.peers.clear();for(let i=0;i<64;i++){const id=String(i).padStart(2,'0')+'x'.repeat(98);h.peers.set(id,{id,ready:true,lastSeen:now(),rtt:20,version:BUILD,inlineRollV1:true,inlineChunkV1:true});}},frames:250,alterRoll:(r:any)=>{let seed=7;for(let i=0;i<r.poses.length;i++){seed=(Math.imul(1664525,seed)+1013904223)>>>0;r.poses[i]=seed/2**32;}}});const{offer}=assertQueued(sent,1);for(const id of offer.members)assert(sizeOf({...h.offer(h.outgoing.get('r'),id),v:1,build:BUILD,from:'host'})<=MAX_MESSAGE_BYTES);});
await check('actual hello does not advertise either withdrawn inline protocol',async()=>{const{h,sent}=host();delete h.send;h.transport.send=async(p:any)=>sent.push(p);await h.send({type:'hello',ready:true});assert.equal(sent.length,1);assert.equal(sent[0].inlineRollV1,undefined);assert.equal(sent[0].inlineChunkV1,undefined);assert.equal(sent[0].publicKey,'synthetic');});
await check('peer hello accepts legacy fields and drops withdrawn capability flags',async()=>{const{h}=host();for(const flag of [true,undefined,'true',false]){await h.receive({v:1,build:BUILD,from:'peer',type:'hello',session:'12345678-1234-1234-1234-123456789012',name:'Peer',role:'PLAYER',ready:true,born:1,inlineRollV1:flag,inlineChunkV1:flag},'peer');assert.equal(h.peers.get('peer').inlineRollV1,undefined);assert.equal(h.peers.get('peer').inlineChunkV1,undefined);assert.equal(h.peers.get('peer').ready,true);}});
await check('unprepared local renderer cannot be bypassed by a ready peer',async()=>{const{h,sent,local}=host(),r=roll();h.pending=r.request;h.send=async(p:any,stamp?:(q:any)=>void)=>{stamp?.(p);sent.push(p);if(p.type==='offer')h.outgoing.get(p.id).wait.delete('peer');};await h.onWorker({id:'r',roll:r});assert(h.outgoing.get('r').wait.has('host'));assert(!local.some(p=>p.type==='start'));await h.onLocal({type:'prepared',id:'r'});assert.equal(local.filter(p=>p.type==='start').length,1);});
await check('neither peer readiness nor local preparation bypasses in-flight uploads',async()=>{const{sent}=await produce({duringSend:async(h:any,p:any)=>{if(['offer','chunk','chunks-done'].includes(p.type)){await h.maybeStart(h.outgoing.get('r'));assert(!h.outgoing.get('r').started);}}});assertQueued(sent);});
await check('authenticated peer restart during offer ACK cannot resurrect discarded roll',async()=>{const{sent,local,h}=await produce({duringOffer:async(h:any)=>{await h.receive({v:1,build:BUILD,from:'peer',type:'hello',session:'87654321-4321-4321-4321-210987654321',name:'Peer',role:'PLAYER',ready:true,born:1,inlineRollV1:true},'peer');}});assert.equal(h.outgoing.size,0);assert(local.some(p=>p.type==='discard'));assert.equal(sent.filter(p=>['chunk','chunks-done','start'].includes(p.type)).length,0);assert.equal(local.filter(p=>p.type==='start').length,0);});
await check('failed manifest, chunk or trailer acknowledgement never starts an unconfirmed roll',async()=>{for(const type of ['offer','chunk','chunks-done']){const{sent,local,errors}=await produce({duringSend:async(_h:any,p:any)=>{if(p.type===type)throw Error('ACK unavailable');}});assert.equal(sent.filter(p=>p.type==='start').length,0);assert.equal(local.filter(p=>p.type==='start').length,0);assert(errors.some(e=>String(e).includes('ACK unavailable')));}});
await check('restart aborts all remaining public children of an in-flight group',async()=>{const{h,sent,local}=host(),r:any=roll(2,2);r.request={...r.request,id:'g',recipe:true,groupSize:2,visibility:'gm'};
 r.formulaData={ids:['da','db'],births:[0,0],contexts:[{visibility:'all',rollerId:'host',itemId:null,label:'one'},{visibility:'all',rollerId:'host',itemId:null,label:'two'}],rows:[{formula:'1d6',dice:[{id:'da',value:3}],total:3},{formula:'1d6',dice:[{id:'db',value:3}],total:3}],timeline:{births:[0,0],clamps:[],decisionAt:0},expression:'1d6;1d6'};
 h.pending=r.request;h.reservations.set('g',{request:r.request,broker:'host',members:['host','peer'],at:now()});h.bus.postMessage=(p:any)=>{local.push(p);if(p.type==='prepare')void h.onLocal({type:'prepared',id:p.roll.request.id});};
 h.send=async(p:any,stamp?:(q:any)=>void)=>{stamp?.(p);sent.push(p);if(p.type==='offer'&&p.id==='g.g0'){const out=h.outgoing.get(p.id);out.wait.delete('peer');await h.receive({v:1,build:BUILD,from:'peer',type:'hello',session:'87654321-4321-4321-4321-210987654321',name:'Peer',role:'PLAYER',ready:true,born:1,inlineRollV1:true},'peer');}};
 await h.onWorker({id:'g',roll:r});assert.equal(h.outgoing.size,0);assert.equal(h.reservations.size,0);assert(!local.some(p=>p.type==='start'||p.type==='prepare'&&p.roll.request.id==='g.g1'));assert(!sent.some(p=>p.type==='offer'&&p.id==='g.g1'));});
async function packet(r=roll()){
 const{poses,contacts,...meta}=r,b=await encodeRoll({...meta,contacts:contacts.length},poses,contacts),chunks=split(b);
 return {chunks,p:{v:1,build:BUILD,from:'host',type:'offer',id:r.request.id,total:chunks.length,bytes:b.length,hash:await hash(b),members:['peer']}};
}
const chunk=(p:any,chunks:string[],index:number)=>({v:1,build:BUILD,from:'host',type:'chunk',id:p.id,index,data:chunks[index]});
function receiver(){const f=host();f.h.transport.id='peer';f.h.peers=new Map([['host',{id:'host',name:'Host',ready:true,born:0,lastSeen:now(),rtt:20,offset:0,version:BUILD}]]);f.h.born=1;return f;}
async function deliver(h:any,p:any,chunks:string[]){await h.receive(p,'host');for(let i=0;i<chunks.length;i++)await h.receive(chunk(p,chunks,i),'host');}
function noisyRoll(){const r=roll(9,90);let seed=91;for(let i=0;i<r.poses.length;i++){seed=(Math.imul(1664525,seed)+1013904223)>>>0;r.poses[i]=seed/2**32;}return r;}
async function fragments(){const wire=await packet(noisyRoll());assert(wire.chunks.length>1);return wire;}
await check('manifest alone cannot prepare and separate chunk validates the exact trace',async()=>{const{h,local}=receiver(),{p,chunks}=await packet();await h.receive(p,'host');assert.equal(local.length,0);await h.receive(chunk(p,chunks,0),'host');assert.equal(h.packetsReceived,2);assert.equal(h.bytesReceived,sizeOf(p)+sizeOf(chunk(p,chunks,0)));assert.deepEqual(h.rolls.get('r').results,[3]);assert.equal(local.filter(p=>p.type==='prepare').length,1);assert(!local.some(p=>p.type==='start'));});
await check('sender packets reassemble through the original Assembly without an inline decoder',async()=>{const{sent,r}=await produce(),{offer,chunks}=assertQueued(sent),assembly=new Assembly(offer.total,offer.bytes,offer.hash);for(const c of chunks)assembly.add(c.index,c.data);const bytes=await assembly.finish();assert.equal(bytes.length,offer.bytes);const{h,local}=receiver();for(const p of sent.filter(p=>['offer','chunk','chunks-done'].includes(p.type)))await h.receive({...p,v:1,build:BUILD,from:'host'},'host');assert.deepEqual(h.rolls.get('r').results,r.results);assert.deepEqual(h.rolls.get('r').poses,r.poses);assert.equal(local.filter(p=>p.type==='prepare').length,1);});
await check('repeated manifest and same chunk do not prepare twice',async()=>{const{h,local}=receiver(),{p,chunks}=await packet();await deliver(h,p,chunks);await h.receive(p,'host');await h.receive(chunk(p,chunks,0),'host');assert.equal(local.filter(p=>p.type==='prepare').length,1);});
await check('withdrawn inline payload is an unknown offer field and cannot prepare',async()=>{for(const inlineChunk of ['AA==',123]){const{h,local}=receiver(),{p,chunks}=await packet();await h.receive({...p,inlineChunk},'host');assert.equal(h.inbound.get('r').assembly.parts.size,0);assert.equal(local.length,0);await h.receive(chunk(p,chunks,0),'host');assert.deepEqual(h.rolls.get('r').results,[3]);}});
await check('invalid manifest is rejected before retaining any trajectory',async()=>{for(const extra of [{total:2},{bytes:0},{hash:'wrong'}]){const{h,local}=receiver(),{p}=await packet();await assert.rejects(h.receive({...p,...extra},'host'),/manifest/);assert.equal(h.inbound.size,0);assert.equal(local.length,0);}});
await check('conflicting duplicate manifest cannot change hash, total or bytes',async()=>{for(const extra of [{hash:'0'.repeat(64)},{total:2},{bytes:1}]){const{h,local}=receiver(),{p}=await packet();await h.receive(p,'host');await assert.rejects(h.receive({...p,...extra},'host'),/冲突/);assert.equal(h.inbound.get('r').assembly.bytes,p.bytes);assert.equal(local.length,0);}});
await check('malformed chunk fails before preparation',async()=>{for(const extra of [{data:123},{data:'AA=='},{index:-1}]){const{h,local}=receiver(),{p,chunks}=await packet();await h.receive(p,'host');await assert.rejects(h.receive({...chunk(p,chunks,0),...extra},'host'));assert.equal(local.length,0);assert.equal(h.rolls.size,0);}});
await check('wrong SHA and unauthorised manifest source never prepare or start',async()=>{const{h,local}=receiver(),{p,chunks}=await packet();await h.receive({...p,hash:'0'.repeat(64)},'host');await assert.rejects(h.receive(chunk(p,chunks,0),'host'),/SHA/);assert.equal(local.length,0);const f=receiver();await assert.rejects(f.h.receive({...p,from:'outsider'},'outsider'),/权威/);assert.equal(f.local.length,0);});
await check('a chunk from a different source cannot populate an authorised manifest',async()=>{const{h,local}=receiver(),{p,chunks}=await packet();await h.receive(p,'host');await h.receive({...chunk(p,chunks,0),from:'outsider'},'outsider');assert.equal(h.inbound.get('r').assembly.parts.size,0);assert.equal(local.length,0);});
await check('conflicting duplicate chunk is rejected without replacing the good roll',async()=>{const{h,local}=receiver(),{p,chunks}=await packet();await deliver(h,p,chunks);const altered=Buffer.from(chunks[0],'base64');altered[altered.length-1]^=1;await assert.rejects(h.receive({...chunk(p,chunks,0),data:altered.toString('base64')},'host'),/Conflicting/);assert.deepEqual(h.rolls.get('r').results,[3]);assert.equal(local.filter(p=>p.type==='prepare').length,1);});
await check('legacy transfer cannot make forbidden private results public',async()=>{for(const visibility of ['self','gm','players']){const r=roll();r.request.visibility=visibility;const{h,local}=receiver(),{p,chunks}=await packet(r);await assert.rejects(deliver(h,p,chunks),/权威\/结果/);assert.equal(local.length,0);assert.equal(h.rolls.size,0);}});
await check('invalid results, changed request and mismatched authority remain rejected',async()=>{for(const field of ['result','authority','request']){const r=roll(),{h,local}=receiver();if(field==='result')r.results[0]=99;if(field==='authority')r.request.authority='outsider';if(field==='request')h.requests.set('r',{request:{...r.request,seed:2}});const{p,chunks}=await packet(r);await assert.rejects(deliver(h,p,chunks));assert.equal(local.length,0);assert.equal(h.rolls.size,0);}});
await check('targeted preparation and late-start retries send plain manifests and repair on demand',async()=>{const{h,sent}=await produce();const out=h.outgoing.get('r');out.started=false;out.start=undefined;out.wait=new Set(['peer']);out.roll.request.source='peer';out.at=now()-3000;out.retry=0;sent.length=0;await h.tick();let offers=sent.filter(p=>p.type==='offer');assert(offers.length);assert(offers.every(p=>p.to==='peer'&&p.inlineChunk===undefined&&p.hash===out.hash));assert(!sent.some(p=>p.type==='chunk'));out.started=true;out.start=now();out.lastStartRetry=now()-2000;out.acks=new Set(['peer']);sent.length=0;await h.tick();offers=sent.filter(p=>p.type==='offer');assert(offers.length);assert(offers.every(p=>p.to==='peer'&&p.inlineChunk===undefined&&p.hash===out.hash));assert(sent.some(p=>p.type==='start'&&p.to==='peer'&&p.hash===out.hash));sent.length=0;await h.receive({v:1,build:BUILD,from:'peer',type:'missing',id:'r',indices:[0]},'peer');assert(sent.some(p=>p.type==='chunk'&&p.to==='peer'&&p.index===0&&p.data===out.chunks[0]));});
await check('multi-fragment receiver waits for every hash-verified chunk',async()=>{const{h,local}=receiver(),{p,chunks}=await fragments();await h.receive(p,'host');for(let i=chunks.length-1;i>=1;i--)await h.receive(chunk(p,chunks,i),'host');assert.equal(local.filter(p=>p.type==='prepare').length,0);await h.receive(chunk(p,chunks,0),'host');assert.equal(local.filter(p=>p.type==='prepare').length,1);assert.deepEqual(h.rolls.get('r').results,Array(9).fill(3));});
await check('duplicate manifest never postpones the missing-fragment repair deadline',async()=>{const{h,sent}=receiver(),{p,chunks}=await fragments();await h.receive(p,'host');await h.receive(chunk(p,chunks,0),'host');const inbound=h.inbound.get('r');inbound.at=now()-3100;const prior=inbound.at;await h.receive(p,'host');assert.equal(inbound.at,prior);await h.tick();const missing=sent.find(p=>p.type==='missing');assert(missing);assert.deepEqual(missing.indices,Array.from({length:chunks.length-1},(_,i)=>i+1));});
await check('genuinely new chunk advances progress while same-data duplicate does not',async()=>{const{h}=receiver(),{p,chunks}=await fragments();await h.receive(p,'host');const inbound=h.inbound.get('r');inbound.at=now()-3100;const wire=chunk(p,chunks,0);await h.receive(wire,'host');assert(inbound.at>now()-100);const fresh=inbound.at;await h.receive(wire,'host');assert.equal(inbound.at,fresh);});
await check('lost tail and trailer repair survives duplicate manifests and first chunks',async()=>{const{h,sent,local}=receiver(),{p,chunks}=await fragments();await h.receive(p,'host');for(let i=0;i<chunks.length-1;i++)await h.receive(chunk(p,chunks,i),'host');const inbound=h.inbound.get('r');inbound.at=now()-3100;const prior=inbound.at;for(let i=0;i<4;i++){await h.receive(p,'host');await h.receive(chunk(p,chunks,0),'host');}assert.equal(inbound.at,prior);await h.tick();const missing=sent.find(p=>p.type==='missing');assert.deepEqual(missing.indices,[chunks.length-1]);await h.receive(chunk(p,chunks,chunks.length-1),'host');assert.equal(local.filter(p=>p.type==='prepare').length,1);});
await check('tail before lost manifest needs manifest retry and all missing fragments',async()=>{const{h,sent,local}=receiver(),{p,chunks}=await fragments();for(let i=0;i<chunks.length;i++)await h.receive(chunk(p,chunks,i),'host');assert.equal(h.inbound.size,0);await h.receive(p,'host');assert.equal(local.length,0);h.inbound.get('r').at=now()-3100;await h.tick();const missing=sent.find(p=>p.type==='missing');assert.deepEqual(missing.indices,Array.from({length:chunks.length},(_,i)=>i));for(const i of missing.indices)await h.receive(chunk(p,chunks,i),'host');assert.equal(local.filter(p=>p.type==='prepare').length,1);});
await check('received trailer promptly requests lost tail without waiting for timeout',async()=>{const{h,sent,local}=receiver(),{p,chunks}=await fragments();await h.receive(p,'host');for(let i=0;i<chunks.length-1;i++)await h.receive(chunk(p,chunks,i),'host');await h.receive({v:1,build:BUILD,from:'host',type:'chunks-done',id:'r'},'host');assert.deepEqual(sent.find(p=>p.type==='missing').indices,[chunks.length-1]);assert.equal(local.length,0);});
const report={checks:tests.length,passed:tests.filter(t=>t.passed).length,failed:tests.filter(t=>!t.passed).length,boundary:'Production Controller/codec; established offer/chunk queue with in-memory transport and renderer acknowledgement. Not browser or phone latency.',tests};console.log(JSON.stringify(report,null,2));if(report.failed)process.exitCode=1;
