import assert from 'node:assert/strict';
import {readFileSync,writeFileSync} from 'node:fs';
import * as T from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {DiceRenderer} from '../extensions/workbench-dice3d/src/renderer';
import {diceCatalog} from '../extensions/workbench-dice3d/src/asset-catalog';
import {makeProjection,fitPixelsPerDie,projectVisual} from '../extensions/workbench-dice3d/src/native';
import {formulaCue,FormulaShow} from '../extensions/workbench-dice3d/src/research/presentation';
import {CueRenderer} from '../extensions/workbench-dice3d/src/cue-renderer';
import {buildCue} from '../extensions/workbench-dice3d/src/cue';
import {cuePlacement,cueSlots} from '../extensions/workbench-dice3d/src/cue-layout';
const out=process.env.DND_DICE_EVIDENCE!,rolls=JSON.parse(readFileSync(out+'/rolls.json','utf8')),catalog=diceCatalog();
const tests:any[]=[],check=(name:string,fn:()=>void)=>{try{fn();tests.push({name,passed:true});}catch(e){tests.push({name,passed:false,error:String(e)});}};
const views=[[320,568],[390,844],[568,320],[844,390],[768,1024],[1024,768],[1366,1024],[750,335]];
const models=new Map<string,T.Vector3[]>();
for(const [kind,asset] of Object.entries(catalog.dice)){const bytes=readFileSync('extensions/workbench-dice3d/public/'+asset.model),gltf=await new GLTFLoader().parseAsync(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),'');const positions=(gltf.scene.getObjectByName('RenderMesh') as T.Mesh).geometry.getAttribute('position');models.set(kind,Array.from({length:positions.count},(_,i)=>new T.Vector3().fromBufferAttribute(positions,i).multiplyScalar(40)));}
function fixture(roll:any,from:number[],to=from,ratio=1){
 const projection=makeProjection(from[0],from[1]);projection.pixelsPerDie=fitPixelsPerDie(projection,[roll.bounds]);
 const renderer:any=Object.create(DiceRenderer.prototype),container={clientWidth:to[0],clientHeight:to[1]},beams=buildCue(roll,projection,catalog.themes.ink_sketch).beams;
 const camera=new T.OrthographicCamera();camera.position.set(0,Math.cos(.1745329252)*44,-Math.sin(.1745329252)*44);camera.lookAt(0,0,0);camera.updateMatrixWorld(true);
 Object.assign(renderer,{container,camera,gl:{getSize:(v:T.Vector2)=>v.set(to[0],to[1]),getPixelRatio:()=>ratio,domElement:{width:Math.floor(to[0]*ratio),height:Math.floor(to[1]*ratio)},setSize(){}},rendererSize:new T.Vector2(),projection,active:[{roll,released:true,cue:{beams},show:{setSlotOffset(){}}}],ready:false,emit(){}});renderer.resize();return renderer;
}
let hullSamples=0,entrySamples=0,modelSamples=0,resizeCases=0;const steady:any[]=[];
for(const roll of rolls)for(const view of views){const projection=makeProjection(view[0],view[1]);projection.pixelsPerDie=fitPixelsPerDie(projection,[roll.bounds]);const entered=new Set<number>();let clips=0;
 for(let f=0;f<roll.frames;f++)for(let i=0;i<roll.kinds.length;i++){const o=(f*roll.kinds.length+i)*7,q=new T.Quaternion().fromArray(roll.poses,o+3),pos=new T.Vector3().fromArray(roll.poses,o);let clipped=false;
 for(const v of catalog.dice[roll.kinds[i] as keyof typeof catalog.dice].hull){const p=new T.Vector3(...v as [number,number,number]).applyQuaternion(q).add(pos),[x,y]=projectVisual(projection,p.x,p.y,p.z);hullSamples++;if(x<2.5||y<2.5||x>view[0]-2.5||y>view[1]-2.5)clipped=true;}
 if(!clipped)entered.add(i);else if(entered.has(i))clips++;else entrySamples++;
 }if(clips)steady.push({id:roll.request.id,view,clips});
}
check('steady full collision hulls remain visible after their deliberate offscreen entry',()=>assert.deepEqual(steady,[]));
for(const from of [[390,844],[844,390],[1024,768]])for(const to of views)for(const ratio of [1,1.5,2,3])check(`immediate settled model fit ${from} -> ${to} DPR ${ratio}`,()=>{
 for(const roll of rolls){const renderer=fixture(roll,from,to,ratio),p=renderer.projection;resizeCases++;
 for(let i=0;i<roll.kinds.length;i++){const offset=((roll.frames-1)*roll.kinds.length+i)*7,q=new T.Quaternion().fromArray(roll.poses,offset+3),pos=new T.Vector3().fromArray(roll.poses,offset);
 for(const local of models.get(roll.kinds[i])!){const world=local.clone().applyQuaternion(q).add(pos),[x,y]=projectVisual(p,world.x,world.y,world.z);modelSamples++;assert(x>=2.5&&x<=to[0]-2.5&&y>=2.5&&y<=to[1]-2.5,`${roll.request.id}: ${x},${y} not in ${to}`);
 const ndc=world.clone();ndc.x*=-1;ndc.project(renderer.camera);assert(Math.abs(x-(ndc.x+1)*to[0]/2)<.0001);assert(Math.abs(y-(1-ndc.y)*to[1]/2)<.0001);}
 }
 for(const beam of renderer.active[0].cue.beams){const o=((roll.frames-1)*roll.kinds.length+beam.dieIndex)*7;assert.deepEqual([beam.sourceX,beam.sourceY],projectVisual(p,...roll.poses.slice(o,o+3) as [number,number,number]));}
 }
});
check('collapsed containers retain finite positive camera scale and recover',()=>{for(const dims of [[0,0],[1,1],[8,8],[16,8]]){const r=fixture(rolls[0],[390,844],dims);assert(Number.isFinite(r.projection.pixelsPerDie)&&r.projection.pixelsPerDie>0);r.container.clientWidth=390;r.container.clientHeight=844;r.resize();for(let i=0;i<100;i++)r.animateProjection(1/60);assert(Math.abs(r.projection.pixelsPerDie-r.targetPixelsPerDie)<.02);}});
check('expansion and same-size active-roll fit retain smooth transitions',()=>{const r=fixture(rolls[0],[320,568],[1024,768]);assert(r.projection.pixelsPerDie<r.targetPixelsPerDie);const before=r.projection.pixelsPerDie;r.animateProjection(1/60);assert(r.projection.pixelsPerDie>before&&r.projection.pixelsPerDie<r.targetPixelsPerDie);const unchanged=r.projection.pixelsPerDie;r.active[0].roll={...rolls[0],bounds:{minX:-1,maxX:1,minZ:-1,maxZ:1}};r.layout();assert.equal(r.projection.pixelsPerDie,unchanged);assert(r.targetPixelsPerDie<unchanged);});
check('unconstrained desktop slots retain exact legacy positions',()=>{for(const [width,height,count] of [[1366,1024,5],[1366,1024,10],[1920,1080,9],[1024,768,5],[768,1024,5]]){const columns=Math.min(count,Math.max(1,Math.floor(width/250))),rows=Math.ceil(count/columns),slots=cueSlots(width,height,count);slots.forEach((slot,index)=>{const row=Math.floor(index/columns),inRow=Math.min(columns,count-row*columns);assert.equal(slot.x,(index%columns-(inRow-1)*.5)*Math.min(300,width/(inRow+.25)));assert.equal(slot.y,(row-(rows-1)*.5)*Math.min(170,height/(rows+1)));const fit=cuePlacement(width,height,slot.x,slot.y,slot.width,slot.height);assert.equal(fit.scale,1);assert.equal(fit.x,width*.5+slot.x);assert.equal(fit.y,height*.5+slot.y);});}});
check('viewport reflow snaps actual cue slots while same-viewport updates retain easing',()=>{const roll=rolls[0],r=fixture(roll,[844,390]);const shows=Array.from({length:5},()=>{const show:any=Object.create(CueRenderer.prototype);show.currentSlot=[0,0];show.targetSlot=[0,0];return show;});r.active=shows.map(show=>({roll,released:true,cue:{beams:[],modifier:{}},show}));r.reslot();shows.forEach(show=>{show.currentSlot=[...show.targetSlot];});r.container.clientWidth=320;r.container.clientHeight=568;r.resize();shows.forEach(show=>assert.deepEqual(show.currentSlot,show.targetSlot));const old=[...shows[0].currentSlot];shows[0].setSlotOffset(old[0]+50,old[1]+30,200,200);assert.deepEqual(shows[0].currentSlot,old);});
// Minimal DOM/Canvas doubles execute FormulaShow itself. Text widths are conservative modeled
// bounds; true browser font metrics, pixel visibility, safe-area behavior and GPU are separate QA.
class Element {children:Element[]=[];className='';textContent='';style:any={};width=0;height=0;title='';classList={add(){},toggle(){}};ctx:any;constructor(public tag:string){}append(...e:Element[]){this.children.push(...e);}remove(){}animate(){}querySelector(sel:string):Element|null{for(const e of this.children){if(sel[0]==='.'?e.className===sel.slice(1):e.tag===sel)return e;const child=e.querySelector(sel);if(child)return child;}return null;}getContext(){return this.ctx;}}
let currentCtx:any;Object.assign(globalThis,{document:{createElement:(tag:string)=>{const el=new Element(tag);if(tag==='canvas')el.ctx=currentCtx;return el;}},window:{devicePixelRatio:3},devicePixelRatio:3});
function context(){let matrix=[1,0,0,1,0,0],stack:any[]=[],font='10px sans-serif';const drawn:any[]=[],plates:any[]=[],arcs:any[]=[];const target:any={setTransform(a:number,b:number,c:number,d:number,e:number,f:number){matrix=[a,b,c,d,e,f];},save(){stack.push({matrix:[...matrix],font});},restore(){({matrix,font}=stack.pop());},translate(x:number,y:number){matrix[4]+=matrix[0]*x+matrix[2]*y;matrix[5]+=matrix[1]*x+matrix[3]*y;},scale(x:number,y:number){matrix[0]*=x;matrix[1]*=x;matrix[2]*=y;matrix[3]*=y;},fillText(text:string,x:number,y:number,maxWidth?:number){drawn.push({text,x:matrix[0]*x+matrix[2]*y+matrix[4],y:matrix[1]*x+matrix[3]*y+matrix[5],scale:matrix[0],font,maxWidth});},strokeText(){},arc(x:number,y:number,r:number){arcs.push({x:matrix[0]*x+matrix[4],y:matrix[3]*y+matrix[5],radius:r,scale:matrix[0]});},measureText(text:string){return{width:parseFloat(font.match(/([0-9.]+)px/)?.[1]||'10')*.65*text.length};},roundRect(x:number,y:number,w:number,h:number){plates.push({left:matrix[0]*x+matrix[4],top:matrix[3]*y+matrix[5],right:matrix[0]*(x+w)+matrix[4],bottom:matrix[3]*(y+h)+matrix[5]});}};Object.defineProperty(target,'font',{get:()=>font,set:v=>font=v});return{ctx:new Proxy(target,{get:(obj,key)=>key in obj?obj[key]:()=>{}}),drawn,plates,arcs};}
const formulaReports:any[]=[];
for(const view of views)for(const roll of rolls.filter((r:any)=>r.formulaData))check(`production FormulaShow ${roll.request.formula} at ${view}`,()=>{
 const original=JSON.stringify(roll),p=makeProjection(...view as [number,number]),ctx=context();currentCtx=ctx.ctx;const stage=new Element('stage') as any;stage.clientWidth=view[0];stage.clientHeight=view[1];const shows:any[]=[],cues:any[]=[];
 for(const row of roll.formulaData.rows){const included=new Set(row.dice.map((d:any)=>d.id)),indices=roll.formulaData.ids.map((id:string,i:number)=>included.has(id)?i:-1).filter((i:number)=>i>=0),ids=indices.map((i:number)=>roll.formulaData.ids[i]),poses=new Float32Array(roll.frames*ids.length*7);
 for(let f=0;f<roll.frames;f++)for(const [i,source] of indices.entries())poses.set(roll.poses.slice((f*roll.kinds.length+source)*7,(f*roll.kinds.length+source+1)*7),(f*ids.length+i)*7);
 const child={...roll,kinds:indices.map((i:number)=>roll.kinds[i]),results:indices.map((i:number)=>roll.results[i]),poses},fullRow={...row,compute:()=>row.total},cue=formulaCue(child,ids,fullRow,p,catalog.themes.ink_sketch),show=new FormulaShow(stage,child,ids,fullRow,new Element('article') as any,()=>p,roll.formulaData.timeline);shows.push(show);cues.push(cue);
 }
 const r=fixture(roll,view);r.active=shows.map((show,i)=>({roll:{masked:false},show,cue:cues[i],slot:0}));r.reslot();
 shows.forEach((show:any,i:number)=>{show.currentSlot=[...show.targetSlot];const cue=cues[i];show.draw(cue.firstBeam+.2,cue,1);if(cue.modifier){show.draw(cue.modifier.start+.15999,cue,1);show.draw(cue.modifier.start+.16001,cue,1);}show.draw(cue.finalReveal+.1,cue,1);show.draw(cue.finalReveal+.17,cue,1);assert.equal(show.total.textContent,String(cue.total));});
 const totals=ctx.drawn.filter(d=>/92px/.test(d.font));assert(totals.length);for(const d of totals){assert(Number.isFinite(d.maxWidth)&&d.maxWidth>0,'long totals must specify a positive fitted Canvas maxWidth');const half=d.maxWidth*d.scale/2+6*d.scale;assert(d.x-half>=-1e-6&&d.x+half<=view[0]*2+1e-6,'total lies within canvas');const halfHeight=92*.55*d.scale;assert(d.y-halfHeight>=-1e-6&&d.y+halfHeight<=view[1]*2+1e-6,'total vertical envelope lies within canvas');}
 for(const arc of ctx.arcs.filter(a=>Math.abs(a.radius-16.2)<.01)){const radius=arc.radius*arc.scale;assert(arc.x-radius>=0&&arc.y-radius>=0&&arc.x+radius<=view[0]*2&&arc.y+radius<=view[1]*2,'modifier recoil flare lies within canvas');}
 for(const plate of ctx.plates){assert(plate.left>=0&&plate.top>=0&&plate.right<=view[0]*2&&plate.bottom<=view[1]*2,'actual nameplate Canvas rectangle lies within canvas');}
 for(const show of shows){const [x,y]=show.currentSlot,[w,h]=show.slotSize,fit=cuePlacement(view[0],view[1],x,y,w,h,!!cues[shows.indexOf(show)].modifier);assert(fit.x-116*fit.scale>=0&&fit.x+116*fit.scale<=view[0]);assert(fit.y-110*fit.scale>=0&&fit.y+119*fit.scale<=view[1]);}
 assert.equal(JSON.stringify(roll),original,'presentation must not rewrite authoritative data');formulaReports.push({formula:roll.request.formula,physicalDice:roll.kinds.length,rows:shows.length,view,totals:cues.map(c=>c.total)});shows.forEach(show=>show.destroy());
});
for(const view of [[320,568],[568,320],[1366,1024]])for(const roll of rolls.filter((r:any)=>r.formulaData?.rows.length===1))for(const position of [[0,0],[view[0],0],[0,view[1]],[view[0],view[1]],[view[0]/2,view[1]/2]])check(`anchored compact cue ${roll.request.formula} ${view} at ${position}`,()=>{
 const ctx=context();currentCtx=ctx.ctx;const stage=new Element('stage') as any;stage.clientWidth=view[0];stage.clientHeight=view[1];const p=makeProjection(...view as [number,number]),row=roll.formulaData.rows[0],cue=formulaCue(roll,roll.formulaData.ids,{...row,compute:()=>row.total},p,catalog.themes.ink_sketch),show=new CueRenderer(stage,roll.request.id,'name','#76bceb');show.setAnchor(()=>({x:position[0],y:position[1]}),'Long formula label '+row.formula);
 if(cue.modifier){show.draw(cue.modifier.start+.15999,cue,1);show.draw(cue.modifier.start+.16001,cue,1);}show.draw(cue.finalReveal+.1,cue,1);show.draw(cue.finalReveal+.17,cue,1);
 for(const d of ctx.drawn.filter(d=>d.font.includes('30px')||d.font.includes('13px'))){const font=Number(d.font.match(/([0-9.]+)px/)[1]),width=Math.min(font*.65*d.text.length,d.maxWidth??Infinity),half=width*d.scale/2+3*d.scale,halfHeight=font*.55*d.scale;assert(d.x-half>=0&&d.x+half<=view[0]*2&&d.y-halfHeight>=0&&d.y+halfHeight<=view[1]*2,JSON.stringify(d));}
 for(const arc of ctx.arcs.filter(a=>Math.abs(a.radius-16.2)<.01)){const radius=arc.radius*arc.scale;assert(arc.x-radius>=0&&arc.y-radius>=0&&arc.x+radius<=view[0]*2&&arc.y+radius<=view[1]*2);}
 if(view[0]===1366&&position[0]===683&&position[1]===512){const actual=ctx.drawn.filter(d=>d.font.includes('30px')&&d.text===String(cue.total)).at(-1)!;assert.equal(actual.x,position[0]*2);assert.equal(actual.y,position[1]*2);assert(actual.maxWidth>=30*.65*actual.text.length,'unconstrained desktop total is not condensed');}
 show.destroy();
});
check('offscreen token anchors stay offscreen and are not pulled into the viewport',()=>{const ctx=context();currentCtx=ctx.ctx;const stage=new Element('stage') as any;stage.clientWidth=320;stage.clientHeight=568;const roll=rolls[0],cue=buildCue(roll,makeProjection(320,568),catalog.themes.ink_sketch),show=new CueRenderer(stage,'offscreen','name');show.setAnchor(()=>({x:-200,y:-200}),'offscreen');show.draw(cue.finalReveal+.1,cue,1);const total=ctx.drawn.find(d=>d.font.includes('30px'));assert(total&&total.x<0&&total.y<0);show.destroy();});
const entryTiming:any[]=[];
for(const roll of rolls.filter((r:any)=>!r.formulaData)){
 const [width,height]=roll.sourceView,p=makeProjection(width,height);p.pixelsPerDie=fitPixelsPerDie(p,[roll.bounds]);const partial:(number|null)[]=Array(roll.kinds.length).fill(null),full:(number|null)[]=Array(roll.kinds.length).fill(null);
 for(let frame=0;frame<roll.frames;frame++)for(let i=0;i<roll.kinds.length;i++){if(partial[i]!==null&&full[i]!==null)continue;const offset=(frame*roll.kinds.length+i)*7,q=new T.Quaternion().fromArray(roll.poses,offset+3),pos=new T.Vector3().fromArray(roll.poses,offset),project=(v:T.Vector3)=>{const point=v.clone().applyQuaternion(q).add(pos);return projectVisual(p,point.x,point.y,point.z);};
 if(partial[i]===null&&models.get(roll.kinds[i])!.some(v=>{const[x,y]=project(v);return x>=0&&x<=width&&y>=0&&y<=height;}))partial[i]=frame/roll.fps;
 if(full[i]===null&&catalog.dice[roll.kinds[i] as keyof typeof catalog.dice].hull.every(v=>{const[x,y]=project(new T.Vector3(...v as [number,number,number]));return x>=2.5&&x<=width-2.5&&y>=2.5&&y<=height-2.5;}))full[i]=frame/roll.fps;
 }
 entryTiming.push({id:roll.request.id,count:roll.kinds.length,kind:roll.request.kind,sourceView:roll.sourceView,firstPartialVertexSeconds:Math.min(...partial as number[]),firstFullHullSeconds:Math.min(...full as number[]),allFullHullSeconds:Math.max(...full as number[]),perDiePartialSeconds:partial,perDieFullSeconds:full});
}
const report={boundary:'Node real locked-Jolt traces; actual GLTF model vertices and Three camera matrices; production FormulaShow with modeled DOM/Canvas calls. No browser, real mobile, notch safe area, pixels, GPU, or performance claim.',checks:tests.length,passed:tests.filter(t=>t.passed).length,failed:tests.filter(t=>!t.passed).length,realJoltRolls:rolls.length,hullSamples,modelSamples,entrySamples,resizeCases,styles:Object.keys(catalog.themes),outlineAllowanceCssPx:2.5,reducedUsableArea:[750,335],entryTiming,formulaReports,tests};writeFileSync(out+'/result.json',JSON.stringify(report,null,2));console.log(JSON.stringify({...report,tests:tests.filter(t=>!t.passed),formulaReports:undefined,entryTiming:undefined},null,2));if(report.failed)process.exitCode=1;
