import {CARDS, STANDARD_CARDS, SPECIAL_CARDS, card, createGame, applyAction, eligibleActions, projectPublic, projectSeat, checkInvariants, flightStrength, RULE_PROMPTS, CARD_HINTS, cardName, type GameState, type GameAction} from "../extensions/three-dragon-ante/src/game/rules";
let assertions=0,actionSerial=0;
function check(value:unknown,label:string):asserts value{if(!value)throw Error(`ASSERTION: ${label}`);assertions++;}
function eq(a:unknown,b:unknown,label:string){check(JSON.stringify(a)===JSON.stringify(b),`${label}: ${JSON.stringify(a)} != ${JSON.stringify(b)}`);}
const game=(n=3,seed=777,specialIds?:string[])=>createGame({id:"test",seats:Array.from({length:n},(_,i)=>({id:`p${i}`,name:`Player ${i}`})),seed,specialIds});
function act(s:GameState,seat:number,kind:GameAction["kind"],data:Partial<GameAction>={}):GameState{
 const action={id:`action-${++actionSerial}`,revision:s.revision,seatId:s.seats[seat].id,kind,...data};const result=applyAction(s,action);check(result.ok,`valid ${kind} action ${JSON.stringify(action)} ${!result.ok?result.error.code:""}`);if(!result.ok)throw Error("unreachable");
 const errors=checkInvariants(result.state);check(errors.length===0,`invariants after ${kind}: ${errors}`);
 const pending=result.state.pending;if(pending){check(!!RULE_PROMPTS[pending.code],`choice prompt exists: ${pending.code}`);for(const option of pending.options){check(!!(option.code||option.cardId||option.seatId),`choice has presentation metadata: ${option.id}`);if(option.code)check(!!RULE_PROMPTS[option.code],`option prompt exists: ${option.code}`);if(option.cardId)check(CARDS.some(c=>c.id===option.cardId),`choice card exists: ${option.cardId}`);if(option.seatId)check(result.state.seats.some(p=>p.id===option.seatId),`choice seat exists: ${option.seatId}`);}}
 return result.state;
}
function pick(s:GameState,ids?:string[]):GameState{check(!!s.pending,"choice pending");return act(s,s.seats.findIndex(p=>p.id===s.pending!.seatId),"choose",{choiceId:s.pending!.id,optionIds:ids??[s.pending!.options[0].id]});}
function resolve(s:GameState,limit=100):GameState{while(s.pending&&limit-->0)s=pick(s);check(limit>0,"choice chain bounded");return s;}
interface Fixture{play:string;hand?:string[];flights?:string[][];hands?:string[][];ante?:string[];deck?:string[];n?:number;gold?:number;stakes?:number;round?:number;turnIndex?:number;active?:number;previous?:string}
function fixture(f:Fixture):GameState{
 const all=[f.play,...f.hand??[],...f.flights?.flat()??[],...f.hands?.flat()??[],...f.ante??[],...f.deck??[]];const required=[...new Set(all)].filter(id=>card(id).category!=="standard");
 const chosen=[...required,...SPECIAL_CARDS.map(c=>c.id).filter(id=>!required.includes(id))].slice(0,10);
 const s=game(f.n??3,123,chosen);s.stage="play";s.round=f.round??1;s.active=f.active??0;s.leader=0;s.turnIndex=f.turnIndex??0;s.stakes=f.stakes??80;s.ante=f.ante??[];s.effects=[];s.committed={};s.discard=[];
 for(let i=0;i<s.seats.length;i++){s.seats[i].gold=f.gold??50;s.seats[i].flight=(f.flights?.[i]??[]).map(cardId=>({cardId}));s.seats[i].hand=[...(f.hands?.[i]??[])];}
 s.seats[s.active].hand=[f.play,...f.hand??[]];
 const allocated=new Set([...s.seats.flatMap(p=>[...p.hand,...p.flight.map(c=>c.cardId)]),...s.ante]);
 const pool=[...STANDARD_CARDS.map(c=>c.id),...chosen];
 // Fill unused opponent hands without duplicating explicitly arranged cards.
 for(let i=0;i<s.seats.length;i++)if(!s.seats[i].hand.length)for(let fill=0;fill<3;fill++){const id=pool.find(id=>!allocated.has(id)&&!f.deck?.includes(id))!;s.seats[i].hand.push(id);allocated.add(id);}
 s.deck=[...f.deck??[],...pool.filter(id=>!allocated.has(id)&&!f.deck?.includes(id))];s.randomState=1;s.roundCards=s.seats.map(()=>null);
 if(f.previous)s.roundCards[(s.active+s.seats.length-1)%s.seats.length]=f.previous;
 return s;
}
const play=(f:Fixture)=>act(fixture(f),f.active??0,"play",{cardId:f.play});
eq(CARDS.length,100,"base box 100 cards");eq(STANDARD_CARDS.length,70,"70 standard dragons");eq(SPECIAL_CARDS.filter(c=>c.category==="legendary").length,15,"15 legendary");eq(SPECIAL_CARDS.filter(c=>c.category==="mortal").length,15,"15 mortals");check(new Set(CARDS.map(c=>c.id)).size===100,"unique identities");
for(const n of [2,6]){const s=game(n);eq(s.seats.map(p=>p.gold),Array(n).fill(n*10),`${n} player starting gold`);eq(s.seats.map(p=>p.hand.length),Array(n).fill(6),`${n} player opening hands`);eq(s.deck.length,80-n*6,"80 card default deck");eq(s.excluded.length,20,"unselected cards stay private");eq(game(n),game(n),"seeded creation deterministic");}

let s=fixture({play:"black-1",n:3,hands:[[],["blue-1","blue-11"],["white-1","white-8"]],hand:["red-2"],stakes:0});s.stage="ante";s.round=0;
s=act(s,0,"ante",{cardId:"black-1"});const secret=projectPublic(s);check(!JSON.stringify(secret).includes('"black-1"'),"unrevealed ante absent from public projection");check(!JSON.stringify(projectSeat(s,"p1")).includes('"black-1"'),"other seat cannot see hidden ante");eq(projectSeat(s,"p0").committedAnte?.id,"black-1","own committed ante visible privately");
s=act(s,1,"ante",{cardId:"blue-1"});s=act(s,2,"ante",{cardId:"white-1"});eq(s.stage,"ante","all tied ante repeats");eq(s.stakes,0,"tied ante charges nothing");eq(s.discard.slice(0,3),["black-1","blue-1","white-1"],"tied ante discarded");
s=act(s,0,"ante",{cardId:"red-2"});s=act(s,1,"ante",{cardId:"blue-11"});s=act(s,2,"ante",{cardId:"white-8"});eq(s.leader,1,"highest untied ante leader");eq(s.events.filter(e=>e.code==="PAID_STAKES").slice(0,3).map(e=>e.amount),[11,11,11],"ante pays highest strength from each player before forced buying");

// Action guards and idempotency never expose state or consume randomness.
const stateBefore=JSON.stringify(s),valid={id:"repeat",revision:s.revision,seatId:"p1",kind:"play" as const,cardId:s.seats[1].hand[0]};const good=applyAction(s,valid);check(good.ok,"valid action accepted");if(good.ok){const again=applyAction(good.state,valid);check(again.ok&&again.duplicate&&again.state===good.state,"same ID and payload idempotent before revision guard");const conflict=applyAction(good.state,{...valid,cardId:s.seats[1].hand[1]});check(!conflict.ok&&conflict.error.code==="ACTION_ID_CONFLICT","same ID cannot alter payload");const stale=applyAction(good.state,{...valid,id:"stale"});check(!stale.ok&&stale.error.code==="STALE_REVISION","stale action rejected");}
const intruder=applyAction(s,{...valid,seatId:"intruder"});check(!intruder.ok&&intruder.error.code==="UNKNOWN_SEAT","unknown seat rejected");const wrong=applyAction(s,{...valid,seatId:"p0",cardId:s.seats[0].hand[0]});check(!wrong.ok&&wrong.error.code==="NOT_YOUR_TURN","wrong seat rejected");eq(JSON.stringify(s),stateBefore,"actions do not mutate input");
check(!("hand" in projectPublic(s).seats[0])&&!Object.keys(projectSeat(s,"p0")).some(key=>["deck","excluded","accepted","randomState","queue"].includes(key)),"projections whitelist public and own data");

// Every standard family and every special family has a real power scenario.
s=play({play:"black-1",hand:["white-8"]});eq(s.stakes,77,"black takes three");
s=play({play:"black-raider",hand:["white-8"],n:4});eq(s.seats.map(p=>p.gold),[60,48,47,46],"raider sequential escalating collection");
for(const [id,multiplier] of [["blue-2",1],["blue-overlord",2]] as const){s=play({play:id,hand:["white-8"],flights:[["red-2"],[],[]]});s=pick(s,["stakes"]);eq(s.stakes,80+4*multiplier,`${id} scales stakes with flight size`);s=play({play:id,hand:["white-8"]});s=pick(s,["hoard"]);eq(s.seats[0].gold,50+2*multiplier,`${id} hoard branch`);}
s=play({play:"brass-3",hand:["white-8"],hands:[[],["red-2"],["gold-9"]]});eq(s.pending?.seatId,"p2","brass chooses right neighbor");s=pick(s,["gold-9"]);check(s.seats[0].hand.includes("gold-9")&&!s.seats[2].hand.includes("gold-9"),"brass visible stronger good transfer");
s=play({play:"green-5",hand:["white-8"],hands:[[],["red-2"],["gold-9"]]});eq(s.pending?.seatId,"p1","green chooses left neighbor");s=pick(s,["red-2"]);check(s.seats[0].hand.includes("red-2"),"green weaker evil transfer");
for(const id of ["brass-sultan","green-schemer"]){s=play({play:id,hand:["white-8"],n:2});s=resolve(s);eq(s.seats.map(p=>p.gold),[60,40],`${id} hits single neighbor twice in two-player game`);}
s=play({play:"bronze-7",hand:["white-8"],ante:["black-2","blue-2","gold-13"]});s=pick(s,["blue-2"]);s=pick(s,["black-2"]);check(s.seats[0].hand.includes("blue-2")&&s.seats[0].hand.includes("black-2")&&s.ante.length===1,"bronze tied lowest choices");
s=play({play:"bronze-warlord",hand:["white-8"],ante:[]});check(s.effects.some(e=>e.kind==="warlord"),"warlord persists with no ante cards");
s=play({play:"copper-1",hand:["white-8"],deck:["copper-3","black-3"]});eq(s.seats[0].flight[0].cardId,"black-3","copper chains replacement");eq(s.roundCards[0],"black-3","replacement controls following trigger and leader");eq(s.stakes,77,"replacement power triggered");
s=play({play:"copper-trickster",hand:["white-8"],flights:[["black-9"],[],[]],deck:["black-1"]});s=pick(s,["black-9"]);s=pick(s,["skip"]);eq(s.stakes,80,"trickster can skip replacement power");check(s.seats[0].flight.some(f=>f.cardId==="black-1"),"trickster replacement mandatory");
for(const [id,replacement] of [["chromatic-wyrmling","black-1"],["metallic-wyrmling","gold-2"]]){s=play({play:id,hand:[replacement,"white-8"]});s=pick(s,[replacement]);check(s.seats[0].flight[0].cardId===replacement,`${id} optional hand replacement`);s=play({play:id,hand:[replacement,"white-8"]});s=pick(s,["skip"]);eq(s.seats[0].flight[0].cardId,id,`${id} may keep itself`);}
s=play({play:"gold-2",hand:["white-8"],flights:[["silver-2"],[],[]]});eq(s.seats[0].hand.length,3,"gold draws for all own good dragons including itself");
s=play({play:"gold-monarch",hand:["white-8"]});check(s.effects.some(e=>e.kind==="monarch"),"monarch gift condition armed");
s=play({play:"silver-2",hand:["white-8"],flights:[[],["gold-2"],[]],hands:[[],["red-2"],["blue-1"]]});eq(s.seats.map(p=>p.hand.length),[2,2,1],"silver draws for players with good dragons only");
s=play({play:"silver-seer",hand:["white-8"],deck:["blue-1","black-1","red-2","gold-13"]});check(s.pending?.code==="KEEP_SEER_CARD","seer offers private top-three choice");const seerIds=s.pending!.options.map(o=>o.id);check(seerIds.every(id=>!JSON.stringify(projectPublic(s)).includes(`"${id}"`)),"seer candidates absent publicly");check(seerIds.every(id=>!JSON.stringify(projectSeat(s,"p1")).includes(`"${id}"`)),"seer candidates absent for opponent");s=pick(s,[seerIds[1]]);check(s.seats[0].hand.includes(seerIds[1]),"seer takes chosen card");
s=play({play:"white-1",hand:["white-8"],flights:[[],["red-2"],["blue-2"]]});eq(s.pending!.options.length,2,"white permits tied weakest targets");s=pick(s,["p2"]);eq(s.seats[2].gold,48,"white target pays two");
for(const [id,amount] of [["red-2",1],["red-destroyer",10]] as const){s=play({play:id,hand:["white-8"],flights:[[],["gold-13"],["black-1"]],hands:[[],["blue-1","blue-4","blue-6"],["blue-2","blue-7","blue-9"]]});s=pick(s,["p1"]);eq(s.seats[1].gold,50-amount,`${id} strongest opponent pays`);check(s.seats[0].hand.includes("blue-1"),`${id} random transfer reaches own hand`);check(!JSON.stringify(projectPublic(s)).includes('"blue-1"'),`${id} random transfer not publicly revealed`);}
s=play({play:"white-hunter",hand:["white-8"],flights:[[],["black-1"],["gold-13"]]});eq(s.seats.map(p=>p.gold),[53,47,50],"white hunter takes from every weaker opponent");
for(const [id,amount] of [["bahamut",10],["queen",5]] as const){s=play({play:id,hand:["white-8"],flights:[[],["gold-2","red-2"],["blue-1"]],hands:[[],["blue-2","blue-4","blue-6"],["white-1","white-2","white-3"]]});eq(s.seats[1].gold,50-amount,`${id} mixed alignment collection`);}
s=play({play:"tiamat",hand:["white-8"]});check(!s.effects.length,"Tiamat has no triggered power");
s=play({play:"archmage",hand:["white-8"]});check(s.seats[0].archmage,"archmage enables later powers");
s=play({play:"dracolich",hand:["white-8"],flights:[["black-1"],[],[]]});eq(flightStrength(s,0),11,"dracolich no mid-round strength bonus");eq(flightStrength(s,0,true),15,"dracolich scoring includes itself and evil dragons");
s=play({play:"dragonrider",hand:["white-8"],flights:[["red-2","blue-11"],[],[]]});eq(flightStrength(s,0),19,"dragonrider printed value during round");eq(flightStrength(s,0,true),15,"dragonrider changes at scoring");
s=play({play:"dragonslayer",hand:["white-8"],flights:[["black-1"],["gold-13"],[]]});s=pick(s,["black-1"]);check(!s.seats[0].flight.some(f=>f.cardId==="black-1"),"slayer must remove own weak dragon when no enemy eligible");
s=play({play:"druid",hand:["white-8"]});check(s.effects.some(e=>e.kind==="druid"),"druid reversal recorded");
s=play({play:"fool",hand:["white-8"],flights:[[],["gold-13"],["black-9"]]});eq(s.seats[0].hand.length,3,"fool counts stronger opponents");
s=play({play:"kobold",hand:["white-8","gold-13"],deck:["black-1","blue-1"]});s=pick(s,["white-8","gold-13"]);eq(s.seats[0].hand,["black-1","blue-1"],"kobold discards complete selection then redraws");
s=play({play:"merchant-prince",hand:["white-8"]});check(s.effects.some(e=>e.kind==="merchant"),"merchant buy redirection recorded");
s=play({play:"priest",hand:["white-8"]});check(s.effects.some(e=>e.kind==="priest"),"priest split recorded");
s=play({play:"princess",hand:["white-8"],flights:[["gold-2","brass-1"],[],[]]});s=pick(s,["brass-1"]);s=pick(s,["pay"]);s=pick(s,["gold-2"]);eq(s.seats[0].gold,55,"princess triggers chosen good powers in player order");
s=play({play:"prophet",hand:["black-1","white-8"]});s=pick(s,["black-1"]);eq(s.stakes,77,"prophet copies dragon power");check(s.seats[0].hand.includes("black-1")&&s.seats[0].flight[0].cardId==="prophet","prophet reveals without playing held dragon");
s=play({play:"illusionist",hand:["white-8"],flights:[[],["archmage"],[]]});s.seats[1].archmage=true;s=pick(s,["archmage"]);check(s.seats[0].archmage&&s.seats[1].archmage,"illusionist shares archmage without cancelling original effect");
s=play({play:"sorcerer",hand:["white-8"],deck:["black-1","blue-1","gold-13"]});check(projectPublic(s).revealed.length===3,"sorcerer reveals three publicly");s=pick(s,["black-1"]);eq(s.roundCards[0],"black-1","sorcerer replacement is turn's played card");eq(s.ante,["blue-1","gold-13"],"other sorcerer cards enter ante");
s=play({play:"thief",hand:["white-8"]});eq(s.stakes,73,"thief steals seven");
s=play({play:"wyrmpriest",hand:["white-8"],flights:[["green-2","green-5"],[],[]]});eq(s.seats[0].gold,60,"wild color flight pays middle strength five");check(s.seats[0].flight.find(f=>f.cardId==="wyrmpriest")?.wild,"wyrmpriest persistent wildcard");

// The complete inventory reaches its handler, including every standard strength.
for(const c of CARDS){check(!!CARD_HINTS[c.family]?.every(Boolean),`${c.family} has bilingual hint`);check(cardName(c.id,"zh")!==cardName(c.id,"en"),`${c.family} has Chinese name`);s=play({play:c.id,hand:[c.id==="white-8"?"white-6":"white-8"]});s=resolve(s);check(s.events.some(e=>e.code==="POWER_TRIGGERED"&&e.cardIds?.includes(c.id)),`inventory card ${c.id} triggers its family handler`);}

// Triggering, leader ties, debt, flight bonuses and forced purchases.
s=fixture({play:"gold-13",hand:["white-8"],active:2,turnIndex:2,flights:[["bahamut"],["black-7"],[]]});s.roundCards=["bahamut","black-7",null];s=act(s,2,"play",{cardId:"gold-13"});eq(s.leader,1,"round leader ignores stronger tied cards");
s=fixture({play:"white-1",hand:["white-8"],active:2,turnIndex:2,flights:[["black-1"],["blue-1"],[]]});s.roundCards=["black-1","blue-1",null];s=resolve(act(s,2,"play",{cardId:"white-1"}));eq(s.leader,0,"all round cards tied preserves leader");
s=fixture({play:"gold-13",hand:["white-8"],active:1,turnIndex:1,flights:[["black-1"],[],[]],previous:"black-1"});s=act(s,1,"play",{cardId:"gold-13"});check(!s.events.some(e=>e.code==="POWER_TRIGGERED"&&e.cardIds?.includes("gold-13")),"higher non-leading card has no power");
s=fixture({play:"gold-13",hand:["white-8"],active:1,turnIndex:1,flights:[["black-1"],[],[]],previous:"black-1"});s.seats[1].archmage=true;s=act(s,1,"play",{cardId:"gold-13"});check(s.events.some(e=>e.code==="POWER_TRIGGERED"&&e.cardIds?.includes("gold-13")),"archmage overrides normal threshold");
s=play({play:"green-1",hand:["white-8"],gold:2});s=pick(s,["pay"]);eq(s.seats[1].debt,3,"insufficient payment records unpaid amount");eq(s.seats[0].gold,4,"recipient receives real gold only");
s=fixture({play:"gold-13",hand:["white-8"],round:3,active:2,turnIndex:2,flights:[["black-1"],["blue-1"],[]]});s.seats[0].gold=2;s.seats[0].debt=5;s.roundCards=["black-1","blue-1",null];s=act(s,2,"play",{cardId:"gold-13"});eq(s.stage,"ended","unpayable hole ends game after scoring");eq(s.winners,["p2"],"highest hoard wins after debt payment");eq(s.hole,0,"winner receives accumulated hole");
s=fixture({play:"gold-13",hand:["white-8"],round:3,active:2,turnIndex:2,stakes:9,flights:[["black-1"],["blue-1"],[]]});s.effects=[{kind:"priest",seat:0,source:"priest"}];s.roundCards=["black-1","blue-1",null];s=act(s,2,"play",{cardId:"gold-13"});eq(s.seats.map(p=>p.gold),[54,50,55],"priest odd stakes favor actual winner; left neighbor receives remainder");
s=fixture({play:"gold-13",hand:["white-8"],round:3,active:2,turnIndex:2,flights:[["black-1"],["blue-2"],[]]});s.effects=[{kind:"druid",seat:0,source:"druid"}];s.roundCards=["black-1","blue-2",null];s=act(s,2,"play",{cardId:"gold-13"});eq(s.lastGambit?.winners,["p0"],"druid weakest flight wins");
s=fixture({play:"gold-13",hand:["white-8"],round:3,active:2,turnIndex:2,flights:[["black-1"],["blue-2"],[]]});s.effects=[{kind:"warlord",seat:0,source:"bronze-warlord"}];s.roundCards=["black-1","blue-2",null];s=act(s,2,"play",{cardId:"gold-13"});eq(s.round,4,"losing warlord forces fourth round");
s=fixture({play:"gold-13",hand:["white-8"],round:3,active:2,turnIndex:2,flights:[["black-1"],["blue-2"],[]]});s.effects=[{kind:"monarch",seat:2,source:"gold-monarch"}];s.roundCards=["black-1","blue-2",null];s=act(s,2,"play",{cardId:"gold-13"});eq(s.seats.map(p=>p.gold),[53,53,124],"winning monarch gives gifts before end check");
s=fixture({play:"gold-13",hand:["white-8"],round:3,active:2,turnIndex:2,flights:[["bahamut","black-9"],["blue-2"],[]]});s.roundCards=["black-9","blue-2",null];s=act(s,2,"play",{cardId:"gold-13"});eq(s.lastGambit?.winners,["p2"],"Bahamut mixed alignment cannot win despite highest total");
s=fixture({play:"gold-13",hand:["white-8"],round:3,active:2,turnIndex:2,flights:[["tiamat","silver-12"],["blue-2"],[]]});s.roundCards=["silver-12","blue-2",null];s=act(s,2,"play",{cardId:"gold-13"});eq(s.lastGambit?.winners,["p2"],"Tiamat mixed alignment cannot win");
s=play({play:"black-1",hand:["white-8"],stakes:3,flights:[[],["gold-13"],[]]});check(s.lastGambit?.reason==="empty-stakes"&&s.round===0,"empty stakes ends immediately before further turns");
s=fixture({play:"gold-13",hand:["white-8"],round:3,active:2,turnIndex:2,flights:[["dragonrider","red-2","blue-2"],["black-7"],[]],ante:["gold-2","gold-4"]});s.seats[0].flight[0].rider=true;s.roundCards=["blue-2","black-7",null];s=act(s,2,"play",{cardId:"gold-13"});check(s.seats[0].rewards.includes("strength:2")&&s.pending?.code==="STRENGTH_FLIGHT_ANTE","dragonrider creates strength flight at scoring");s=resolve(s);eq(s.lastGambit?.winners,["p2"],"scoring continues after rider bonus choices");
s=play({play:"priest",hand:["white-8"],stakes:5,flights:[["wyrmpriest","merchant-prince"],[],[]]});eq(s.seats[0].gold,65,"simultaneous mortal color reward resolves before strength drains stakes");
s=fixture({play:"green-8",hand:["white-8"],flights:[["green-1","green-2","green-5"],[],[]]});s.seats[0].rewards=["color:green"];s=resolve(act(s,0,"play",{cardId:"green-8"}));eq(s.seats[0].gold,55,"fourth color card does not repay completed flight");
s=play({play:"tiamat",hand:["white-8"],flights:[["black-1","black-5"],[],[]]});eq(s.seats[0].gold,60,"Tiamat uses evil color without triggering power");
s=play({play:"prophet",hand:["green-1","white-8"],hands:[[],["blue-9","blue-11","blue-7"],[]]});s=pick(s,["green-1"]);check(s.pending!.options.some(o=>o.cardId==="blue-9")&&!s.pending!.options.some(o=>o.cardId==="blue-11"),"copied comparison uses Prophet strength, not revealed dragon strength");s=pick(s,["blue-9"]);
// Buying is automatic at one card at turn start and zero only after powers/bonuses.
s=fixture({play:"black-1",hand:["white-8"],hands:[[],["gold-13"],[]],deck:["blue-4","blue-6","blue-7","blue-9"]});s=act(s,0,"play",{cardId:"black-1"});eq(s.seats[1].hand.length,4,"one card at next turn buys to four");eq(s.seats[1].gold,46,"buy price is revealed top card strength");
s=fixture({play:"black-1",hand:["white-8"],hands:[[],["gold-13"],[]],deck:["blue-4","blue-6","blue-7","blue-9"]});s.effects=[{kind:"merchant",seat:2,source:"merchant-prince"}];s=act(s,0,"play",{cardId:"black-1"});eq(s.seats[2].gold,54,"merchant intercepts forced purchase");eq(s.stakes,77,"intercepted buying does not increase stakes");
s=play({play:"chromatic-wyrmling",hand:["red-2"],flights:[[],["gold-13"],[]],hands:[[],["blue-1","blue-2","blue-4"],[]]});s=pick(s,["red-2"]);s=pick(s,["p1"]);check(s.seats[0].hand.length===1&&!s.events.some(e=>e.code==="BUY_PRICE"&&e.seatId==="p0"),"replacement power can rescue empty hand before forced buying");
// Nine-card Bronze selects two then chooses which to keep, rather than blindly lowest.
const eight=["gold-2","gold-4","gold-6","gold-8","gold-9","gold-11","gold-13","white-8"];
s=play({play:"bronze-7",hand:[...eight,"white-6"],ante:["black-1","blue-2","red-12"]});s=pick(s,["black-1"]);s=pick(s,["blue-2"]);eq(s.pending?.code,"KEEP_ONE_ANTE_CARD","Bronze at nine allows either of two weakest");s=pick(s,["blue-2"]);check(s.seats[0].hand.includes("blue-2")&&s.ante.includes("black-1"),"unselected weak ante returned");
s=fixture({play:"gold-2",hand:eight.filter(id=>id!=="gold-2").concat(["white-6","white-5"]),flights:[["silver-2"],[],[]]});s=act(s,0,"play",{cardId:"gold-2"});eq(s.seats[0].hand.length,10,"draw powers stop at ten");
s=fixture({play:"gold-2",hand:["white-8"]});s.deck=[];s.discard=["gold-13"];s=act(s,0,"play",{cardId:"gold-2"});check(s.seats[0].hand.includes("gold-13")&&s.events.some(e=>e.code==="DECK_RESHUFFLED"),"empty deck reshuffles discard");
s=fixture({play:"gold-2",hand:["white-8"]});s.deck=[];s.discard=[];s=act(s,0,"play",{cardId:"gold-2"});eq(s.issue,"RULE_DECK_AND_DISCARD_EMPTY","truly exhausted deck is explicit adjudication, never fabricated cards");
s=fixture({play:"gold-2",hand:["white-8"],deck:["gold-13","black-9"]});s.deck=["gold-13"];s.discard=["black-9"];s=act(s,0,"play",{cardId:"gold-2"});eq(s.deck,["black-9"],"last draw immediately prepares existing discard as next deck");eq(s.discard,[],"future discards cannot enter an already prepared deck");
s=fixture({play:"copper-1",hand:["white-8"],deck:["black-1","gold-13"]});s.deck=["black-1"];s.discard=["gold-13"];s=act(s,0,"play",{cardId:"copper-1"});check(s.deck.includes("copper-1")&&s.deck.includes("gold-13")&&!s.discard.length,"Copper discards before taking the last deck card and immediate reshuffle");
s=fixture({play:"copper-1",hand:["white-8"],deck:["black-1"]});s.deck=[];s.discard=["black-1"];const copperReshuffle=applyAction(s,{id:"copper-reshuffle",revision:s.revision,seatId:"p0",kind:"play",cardId:"copper-1"},{int:upper=>upper-1});check(copperReshuffle.ok,"Copper exhaustion action succeeds");if(copperReshuffle.ok){s=copperReshuffle.state;eq(s.seats[0].flight[0].cardId,"black-1","Copper shuffled replacement is drawn");eq(s.deck,["copper-1"],"Copper itself joined the exhausted-deck reshuffle");eq(checkInvariants(s),[],"Copper reshuffle preserves physical identity");}
s=fixture({play:"copper-trickster",hand:["white-8"],flights:[["black-9"],[],[]],deck:["gold-13"]});s.deck=[];s.discard=["gold-13"];s=act(s,0,"play",{cardId:"copper-trickster"});s=pick(s,["black-9"]);eq(s.pending?.task.source,"black-9","Trickster discarded target can be redrawn from exhaustion reshuffle");eq(s.deck,["gold-13"],"Trickster old card joined reshuffle before top draw");s=pick(s,["skip"]);
const pass=applyAction(game(),{id:"pass",revision:0,seatId:"p0",kind:"pass" as any});check(!pass.ok&&pass.error.code==="INVALID_ACTION","no invented general pass action");
for(const id of ["kobold","prophet","chromatic-wyrmling","metallic-wyrmling","illusionist"]){s=play({play:id,hand:["black-1","gold-13"],flights:[[],["druid"],[]]});if(s.pending)s=pick(s,s.pending.min===0?[]:["skip"]);check(s.stage==="play"&&s.active===1,`${id} declining optional action still advances turn`);}

// Remaining continuation branches and repeated delayed powers.
s=play({play:"copper-trickster",hand:["white-8"],flights:[["black-9"],[],[]],deck:["black-1"]});s=pick(s,["black-9"]);s=pick(s,["trigger"]);eq(s.stakes,77,"trickster optional trigger branch");
s=fixture({play:"copper-trickster",hand:["white-8"],flights:[["black-9"],[],[]],deck:["black-1"]});s.seats[0].archmage=true;s=act(s,0,"play",{cardId:"copper-trickster"});s=pick(s,["black-9"]);check(!s.pending&&s.stakes===77,"archmage forces trickster replacement trigger");
s=play({play:"prophet",hand:["copper-1","white-8"],deck:["black-1"]});s=pick(s,["copper-1"]);eq(s.seats[0].flight[0].cardId,"black-1","copied copper replaces Prophet, not held dragon");check(s.seats[0].hand.includes("copper-1"),"copied copper remains held");
s=play({play:"prophet",hand:["tiamat","white-8"],flights:[["gold-13"],[],[]]});s=pick(s,["tiamat"]);check(s.seats[0].flight.every(f=>f.cardId!=="tiamat")&&!s.effects.length,"Prophet cannot copy dragon god abilities");
s=play({play:"sorcerer",hand:["white-8"],deck:["copper-1","blue-1","gold-13","black-1"]});s=pick(s,["copper-1"]);eq(s.roundCards[0],"black-1","Sorcerer into Copper resolves nested replacements");
s=play({play:"sorcerer",hand:["white-8"],ante:["red-12","silver-12","gold-13"],deck:["bronze-1","black-1","blue-1"]});s=pick(s,["bronze-1"]);eq(s.pending?.options.map(o=>o.id),["red-12","silver-12"],"Sorcerer replacement power only sees preexisting ante");eq(s.revealed,["black-1","blue-1"],"Sorcerer leftovers stay public while replacement resolves");s=pick(s,["red-12"]);s=pick(s,["silver-12"]);eq(s.ante,["gold-13","black-1","blue-1"],"Sorcerer leftovers enter ante only after full Bronze continuation");eq(s.revealed,[],"resolved Sorcerer clears reserved reveal");
s=play({play:"sorcerer",hand:["white-8"],stakes:3,deck:["black-1","blue-1","gold-13"]});s=pick(s,["black-1"]);check(s.lastGambit?.reason==="empty-stakes","Sorcerer replacement can immediately end gambit");check(s.discard.includes("blue-1")&&s.discard.includes("gold-13"),"immediate end discards reserved Sorcerer leftovers");
s=fixture({play:"illusionist",hand:["white-8"],flights:[[],["merchant-prince"],[]]});s.effects=[{kind:"merchant",seat:1,source:"merchant-prince"}];s=act(s,0,"play",{cardId:"illusionist"});s=pick(s,["merchant-prince"]);eq(s.effects.filter(e=>e.kind==="merchant").map(e=>e.seat),[0],"Merchant beneficiary transfers with Illusionist");
s=fixture({play:"princess",hand:["white-8"],round:3,active:2,turnIndex:2,flights:[["black-1"],["blue-4"],["gold-monarch","gold-13"]]});s.effects=[{kind:"monarch",seat:2,source:"gold-monarch"}];s.roundCards=["black-1","blue-4",null];s=act(s,2,"play",{cardId:"princess"});s=pick(s,["gold-monarch"]);s=pick(s,["gold-13"]);eq(s.seats.map(p=>p.gold),[56,56,118],"Princess retriggering Monarch schedules another gift");

// Explicit unresolved cases remain visible, without silently inventing rules.
s=play({play:"black-1",hand:["white-8"],stakes:3,flights:[[],["blue-1"],[]]});eq(s.issue,"RULE_EMPTY_STAKES_TIE","empty stakes tied winner needs adjudication");eq(eligibleActions(s,"p0"),[],"adjudication does not offer fake legal plays");
s=fixture({play:"gold-13",hand:["white-8"],n:2,round:3,active:1,turnIndex:1,flights:[["bahamut","black-9"],["tiamat"]]});s.roundCards=["black-9",null];s=act(s,1,"play",{cardId:"gold-13"});eq(s.issue,"RULE_NO_ELIGIBLE_GAMBIT_WINNER","both god restrictions cannot select invented winner");
s=fixture({play:"gold-13",hand:["white-8"],round:3,active:2,turnIndex:2,stakes:10,flights:[["black-1"],["blue-2"],[]]});s.roundCards=["black-1","blue-2",null];s.seats[0].gold=1;s.seats[0].debt=1;s.seats[1].gold=60;s=act(s,2,"play",{cardId:"gold-13"});eq(s.issue,"RULE_TIED_WINNERS_ODD_HOLE_COIN","tie's remaining hole coin is table agreement");eq(s.winners,["p1","p2"],"tied victory recorded before coin agreement");eq(s.hole,1,"remaining coin not lost");
s=fixture({play:"copper-1",hand:["white-8"],deck:["copper-3"]});s.deck=["copper-3"];s=act(s,0,"play",{cardId:"copper-1"});eq(s.issue,"RULE_UNBOUNDED_EFFECT_CHAIN","pathological Copper-only shuffle cannot lock host");
s=play({play:"silver-seer",hand:[...eight,"white-6"],deck:["black-1","black-2","black-3","black-5"]});eq(s.pending?.code,"SEER_HAND_FULL_KEEP_TOP","full-hand Seer explains retained top card");const kept=s.pending!.options[0].id;s=pick(s,[kept]);check(s.seats[0].hand.length===10&&s.deck[0]===kept,"full hand skips Seer taking, keeps chosen top card");
// Returned public data cannot mutate authority, and effect targets enforce seat.
s=play({play:"green-5",hand:["white-8"]});const badChoice=applyAction(s,{id:"other-choose",revision:s.revision,seatId:"p0",kind:"choose",choiceId:s.pending!.id,optionIds:["pay"]});check(!badChoice.ok&&badChoice.error.code==="NOT_YOUR_TURN","only demanded player makes private hand/payment choice");const view=projectSeat(s,"p0");view.hand.length=0;view.events.length=0;check(s.seats[0].hand.length>0&&s.events.length>0,"projection is detached from authority");
const invented=applyAction(s,{id:"invented",revision:s.revision,seatId:s.pending!.seatId,kind:"choose",choiceId:s.pending!.id,optionIds:["gold-13"]});check(!invented.ok&&invented.error.code==="INVALID_CHOICE","unoffered cards cannot be submitted");

// Autonomous games exercise real ante/round/choice/settlement progression.
const completed:Record<number,number>={2:0,6:0};const issues=new Map<string,number>();
for(const n of [2,6])for(let seed=1;seed<=12;seed++){
 let g=game(n,seed);let steps=0;
 while(g.stage!=="ended"&&g.stage!=="adjudication"&&steps++<3000){
  const index=g.pending?g.seats.findIndex(p=>p.id===g.pending!.seatId):g.stage==="ante"?g.seats.findIndex(p=>!Object.prototype.hasOwnProperty.call(g.committed,p.id)):g.active;
  const legal=eligibleActions(g,g.seats[index].id)[0];check(!!legal,"live game always has a legal action");
  if(legal.kind==="choose")g=pick(g,legal.choice.min===0?[]:[legal.choice.options[(seed+steps)%legal.choice.options.length].id]);
  else g=act(g,index,legal.kind,{cardId:legal.cardIds[(seed+steps)%legal.cardIds.length]});
  const reserved=(g.pending&&["seer-keep","sorcerer"].includes(g.pending.task.kind)?g.pending.task.ids!.length:0)+g.queue.filter(t=>t.kind==="sorcerer-ante").reduce((sum,t)=>sum+t.ids!.length,0);
  eq(g.deck.length+g.discard.length+g.ante.length+Object.keys(g.committed).length+g.seats.reduce((sum,p)=>sum+p.hand.length+p.flight.length,0)+reserved,80,"full game conserves all 80 cards");
  eq(g.stakes+g.hole+g.seats.reduce((sum,p)=>sum+p.gold,0),n*n*10,"full game conserves physical gold including hole");
 }
 check(steps<3000,`${n} player simulation makes progress`);
 if(g.stage==="ended"){completed[n]++;check(g.winners.length>0&&g.seats.some(p=>p.gold===0),"real game end with winner and bankrupt player");}
 else issues.set(g.issue??"unknown",(issues.get(g.issue??"unknown")??0)+1);
}
check(completed[2]>=8&&completed[6]>=8,"multiple complete 2- and 6-player games");
console.log(`Three-dragon rules: ${assertions} assertions passed; complete games ${JSON.stringify(completed)}; explicit unresolved-rule cases ${JSON.stringify([...issues])}`);
