import assert from 'node:assert/strict';
import {writeFileSync} from 'node:fs';
import {workbenchObservation} from '../src/workbench/observation';
import {createGroupRolls} from '../src/workbench/group-rolls';
const checks:{name:string;passed:boolean;error?:string}[]=[];
const check=(name:string,run:()=>void)=>{try{run();checks.push({name,passed:true});}catch(error){checks.push({name,passed:false,error:String(error)});}};
const sdk=(globalThis as any).selectionSdk;
const observed=workbenchObservation();await observed.read();let events:any[]=[];observed.onChange(change=>events.push(change));
const other={id:'other',connectionId:'other-connection',name:'Player',role:'PLAYER',color:'#555555',metadata:{},selection:[],syncView:false};
sdk.emit('party',[other]);await Promise.resolve();events=[];const version=observed.version();
for(let n=0;n<20;n++)sdk.emit('party',[{...other,selection:['token-'+n],syncView:!!(n%2)}]);
check('other players selecting or changing their viewport do not rebuild the card catalog',()=>{assert.equal(observed.version(),version);assert.equal(events.length,0);});
sdk.emit('party',[{...other,role:'GM'}]);check('party permission changes still invalidate immediately',()=>assert.equal(events.at(-1),'data'));
events=[];sdk.emit('player',{...sdk.player,selection:['token-a']});check('own map selection retains its independent event',()=>assert.deepEqual(events,['selection']));

let selection=Array.from({length:20},(_,n)=>'unit-'+n),listener=()=>{},resolves:(()=>void)[]=[],calls=0;
const target=(id:string)=>({key:'card:'+id,item:{id,name:id,metadata:{}},document:{abilities:Object.fromEntries(['str','dex','con','int','wis','cha'].map(key=>[key,{total:12,modifier:1,save:{bonus:3}}]))}});
const observation:any={sceneEpoch:()=>1,read:async()=>({ready:true,role:'GM',selection,scene:{}}),onChange:(fn:()=>void)=>{listener=fn;return()=>{};}};
const sent:any[]=[];
const groups=createGroupRolls({observation,send:(_type,payload)=>sent.push(payload),resolveTarget:id=>{calls++;return new Promise(resolve=>resolves.push(()=>resolve(target(id))));},applyDelta:async()=>{}});
await new Promise(r=>setTimeout(r,0));
check('multiselection opens its group immediately while target documents are still loading',()=>{assert.equal(groups.snapshot()?.selectedCount,20);assert.equal(groups.snapshot()?.phase,'select');assert.equal((groups.snapshot() as any)?.loading,true);});
check('cold multiselection bounds concurrent document reads',()=>assert.ok(calls<=4,`started ${calls} reads`));
const groupId=groups.snapshot()?.id;
if(groupId)check('pending group cannot mutate targets before its data is ready',()=>assert.equal((groups.snapshot() as any).loading,true));
selection=[];listener();await new Promise(r=>setTimeout(r,0));
check('clearing selection closes a pending group without waiting for slow documents',()=>assert.equal(groups.snapshot(),null));
for(const resolve of resolves)resolve();await new Promise(r=>setTimeout(r,0));
check('old reads cannot recreate the cleared group or start further old downloads',()=>{assert.equal(groups.snapshot(),null);assert.ok(calls<=4);});groups.dispose();
writeFileSync(process.env.SELECTION_REPORT!,JSON.stringify({realRoomVerified:false,checks},null,2));
for(const row of checks)console.log(`${row.passed?'PASS':'FAIL'} ${row.name}${row.error?' '+row.error:''}`);
if(checks.some(row=>!row.passed))process.exitCode=1;
