import assert from 'node:assert/strict';
import {evaluateFormula,parseFormula} from '../extensions/workbench-dice3d/src/research/formula';
import {recoverPlaybackStart} from '../extensions/workbench-dice3d/src/playback-clock';
import {BUILD,now} from '../extensions/workbench-dice3d/src/types';
import {Controller} from '../extensions/workbench-dice3d/src/controller';
import {validateRecipe} from '../extensions/workbench-dice3d/src/suite-formula';
import {splitGroupRoll} from '../extensions/workbench-dice3d/src/group-batch';
import {sizeOf,MAX_MESSAGE_BYTES} from '../extensions/workbench-dice3d/src/wire.mjs';
import {createGroupRolls} from '../src/workbench/group-rolls';
let checks=0;const pass=(name:string)=>{checks++;console.log('PASS '+name);};
const waves:any[]=[];let n=0;
const rows=await evaluateFormula(['1d20+2','adv(1d20)+4','1d20-1'].map(parseFormula),async groups=>{waves.push(groups);return groups.map(g=>Array.from({length:g.count},()=>({id:'die-'+n++,value:n+1})));});
assert.equal(waves.length,1);assert.equal(waves[0].reduce((n:number,g:any)=>n+g.count,0),4);assert.equal(rows.length,3);pass('different target formulas share one physical frontier');
assert.equal(recoverPlaybackStart(1000,1100,6100),5900);assert.equal(recoverPlaybackStart(9000,1100,6100),9000);assert.equal(recoverPlaybackStart(1000,1100,1116),1000);pass('long rAF gap preserves unplayed animation and future barriers');
let preparing=false,scene=1,selection=['one','two'],changed:()=>void=()=>{},sent:any[]=[],calls:any[]=[],uncertain=false;
const observation:any={sceneEpoch:()=>scene,read:async()=>({ready:true,role:'GM',selection,scene:{'com.initiative-tracker/combat':{preparing}}}),onChange:(fn:()=>void)=>{changed=fn;return()=>{};}};
const target=(id:string)=>({key:'card:'+id,item:{id,name:id,metadata:{}},document:{abilities:Object.fromEntries(['str','dex','con','int','wis','cha'].map(key=>[key,{total:12,modifier:1,save:{bonus:3}}]))}});
const group=createGroupRolls({observation,send:(_type,data)=>sent.push(data),resolveTarget:async id=>target(id),applyDelta:async(id,change)=>{calls.push({id,change});if(uncertain)throw Object.assign(Error('connection lost'),{uncertain:true});}});
const flush=async()=>{await new Promise(resolve=>setTimeout(resolve,0));};await flush();assert.equal(group.snapshot()?.phase,'select');pass('DM multiselection creates group');
let id=group.snapshot()!.id;await group.handle({id,action:'roll',kind:'save',ability:'dex',variant:'normal'});assert.equal(group.snapshot()?.phase,'resolve');selection=[];changed();await flush();assert.equal(group.snapshot()?.id,id);assert.equal(group.snapshot()?.phase,'resolve');pass('DC state survives selection clear');
await group.handle({id,action:'visibility',visible:false});assert.equal(group.snapshot()?.visible,false);await group.handle({id,action:'visibility',visible:true});assert.equal(group.snapshot()?.visible,true);pass('visibility changes do not close the group');
await group.handle({id,action:'settle',dc:10,value:9,mode:'damage'});assert.equal(group.snapshot()?.phase,'settled');assert.equal(calls.length,2);assert.deepEqual(calls.map(c=>c.change.value),[9,4]);await group.handle({id,action:'settle',dc:10,value:9,mode:'damage'});assert.equal(calls.length,2);pass('settlement keeps results and cannot repeat successful deltas');
await group.handle({id,action:'close'});assert.equal(group.snapshot(),null);pass('close removes group');
selection=['one','two'];changed();await flush();id=group.snapshot()!.id;await group.handle({id,action:'close'});changed();await flush();await group.refreshSelection();assert.equal(group.snapshot(),null);pass('closed group stays absent while selection is unchanged');
selection=['one'];changed();await flush();assert.equal(group.snapshot(),null);selection=['one','two'];changed();await flush();assert.ok(group.snapshot());assert.notEqual(group.snapshot()!.id,id);await group.handle({id:group.snapshot()!.id,action:'close'});pass('selection change permits the same closed group to open again');
selection=['three','four'];changed();await flush();id=group.snapshot()!.id;await group.handle({id,action:'roll',kind:'save',ability:'dex',variant:'normal'});uncertain=true;await group.handle({id,action:'settle',dc:10,value:9,mode:'damage'});const before=calls.length;await assert.rejects(()=>group.handle({id,action:'settle',dc:10,value:9,mode:'damage'}),/不确定/);assert.equal(calls.length,before);pass('uncertain receipt cannot reapply damage');
scene++;changed();await flush();assert.notEqual(group.snapshot()?.id,id);pass('scene change discards locked result');
group.dispose();
// A late completion belongs to its own group, never to its successor.
(globalThis as any).pendingRolls=[];selection=['five','six'];uncertain=false;
const races=createGroupRolls({observation,send:()=>{},resolveTarget:async id=>target(id),applyDelta:async()=>{}});await flush();const old=races.snapshot()!.id,first=races.handle({id:old,action:'roll',kind:'save',ability:'dex',variant:'normal'});await flush();await races.handle({id:old,action:'close'});selection=['seven','eight'];changed();await flush();const next=races.snapshot()!.id;
await assert.rejects(()=>races.handle({id:old,action:'close'}),/已改变/);assert.equal(races.snapshot()?.id,next);pass('late close cannot dismiss a different group');
const second=races.handle({id:next,action:'roll',kind:'save',ability:'dex',variant:'normal'});await flush();(globalThis as any).pendingRolls[0]();await first;await assert.rejects(()=>races.handle({id:next,action:'roll',kind:'save',ability:'dex',variant:'normal'}),/正在进行/);(globalThis as any).pendingRolls[1]();await second;races.dispose();pass('old roll completion cannot unlock a new in-flight group');
delete (globalThis as any).pendingRolls;
for(const [count,variant]of [[100,'normal'],[50,'adv'],[50,'dis']] as const){
 selection=Array.from({length:count},(_,i)=>'budget-'+variant+'-'+i);const bounded=createGroupRolls({observation,send:()=>{},resolveTarget:async id=>target(id),applyDelta:async()=>{throw Error('roll cannot write stats');}});await flush();const id=bounded.snapshot()!.id;await bounded.handle({id,action:'roll',kind:'save',ability:'dex',variant});assert.equal(bounded.snapshot()?.phase,'resolve');assert.equal(bounded.snapshot()?.targets.length,count);bounded.dispose();
 const formulas=Array.from({length:count},()=>variant==='normal'?'1d20':variant+'(1d20)'),frontiers:any[]=[];validateRecipe({recipe:true,formulas,contexts:formulas.map(()=>({visibility:'all'}))} as any);await evaluateFormula(formulas.map(parseFormula),async groups=>{frontiers.push(groups);return groups.map((g,groupIndex)=>Array.from({length:g.count},(_,i)=>({id:'budget-'+groupIndex+'-'+i,value:10})));});assert.equal(frontiers.length,1);assert.equal(frontiers[0].reduce((n:number,g:any)=>n+g.count,0),100);pass(count+' '+variant+' targets accepted in one 100-die physical frontier (not a GPU performance claim)');
}
for(const [count,variant]of [[101,'normal'],[51,'adv'],[51,'dis']] as const){
 selection=Array.from({length:count},(_,i)=>'over-'+variant+'-'+i);let resolved=0;const bounded=createGroupRolls({observation,send:()=>{},resolveTarget:async id=>{resolved++;return target(id);},applyDelta:async()=>{throw Error('rejected roll cannot write stats');}});await flush();const before=bounded.snapshot(),reads=resolved,submissions=(globalThis as any).groupSubmissions??0;await assert.rejects(()=>bounded.handle({id:before!.id,action:'roll',kind:'save',ability:'dex',variant}),/100 枚实体骰/);assert.deepEqual(bounded.snapshot(),before);assert.equal(resolved,reads);assert.equal((globalThis as any).groupSubmissions??0,submissions);if(count===101)assert.equal(resolved,0);bounded.dispose();pass(count+' '+variant+' targets rejected before state mutation or engine submission');
}
const masterId='00000000-0000-4000-8000-000000000000-'+Date.now(),barrier:any=Object.create(Controller.prototype),groupPackets:any[]=[],localStarts:any[]=[];
barrier.reservations=new Map([[masterId,{request:{id:masterId,source:'source',groupSize:100},broker:'broker',members:['viewer']}]]);barrier.authority=()=> 'broker';barrier.outgoing=new Map();barrier.peers=new Map();barrier.settledAt=new Map();barrier.transport={id:'source'};barrier.bus={postMessage:(m:any)=>localStarts.push(m)};barrier.send=async(m:any)=>groupPackets.push(m);barrier.retainUntilExit=()=>{};barrier.finishReservation=()=>{};barrier.next=()=>{};barrier.log=()=>{};
const descriptors=Array.from({length:100},(_,index)=>({id:masterId+'.g'+index,count:1,visibility:index%2?'gm':'all'}));barrier.registerGroupParts(masterId,descriptors,'source');assert.equal(barrier.reservations.size,101);
for(const [index,part]of descriptors.entries())barrier.outgoing.set(part.id,{roll:{request:{id:part.id,visibility:part.visibility,batch:{id:masterId,index,size:100}}},wait:new Set(),members:['viewer'],started:false,hash:'f'.repeat(64)});
await barrier.maybeStart(barrier.outgoing.get(descriptors[0].id));assert.equal(localStarts.length,100);assert.equal(new Set(localStarts.map(m=>m.at)).size,1);assert.equal(groupPackets.length,1);assert.equal(groupPackets[0].type,'start-group');assert.ok(sizeOf({v:1,build:BUILD,from:'source',...groupPackets[0]})<=MAX_MESSAGE_BYTES);pass('100 mixed-visibility parts retain one shared start barrier within message size budget');
const badParts:any=Object.create(Controller.prototype);badParts.authority=()=> 'broker';for(const count of [101,51]){badParts.reservations=new Map([[masterId,{request:{id:masterId,source:'source',groupSize:count},broker:'broker'}]]);assert.throws(()=>badParts.registerGroupParts(masterId,Array.from({length:count},(_,i)=>({id:masterId+'.g'+i,count:count===51?2:1,visibility:i%2?'gm':'all'})),'source'),/非法/);assert.equal(badParts.reservations.size,1);}pass('protocol rejects over-budget group parts before adding any child reservation');
const synthetic:any={request:{id:masterId,seed:123456,groupSize:2},diagnostics:{simulationSeed:123456},frames:1,kinds:['d20','d20'],results:[4,19],poses:new Float32Array(14),contacts:[],formulaData:{ids:['a','b'],births:[0,0],contexts:[{visibility:'all'},{visibility:'gm'}],rows:[{dice:[{id:'a'}],formula:'1d20'},{dice:[{id:'b'}],formula:'1d20'}],timeline:{births:[0,0],clamps:[]}}};const sliced=splitGroupRoll(synthetic);assert.equal(sliced[0].request.seed,0);assert.equal(sliced[0].diagnostics,undefined);assert.deepEqual(sliced[0].results,[4]);assert.deepEqual(sliced[1].results,[19]);assert.equal(sliced[0].request.batch?.id,sliced[1].request.batch?.id);pass('public mixed sibling contains no master seed or hidden face; both keep the same batch');
const cancelled:any=Object.create(Controller.prototype),released:string[]=[],discarded:string[]=[];
for(const key of ['reservations','requests','privateAudiences','outgoing','inbound','rolls','records','secrets','started'])cancelled[key]=new Map();cancelled.privateRunning=new Set();cancelled.queue=[];cancelled.releasePhysics=(id:string)=>released.push(id);cancelled.bus={postMessage:(m:any)=>discarded.push(m.id)};cancelled.sendRecords=()=>{};cancelled.next=()=>{};
const master={id:'master',groupSize:3};cancelled.reservation={request:master};cancelled.reservations.set('master',{request:master});for(let i=0;i<3;i++){const request={id:'master.g'+i,batch:{id:'master',index:i,size:3}};cancelled.reservations.set(request.id,{request});cancelled.outgoing.set(request.id,{roll:{request},started:false});cancelled.inbound.set(request.id,{});}
cancelled.cancelSecret('master.g1');assert.equal(cancelled.reservation,undefined);assert.equal(cancelled.reservations.size,0);assert.equal(cancelled.outgoing.size,0);assert.equal(cancelled.inbound.size,0);assert.equal(released.length,4);assert.equal(discarded.length,4);pass('one aborted child releases the complete unstarted group barrier');
const fillBarrier=()=>{const at=now(),request={id:'master',groupSize:3,source:'source'};cancelled.reservation={request,at};cancelled.reservations.set('master',{request,broker:'broker',at});for(let i=0;i<3;i++){const request={id:'master.g'+i,source:'source',batch:{id:'master',index:i,size:3}};cancelled.reservations.set(request.id,{request,broker:'broker',at});cancelled.inbound.set(request.id,{source:'source',assembly:{bytes:1},at:at-(i?0:31000)});}};
for(const key of ['peers','probes','accepted'])cancelled[key]=new Map();cancelled.transport={id:'viewer'};cancelled.lastState=now();cancelled.state=()=>{};cancelled.fail=()=>{};cancelled.send=async()=>{};cancelled.bytesReceived=cancelled.packetsReceived=0;cancelled.peers.set('source',{lastSeen:now()});fillBarrier();await cancelled.tick();assert.equal(cancelled.reservations.size,0);assert.equal(cancelled.inbound.size,0);assert.equal(cancelled.reservation,undefined);pass('receive timeout immediately releases the whole group barrier');
fillBarrier();cancelled.inbound.clear();await cancelled.receive({v:1,build:BUILD,from:'attacker',type:'abort',id:'master.g1'},'attacker');assert.equal(cancelled.reservations.size,4);await cancelled.receive({v:1,build:BUILD,from:'source',type:'abort',id:'master.g1'},'source');assert.equal(cancelled.reservations.size,0);assert.equal(cancelled.reservation,undefined);pass('authorized late abort cleans leases after inbound disappeared; foreign abort is ignored');
delete (globalThis as any).pendingRolls;selection=['initiative-one','initiative-two'];const initiative=createGroupRolls({observation,send:()=>{},resolveTarget:async id=>target(id),applyDelta:async()=>{}});await flush();await initiative.handle({id:initiative.snapshot()!.id,action:'roll',kind:'initiative',ability:'dex',variant:'normal'});assert.equal(initiative.snapshot()?.phase,'settled');assert.deepEqual((globalThis as any).initiativeWrites.at(-1).map((i:any)=>i.metadata['com.initiative-tracker/data'].count),[5,15]);initiative.dispose();pass('group initiative uses the same batch and stores raw d20 once');
let bindingReads=0;const rebind=createGroupRolls({observation,send:()=>{},resolveTarget:async id=>{const value=target(id);if(++bindingReads>4)value.key='changed';return value;},applyDelta:async()=>{}});await flush();const written=(globalThis as any).initiativeWrites.length;await assert.rejects(()=>rebind.handle({id:rebind.snapshot()!.id,action:'roll',kind:'initiative',ability:'dex',variant:'normal'}),/关联已改变/);assert.equal((globalThis as any).initiativeWrites.length,written);assert.equal(rebind.snapshot()?.phase,'resolve');rebind.dispose();pass('rebinding before initiative write cannot mutate a replacement character');
selection=['field-one','field-two'];preparing=true;const edits:any[]=[],fields=createGroupRolls({observation,send:()=>{},resolveTarget:async id=>target(id),applyDelta:async(id,change)=>{edits.push({id,...change});}});await flush();assert.equal(fields.snapshot()?.kind,'initiative');preparing=false;changed();await flush();assert.equal(fields.snapshot()?.kind,'save');pass('combat preparation selects group initiative and returns to save before rolling');
const fieldId=fields.snapshot()!.id;for(const [field,mode,value]of [['health','heal',3],['health','heal',4],['max health','set',12],['armor class','damage',3]] as const){await fields.handle({id:fieldId,action:'adjust',field,mode,value});assert.equal(fields.snapshot()?.phase,'select');assert.deepEqual(edits.slice(-2).map(x=>[x.field,x.mode,x.value]),[[field,mode,value],[field,mode,value]]);}pass('pre-roll HP/Max HP/AC edits preserve repeated explicit adjustments without DC');
await fields.handle({id:fieldId,action:'roll',kind:'save',ability:'dex',variant:'normal'});await fields.handle({id:fieldId,action:'settle',field:'armor class',mode:'damage',value:9,dc:10});assert.deepEqual(edits.slice(-2).map(x=>[x.field,x.value]),[['armor class',9],['armor class',4]]);await assert.rejects(()=>fields.handle({id:fieldId,action:'settle',field:'max health',mode:'damage',value:9,dc:10}),/参数/);fields.dispose();pass('DC half-on-success applies to the selected field and retry cannot change fields');
selection=['mixed-monster','mixed-character'];const mixedCalls:any[]=[],mixed=createGroupRolls({observation,send:()=>{},resolveTarget:async id=>({...target(id),item:{...target(id).item,metadata:id==='mixed-character'?{'com.character-cards/boundCardId':'hero'}:{}}}),applyDelta:async(id,change)=>{mixedCalls.push({id,...change});}});await flush();const mixedId=mixed.snapshot()!.id;await assert.rejects(()=>mixed.handle({id:mixedId,action:'adjust',field:'armor class',mode:'set',value:16}),/调整值/);assert.equal(mixedCalls.length,0);assert.equal(mixed.snapshot()?.adjustment,undefined);await mixed.handle({id:mixedId,action:'adjust',field:'health',mode:'heal',value:1});assert.equal(mixedCalls.length,2);mixed.dispose();pass('mixed character/monster AC adjustment rejects every target before writing, and HP stays usable');
let rejectSecond=true;selection=['partial-one','partial-two'];const partialCalls:any[]=[],partial=createGroupRolls({observation,send:()=>{},resolveTarget:async id=>target(id),applyDelta:async(id,change)=>{partialCalls.push({id,...change});if(id==='partial-two'&&rejectSecond)throw Error('synthetic temporary write failure');}});await flush();const partialId=partial.snapshot()!.id;await partial.handle({id:partialId,action:'adjust',field:'max health',mode:'heal',value:5});assert.equal(partial.snapshot()?.adjustment?.pending,true);await assert.rejects(()=>partial.handle({id:partialId,action:'adjust',field:'armor class',mode:'heal',value:5}),/参数/);selection=['after-one','after-two'];changed();await flush();assert.equal(partial.snapshot()?.id,partialId);rejectSecond=false;await partial.handle({id:partialId,action:'adjust',field:'max health',mode:'heal',value:5});await flush();assert.deepEqual(partialCalls.map(x=>x.id),['partial-one','partial-two','partial-two']);assert.notEqual(partial.snapshot()?.id,partialId);partial.dispose();pass('partial pre-roll edit locks selection and only retries unfinished targets');
console.log(JSON.stringify({checks,success:true}));
