import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {writeFileSync} from 'node:fs';
const out=process.argv[2],handlers=new Map(),channels=[],controllers=[],modals=[],sent=[],report={realOwlbear:false,cases:[]};
let dropReplies=false;
const observed={role:'GM',player:{id:'owner',connectionId:'local',role:'GM',name:'Synthetic',color:'#ffffff',metadata:{}},party:[],items:[]};
globalThis.localStorage={getItem:()=>null,setItem:()=>{}};
globalThis.BroadcastChannel=class {constructor(name){this.name=name;channels.push(this);}postMessage(data){for(const channel of channels)if(channel!==this&&!channel.closed&&channel.name===this.name)queueMicrotask(()=>channel.onmessage?.({data}));}close(){this.closed=true;}};
const deliver=async(name,event)=>{for(const fn of [...handlers.get(name)||[]])await fn(event);};
globalThis.diceTestSDK={room:{id:'synthetic'},player:{setMetadata:async()=>{},getConnectionId:async()=>observed.player.connectionId},notification:{show:async()=>{}},modal:{open:async(data)=>modals.push(data),close:async()=>{}},broadcast:{onMessage:(name,fn)=>{if(!handlers.has(name))handlers.set(name,new Set());handlers.get(name).add(fn);return()=>handlers.get(name)?.delete(fn);},sendMessage:async(name,data,options)=>{sent.push({name,data,options});if(dropReplies&&name.endsWith('/reply'))return;if(options?.destination==='LOCAL')queueMicrotask(()=>void deliver(name,{connectionId:'local',data}));}}};
globalThis.diceTestObservation={read:async()=>observed,peek:()=>observed,onChange:()=>()=>{}};
globalThis.diceTestController=class {constructor(transport){this.transport=transport;this.bus=new BroadcastChannel('com.obr-suite/workbench-dice3d.v1:local:'+transport.id);controllers.push(this);}async init(){}dispose(){this.bus.close();}setProfile(){return Promise.resolve();}async submit(options){this.calls=(this.calls||0)+1;this.last=options;if(options.context?.label==='reject-submit')throw {message:'SDK synthetic rate limit',code:429};const die=options.preset?.dice[0]||{value:13,type:'d20'};this.bus.postMessage({type:'history',records:[{id:options.id,source:'local',name:'Synthetic',color:'#ffffff',at:Date.now(),results:[die.value],total:die.value+(options.modifier||0),kinds:['d20'],complete:true,secret:false,revealed:false,formulaData:{expression:'1d20',context:options.context,rows:[{operation:'sum',total:die.value+(options.modifier||0),dice:[{id:'d',kind:'d20',value:die.value,raw:die.value,kept:true,sign:1,flags:[]}]}]}}]});}};
const host=await import(pathToFileURL(out+'/dice-host.mjs').href),frame=await import(pathToFileURL(out+'/dice-frame.mjs').href);let thrown;
const check=(title,fn)=>{fn();report.cases.push(title);console.log('PASS '+title);};
try{
 await host.setupDice3d();controllers[0].bus.postMessage({type:'state',state:{ready:true}});await new Promise(r=>setTimeout(r,0));
 let value;try{value=await frame.submitCompat3d({itemId:'synthetic-token',rollId:'initiative-fixture',dice:[{type:'d20',value:17}],winnerIdx:0,modifier:3,label:'先攻'});}catch(error){thrown=String(error);}
 check('initiative iframe uses the existing background controller and overlay',()=>{assert.equal(controllers.length,1,JSON.stringify({controllers:controllers.length,modalOpens:modals.length,error:thrown}));assert.equal(modals.length,1);assert.equal(value,'initiative-fixture');assert.equal(controllers[0].last.preset.total,20);});
 check('frame submission remains LOCAL and preserves token, roll identity and modifier',()=>{assert(sent.some(p=>p.options?.destination==='LOCAL'&&p.data?.method==='compat'));assert.equal(controllers[0].last.context.itemId,'synthetic-token');assert.equal(controllers[0].last.modifier,3);assert.equal(controllers[0].last.context.rollerId,'owner');});
 await frame.submitDice3d({expression:'1d20+2',itemId:'synthetic-token',label:'公式'});check('formula iframe uses same owner',()=>assert.equal(controllers.length,1));
 const submissions=controllers[0].last,request=sent.find(p=>p.data?.method==='compat');const calls=controllers[0].calls;await deliver(request.name,{connectionId:'local',data:request.data});await new Promise(r=>setTimeout(r,0));check('same request retry cannot duplicate a roll',()=>assert.equal(controllers[0].calls,calls));await deliver(request.name,{connectionId:'remote-player',data:{...request.data,id:'forged-id'}});await new Promise(r=>setTimeout(r,0));check('remote request cannot roll through another player controller',()=>assert.equal(controllers[0].last,submissions));
 await assert.rejects(frame.submitDice3d({expression:'1d20',label:'reject-submit'}),/SDK synthetic rate limit/);report.cases.push('plain SDK rejection reaches caller with useful message');
 const beforeLost=controllers[0].calls;dropReplies=true;const missing=frame.submitDice3d({expression:'1d20',label:'lost-replies'});await new Promise(r=>setTimeout(r,0));const lost=sent.filter(p=>p.data?.method==='formula').at(-1);await deliver(lost.name+'/reply',{connectionId:'remote-player',data:{id:lost.data.id,result:'forged'}});await assert.rejects(missing,/结果暂不确定/);dropReplies=false;check('lost acknowledgement/result retry keeps one roll, rejects a remote reply, and reports unknown outcome',()=>assert.equal(controllers[0].calls,beforeLost+1));
 host.teardownDice3d();check('teardown removes the owner submission listener',()=>assert.equal(handlers.get(request.name)?.size||0,0));let ghost=0;const stop=frame.serveDiceSubmissions('local',async()=>{ghost++;return 'unwanted';});for(const fn of handlers.get(request.name)||[])fn({connectionId:'local',data:{id:'scene-change',method:'compat',data:{}}});stop();await new Promise(r=>setTimeout(r,0));check('teardown before queued execution cannot revive the owner',()=>assert.equal(ghost,0));assert(sent.some(p=>p.data?.id==='scene-change'&&p.data.error?.includes('场景已改变')));report.success=true;
}catch(error){report.error=String(error);report.controllers=controllers.length;report.modalOpens=modals.length;report.initialError=thrown;throw error;}finally{host.teardownDice3d();frame.teardownDice3d?.();writeFileSync(out+'/frame-results.json',JSON.stringify(report,null,2));}
