import assert from 'node:assert/strict';
import {setupWorkbenchDice,teardownWorkbenchDice,rolls} from '../src/workbench/dice';
import {setupDice3d,teardownDice3d} from '../src/workbench/dice3d';
import {setupTokenResults,setTokenResults,clearTokenResults,teardownTokenResults} from '../src/workbench/token-results';
const g=globalThis as any,handlers=new Map<string,Function>(),channels:any[]=[],controllers:any[]=[],opens:any[]=[],closed:any[]=[],observers=new Set<Function>();let pendingRead:((v:any)=>void)|undefined,readPending=false,initPending=false,rejectInit:((v:any)=>void)|undefined;
const observed={ready:true,role:'GM',player:{id:'owner',connectionId:'local',role:'GM',name:'Synthetic',color:'#ffffff',metadata:{}},party:[],items:[{id:'unit',visible:true,position:{x:0,y:0},metadata:{}}]};
g.localStorage={getItem:()=>null,setItem:()=>{}};g.sessionStorage=g.localStorage;
g.BroadcastChannel=class{messages:any[]=[];closed=false;onmessage:any;constructor(public name:string){channels.push(this);}postMessage(m:any){assert(!this.closed);this.messages.push(m);}close(){this.closed=true;}};
g.diceTestSDK={room:{id:'synthetic'},broadcast:{onMessage:(name:string,fn:Function)=>{handlers.set(name,fn);return()=>{if(handlers.get(name)===fn)handlers.delete(name);};},sendMessage:async()=>{}},modal:{open:async(o:any)=>{opens.push(o);},close:async(id:string)=>{closed.push(id);}},notification:{show:async()=>{}},action:{open:async()=>{}},player:{setMetadata:async()=>{}},viewport:{getPosition:async()=>({x:0,y:0}),getScale:async()=>1},scene:{grid:{getDpi:async()=>150}}};
g.diceTestObservation={read:()=>readPending?new Promise(resolve=>pendingRead=resolve):Promise.resolve(observed),peek:()=>observed,sceneEpoch:()=>1,onChange:(fn:Function)=>{observers.add(fn);return()=>observers.delete(fn);}};
g.diceTestController=class{disposed=false;constructor(public transport:any){controllers.push(this);}async init(){if(initPending){initPending=false;await new Promise((_,reject)=>rejectInit=reject);}}dispose(){this.disposed=true;}setProfile(){return Promise.resolve();}};
const flush=()=>new Promise(resolve=>setTimeout(resolve,0));let checks=0;const pass=(title:string)=>{checks++;console.log('PASS '+title);};
readPending=true;const old=setupWorkbenchDice();teardownWorkbenchDice();pendingRead!(observed);await old;await flush();assert.equal(handlers.size,0);assert.equal(controllers.length,0);assert.equal(channels.length,0);pass('pending workbench startup cannot revive subscriptions or renderer after teardown');
const token=setupTokenResults();teardownTokenResults();pendingRead!(observed);await token;assert.equal(channels.length,0);pass('pending token result startup cannot revive its channel after teardown');
readPending=false;await setupWorkbenchDice();await flush();rolls.push({rollId:'public',ts:1,itemId:'unit',total:16,label:'Synthetic save',dice:[],expression:'1d20',rollerColor:'#ffffff'} as any);const replay=handlers.get('com.obr-suite/dice-replay')!;const before=channels.reduce((n,c)=>n+c.messages.length,0);replay({connectionId:'foreign',data:{cid:'public'}});await flush();assert.equal(channels.reduce((n,c)=>n+c.messages.length,0),before);pass('remote history clicks cannot change local token labels');
const labels=()=>channels.filter(c=>!c.closed).flatMap(c=>c.messages).filter(m=>m.type==='token-results').at(-1);
const visible=()=>labels()?.groups.filter((v:any)=>v.visible)||[];
const click=(cid:string,action='toggle')=>replay({connectionId:'local',data:{cid,action}});
click('public');await flush();assert.deepEqual(visible().map((v:any)=>v.id),['history:public']);
click('public');await flush();assert.equal(visible().length,0);pass('same history click removes the label completely');
rolls.push({rollId:'second',ts:2,itemId:'unit',total:20,label:'Second',dice:[],expression:'1d20',rollerColor:'#ffffff'} as any);
click('public');click('second');await flush();assert.deepEqual(visible().map((v:any)=>v.id),['history:second']);
click('public','close');click('second');await flush();assert.equal(visible().length,0);pass('history replacement is exclusive and stale close cannot reset its toggle');
const grouped={rollId:'member',ts:3,collectiveId:'group-roll',itemId:'unit',total:14,label:'Group',dice:[],expression:'1d20',rollerColor:'#ffffff'} as any;rolls.push(grouped);setTokenResults('group-roll',[grouped]);await flush();
click('group-roll');await flush();assert.deepEqual(visible().map((v:any)=>v.id),['history:group-roll']);
click('group-roll');await flush();assert.equal(visible().length,0);setTokenResults('group-roll',[grouped]);await flush();assert.equal(visible().length,0);pass('group history cancels both duplicates and late group results stay dismissed');
click('public');await flush();observed.role='PLAYER';for(const fn of observers)fn();await flush();assert.equal(visible().length,0);observed.role='GM';for(const fn of observers)fn();pass('viewer permission changes clear every existing token label');
const originalPosition=g.diceTestSDK.viewport.getPosition;let resolvePosition:Function=()=>{};g.diceTestSDK.viewport.getPosition=()=>new Promise(resolve=>resolvePosition=resolve);
setTokenResults('pending',[grouped]);await flush();clearTokenResults('pending');resolvePosition({x:0,y:0});await flush();assert.deepEqual(labels().groups,[]);g.diceTestSDK.viewport.getPosition=originalPosition;pass('cancel during an in-flight coordinate read still publishes the empty result');
const group=handlers.get('com.obr-suite/workbench/group-result-control')!;readPending=true;group({connectionId:'local',data:{id:'group-old',action:'show'}});teardownWorkbenchDice();pendingRead!(observed);await flush();assert(channels.every(c=>c.closed));pass('awaiting group control does not revive token service after teardown');
readPending=false;initPending=true;const first=setupDice3d();await flush();const oldController=controllers.at(-1);teardownDice3d();const second=setupDice3d();await second;const newController=controllers.at(-1);assert.notEqual(oldController,newController);rejectInit!(Error('synthetic old init failure'));await first;await flush();assert.equal(newController.disposed,false);assert.equal(oldController.disposed,true);assert.equal(opens.length,2);teardownDice3d();pass('old initialization failure cannot tear down the new controller or reopen an old overlay');
console.log(JSON.stringify({checks,success:true}));
