import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash,webcrypto} from 'node:crypto';
import {parseFormula,evaluateFormula,initialPhysicalCount} from '../extensions/workbench-dice3d/src/research/formula';
import {percentileValue,validateRecipe} from '../extensions/workbench-dice3d/src/suite-formula';
import {packReveal,unpackReveal} from '../extensions/workbench-dice3d/src/suite-reveal';
import {SecretKeys} from '../extensions/workbench-dice3d/src/secret-keys';
import {shapeSymmetries,maskRoll} from '../extensions/workbench-dice3d/src/hidden-roll';
import {materialCatalog,STYLE_CHOICES} from '../extensions/workbench-dice3d/src/material-styles';
import {workbenchDice3dPlugin} from './workbench-dice3d-vite';
import {adapt3dHistory} from './workbench-dice3d-history.mjs';
Object.defineProperty(globalThis,'crypto',{value:webcrypto});let checks=0;
const ok=(label:string,test:()=>void)=>{test();checks++;console.log('PASS '+label);};
const base='extensions/workbench-dice3d/public/',catalog=materialCatalog(JSON.parse(readFileSync(base+'assets/catalog.json','utf8')));
ok('exactly five active styles',()=>{assert.equal(STYLE_CHOICES.length,5);assert(!['comic_print','flowing_ink','neon_runes'].some(id=>Object.hasOwn(catalog.themes,id)));});
ok('persistent startup independent of UI',()=>assert(readFileSync('src/workbench/background.ts','utf8').includes('void setupWorkbenchDice()')));
const activePlugin=workbenchDice3dPlugin(true),adaptedIndex=(activePlugin.transform as Function)(readFileSync('src/modules/dice/index.ts','utf8'),'/src/modules/dice/index.ts');
ok('old feature toggle cannot tear down persistent 3D',()=>assert(adaptedIndex.includes('if (WORKBENCH_DEV) { return; }')));
const lock=JSON.parse(readFileSync(base+'vendor/lock.json','utf8'));for(const [file,digest] of Object.entries(lock.files))ok('locked '+file,()=>assert.equal(createHash('sha256').update(readFileSync(base+'vendor/'+file)).digest('hex'),digest));
for(const [kind,asset] of Object.entries(catalog.dice))ok('proper hull symmetries '+kind,()=>assert(shapeSymmetries(asset).length>=asset.outcomes.length));
for(const [formula,count] of [['1d100',2],['adv(1d20)',2],['adv(1d20,2)',3],['repeat(3,2d6+5)',6],['2d4*3',2],['resetmin(1d6,6)',1]] as const)ok('frontier '+formula,()=>assert.equal(initialPhysicalCount(parseFormula(formula)),count));
for(const [a,b,c] of [[0,0,100],[0,9,9],[90,0,90],[90,9,99]])ok('percentile '+a+'/'+b,()=>assert.equal(percentileValue(a,b),c));
const request:any={id:'mask',source:'a',name:'A',count:1,kind:'d6',seed:123,modifier:5,theme:'ink_sketch',visibility:'self',recipe:true,formula:'1d6+5',context:{rollerId:'a',itemId:null,label:'secret'}};
const roll:any={version:2,request,kinds:['d6'],results:[4],fps:120,frames:2,poses:new Float32Array([0,0,0,0,0,0,1,0,0,0,0,0,0,1]),contacts:[],duration:1/120,formulaData:{ids:['mask:0'],rows:[],births:[0],timeline:{decisionAt:0,clamps:[]},expression:'1d6+5'}};
const masked=maskRoll(roll,catalog);ok('mask all secrets',()=>{assert.equal(masked.roll.formulaData,undefined);assert.equal(masked.roll.request.formula,undefined);assert.equal(masked.roll.request.context,undefined);assert.equal(masked.roll.request.seed,0);assert.deepEqual(masked.roll.results,[0]);});
ok('missing model explicit error',()=>assert.throws(()=>validateRecipe({...request,formula:undefined,preset:{dice:[{type:'d7',value:3}],total:3}})));
const large={...masked.details,formulaData:{...masked.details.formulaData,rows:Array.from({length:100},(_,i)=>({id:i,raw:i,value:i,flag:'secret-'+i,random:Array.from(webcrypto.getRandomValues(new Uint8Array(16)))}))}};
const packed=await packReveal(large);ok('large reveal below transport budget',()=>assert(packed.length<14000));assert.deepEqual(await unpackReveal(packed),large);checks++;
const owner=new SecretKeys('a'),viewer=new SecretKeys('b');await Promise.all([owner.ready,viewer.ready]);await owner.remember('b',viewer.publicKey);await viewer.remember('a',owner.publicKey);const seal=await owner.seal(large as any,'gm',['a','b']);assert.deepEqual(await viewer.open(seal,'a','mask'),large);checks++;
ok('unauthorized reader has no plaintext',()=>{assert(!JSON.stringify(seal).includes('secret-'));});
const outsider=new SecretKeys('c');assert.equal(await outsider.open(seal,'a','mask'),null);checks++;
const plugin=workbenchDice3dPlugin(false);ok('stable adapter disabled',()=>assert.equal((plugin.transform as Function)(readFileSync('src/modules/dice/index.ts','utf8'),'src/modules/dice/index.ts'),undefined));
for(const file of ['history-page','panel-page']){const source=readFileSync('src/modules/dice/'+file+'.ts','utf8'),adapted=adapt3dHistory(source);ok('row total '+file,()=>assert(adapted.includes('entry._3dRows?.[r]?.total')));ok('row modifier '+file,()=>assert(adapted.includes('entry._3dRows?.[rowIdx]?.modifier ?? entry.modifier')));}
const rows=await evaluateFormula(parseFormula('repeat(2,2d4*3)'),async groups=>groups.map((g,i)=>Array.from({length:g.count},(_,j)=>({id:i+':'+j,value:i+j+1}))));ok('independent repeat multiplication',()=>assert.deepEqual(rows.map(r=>r.total),[9,15]));
console.log(JSON.stringify({checks,success:true}));
